### ISSUE TITLE
Handling HTTP to HTTPS redirection

### ISSUE THREAD

**Issue by michaelwilde** [vfarcic/docker-flow-proxy#102]
As a "regular user" I would like to hit the HTTP port for a domain, and if that domain is *in fact* listening on HTTPS, have a redirection occur automatically.

Specifically in my case, i have https://registry.splunk.com.  I believe there *was* a time when DTR had/has a proxy that listens on 80 and redirects to 443, but i have users that just type in "registry.splunk.com" in their browser which defaults to port 80. 

Docker Flow: Proxy presents the expected Docker Flow: Proxy

503 Service Unavailable

No server is available to handle this request.

Understandable, because DTR isn't a "Service" in docker's sense.. its a compose application as far as i know.. so i don't think i can do a service update and add some labels for swarm-listener to pick up on.

I was thinking of hardcoding something, but this might be a feature to add to proxy when it launches

Maybe some global settings, and a service specific setting too. (me, i'd just globalize registry.splunk.com, as it will probably never be changed)

**Comment by vfarcic** [comment]
The release 1.149 adds the feature to redirect all http requests to https through the new parameter `httpsOnly=true`. Can you please try it out and let me know how it went?

**Comment by hamburml** [comment]
I just tried it out. It works on the service I set the httpsOnly label. Strangely all other services which don't have this label are also redirected to their https equivalent.

**Comment by vfarcic** [comment]
@hamburml You're right. I forgot to limit https redirection to ACL of a service. I just made a fix. It's available as release 1.150. It passed all automated tests but I haven't had time to try it out manually. This is one more case I'm making changes on the airport while waiting to board a plane. Can you please try it out and let me know how it went?

**Comment by hamburml** [comment]
@vfarcic works perfect.

**Comment by vfarcic** [comment]
Done as [release 1.153](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.153).
