### ISSUE TITLE
aclName not setting acl name (setting Backend instead)

### ISSUE THREAD

**Issue by mlschuh** [vfarcic/docker-flow-proxy#104]
Hi there,

I'm working with the `aclName` interface (re #35) and have noticed that it looks to not rename the ACL but rather the backend.

I'm adding a service with the following label:

    --label com.df.aclName=zzz 

which leads to the following:

    acl url_isaac_app_service80 path_beg /
    use_backend zzz-be80 if url_isaac_app_service80

    backend zzz-be80
    mode http
    server isaac_app_service isaac_app_service:80

It happily places the backend zzz at the end of the file (Which HAProxy really doesn't care about) but adding other services puts the ACL out of order, leading to this ACL essentially clobbering all others below it. The concept of the aclName is almost a perfect fit for my use case catch-all (other than an HTTP based `default_backend`) and is a very handy thing to have in other use cases.

-Mitch

**Comment by vfarcic** [comment]
You're right. I made a change recently and cause the ordering to stop working. I'll correct it ASAP.

**Comment by vfarcic** [comment]
I made a quick fix while waiting between two airplanes. This time, there is a test that validates the feature. However, I haven't had time to try it out manually as well (they're calling me to board).

The build will be available in a few minutes (Travis is crunching it while I write this). It'll be version 1.146. Can you try it out and let me know if it works correctly?

**Comment by mlschuh** [comment]
Travis passed and I pulled it down. The order is now being respected via the name of the ACL. However, `aclName` is not being set as the name of the ACL itself (but is the name of the backend) so it's still a bit off from what I'm guessing expected behavior is suppose to be.

**Comment by vfarcic** [comment]
That should not matter. Service name keeps being the identifier. I'm using ACL names only to sort the records before writing them to the config file.

**Comment by mlschuh** [comment]
Hmmm, I'm still getting this behavior when running on 1.146 with the zzz label:

    acl url_isaac_alert_service80 path_beg /api/v1/alerts path_beg /docs/v1/alerts
    use_backend isaac_alert_service-be80 if url_isaac_alert_service80
    acl url_isaac_app_service80 path_beg /
    use_backend zzz-be80 if url_isaac_app_service80
    acl url_isaac_controlpanel_service80 path_beg /api/v1/controlpanels path_beg /docs/v1/controlpanels
    use_backend isaac_controlpanel_service-be80 if url_isaac_controlpanel_service80

(I'm also a bit confused as to why there are multiple path_beg in the file but I'll investigate that a bit more and open another ticket if it is easily reproducible as I suspect it's related with how I start/stop services). It's times like this where I wish I knew Go.

**Comment by mlschuh** [comment]
It does look like it's sorting by ACL name (like you said), but not taking `aclName` into account in said sort. If I set the service name to `z_isaac_app_service`, it dutifully puts it at the bottom of the list.

**Comment by vfarcic** [comment]
zzz is the `serviceName` and isaac_app_service `aclName`? If that's the case, I think that the ordering is correct. It is ordered by ACL name. If not present, service name is used instead.

If you specified multiple paths (separated by comma) they are all included in ACL.

Can you send me the commands you used to create services? That would help me understand better the problem. It's late where I am (2am) so I might be completely off the track.

**Comment by vfarcic** [comment]
I'm not sure what you mean by *It does look like it's sorting by ACL name (like you said), but not taking aclName into account in said sort*. That sentence sounds contradictory.

**Comment by mlschuh** [comment]
No worries, service is below. I think this will make a lot more sense now:

    docker service create \
      --replicas 1 \
      --name isaac_app_service \
      -e ROOT_URL=http://127.0.0.1 \
      -e MONGO_URL=mongodb://xx/meteor \
      -e MONGO_OPLOG_URL=mongodb://xx/local?authSource=admin \
      -e METEOR_SETTINGS={\"public\"\:{\"environment\"\:\"PRODUCTION\"}} \
      -p 8020:80 \
      --label com.df.aclName=zzz \
      --label com.df.notify=true \
      --label com.df.distribute=true \
      --label com.df.servicePath=/ \
      --label com.df.port=80 \
      --network proxy \
      --network isaac_net \
      $1


My reference before was to say that it's not using the `--label com.df.aclName=zzz` in the sort but rather url_isaac_app_service. 

No rush, it's easy enough to work around for the time being.

**Comment by vfarcic** [comment]
The names of ACLs and backends were reversed. I don't think it should have affected the functional part since they were sorted by ACL name no matter which name was used in the config.

It is still a bug and confusing.

Please wait for 5 minutes until the release 1.147 is finished and try it again. I think that it should be OK this time.

**Comment by mlschuh** [comment]
Alas, still not quite there. It's updating the ACL name however it looks like the sort happens before then. No rush at all on this, it's a bit trickier than expected.

    acl url_isaac_alert_service80 path_beg /api/v1/alerts
    use_backend isaac_alert_service-be80 if url_isaac_alert_service80
    acl url_zzz80 path_beg /
    use_backend isaac_app_service-be80 if url_zzz80
    acl url_isaac_controlpanel_service80 path_beg /api/v1/controlpanels

**Comment by vfarcic** [comment]
It is, indeed, a bit trickier. I was sorting it by service name since that is the key of the map where I keep services. That was very silly from my part and it just proves that I should not code while in the airport and rushing things.

Assuming it's not urgent, I'll fix this during the weekened (if not before).

**Comment by vfarcic** [comment]
How about the release 1.148 (will be done soon)? This is my last attempt to do something in a hurry (it's 3am over here). If it still doesn't work, I'll fix it calmly during the weekend.

**Comment by mlschuh** [comment]
I'll have a check in the morning, the weekend is plenty quick for me.

**Comment by mlschuh** [comment]
Confirmed working. All set!
