### ISSUE TITLE
allow specifying more settings in service labels

### ISSUE THREAD

**Issue by raarts** [vfarcic/docker-flow-proxy#106]
Most specifically client, server, tunnel timeouts, because some of my services can be working up to 5 minutes per http request. Others use websockets.

**Comment by vfarcic** [comment]
Do you have a snippet of an existing configuration you'd like to accomplish? The amount of config options and combinations supported by HAProxy is almost unlimited. An example of your use case would help me focus on you immediate needs.

**Comment by vfarcic** [comment]
Also, it would be helpful if you could provide a set of commands that would validate this feature. Do you have a public service that could be used for testing?

**Comment by raarts** [comment]
For me currently it's probably only `timeout server` and `timeout tunnel`. It's not really public, I emailed you the address.

**Comment by vfarcic** [comment]
The option to change the default value of `timeout server` already existed in the proxy. I just added the option to specify `timeout tunnel` as well. It is available as the [release 1.154](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.154).

Both settings can be changed through environment variables `TIMEOUT_SERVER` and `TIMEOUT_TUNNEL`. See the [config](http://proxy.dockerflow.com/config/) documentation for more please.

Please don't hesitate to contact me if it does not work as expected or you need more info.

**Comment by raarts** [comment]
I'm very sorry. I absolutely wasn't clear. If I specify TIMEOUT_SERVER this applies to ALL my services, and I meant support for something like a com.df.timeout_server label, so it could be applied per-service.

**Comment by vfarcic** [comment]
Please take a look at the [release 1.156](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.156) and let me know if that's what you were looking for. If it is, I would appreciate if you could try it out and let me know if it works as expected.

**Comment by raarts** [comment]
Yes this work as expected. Thanks. (remark: the generated configfile misses a trailing LF).

I never used haproxy before, but indeed it has a lot of options. Creating a universal auto-reconfiguring proxy will be challenging, using service labels only. On the other hand, maybe there are only two most-used cases: (1) proxying multiple backend services using virtual hostnames for each, and (2) proxying multiple backends under multiple basepaths. 
Anything more complicated will probably need a custom written config file.

**Comment by vfarcic** [comment]
Thanks for trailing LF note. I added it to the code (it'll be released in a few minutes).

I think that the project has many more combinations than those two. It will continue growing to accommodate many additional use cases. Feel free to create an issue if you have a specific use case and I'll add it as long as that would not hurt other users. In the meantime, the existing combinations can be easily extended by providing custom templates. The only downside is that using templates requires knowledge of HAProxy config.
