### ISSUE TITLE
Minimum droplets required?

### ISSUE THREAD

**Issue by katopz** [vfarcic/docker-flow-proxy#11]
Maybe I'm skip reading but I just can't see minimum requirement for this?
Let say if I use Digital Ocean. What's recommended plans for this please?

And usually Digital Ocean love to kill over network by droplets. Which mean 2 mirror droplets setup would ideal so the question is it'll work with this setup?

Thanks!

**Comment by vfarcic** [comment]
Speaking in general terms, the requirement for this is to have at least one Consul instance running somewhere inside the cluster and that service information is stored in it before the proxy is reloaded. The easiest way to get the information to Consul is, as far as I know, through Registrator (running on each server). It listens to Docker Engine events and whenever a new container is run, it stores the information in a registry (in this case Consul). Such a combination should work no matter which hosting provider is used.

I tend to have at least two proxies and DNS pointing to both so that in case one of them fails, the other would take over completely. It truly depends on whether there is one cluster or more and their size.

**Comment by katopz** [comment]
Thanks for sharing, This should be fun :)

**Comment by vfarcic** [comment]
Please let me know how it went. If you have some trouble, we can organize a
chat with shared screens.

On Thu, Apr 21, 2016 at 5:23 PM katopz <notifications@github.com> wrote:

> Thanks for sharing, This should be fun :)
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/vfarcic/docker-flow-proxy/issues/11#issuecomment-212970238>
>
-- 
Viktor Farcic

Blog:
TechnologyConversations.com

Books:
The DevOps 2.0 Toolkit (http://www.amazon.com/dp/B01BJ4V66M or
https://leanpub.com/the-devops-2-toolkit)
Test-Driven Java Development (
http://www.amazon.com/Test-Driven-Java-Development-Viktor-Farcic-ebook/dp/B00YSIM3SC
)

**Comment by katopz** [comment]
Thanks for your kind, I just buy your book just because of that. ;)

BTW I kinda love diagram, wireframe which easier for me to understand it like mind map more than plenty of text so it would be nice if you please add more picture of that.

I'm super newbies in this fields (just learn to setup SSL Nginx HTTP2 CORS a week ago) so it should take sometime to unlock to next step. 

Anyway please keep doing this I'm following your blog and become your big fan starting today...so more picture less text! ;)

Cheers!

**Comment by vfarcic** [comment]
Hi,

Thank you for the feedback. It is really valuable for my work. The more
feedback I get, the better I do my job. The next article will continue in
the same fashion and with quite a few diagrams.

On Thu, Apr 21, 2016 at 7:14 PM katopz <notifications@github.com> wrote:

> Thanks for your kind, I just buy your book just because of that. ;)
>
> BTW I kinda love diagram, wireframe which easier for me to understand it
> like mind map more than plenty of text so it would be nice if you please
> add more picture of that.
>
> I'm super newbies in this fields (just learn to setup SSL Nginx HTTP2 CORS
> a week ago) so it should take sometime to unlock to next step.
>
> Anyway please keep doing this I'm following your blog and become your big
> fan starting today...so more picture less text! ;)
>
> Cheers!
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/vfarcic/docker-flow-proxy/issues/11#issuecomment-213022717>
>
-- 
Viktor Farcic

Blog:
TechnologyConversations.com

Books:
The DevOps 2.0 Toolkit (http://www.amazon.com/dp/B01BJ4V66M or
https://leanpub.com/the-devops-2-toolkit)
Test-Driven Java Development (
http://www.amazon.com/Test-Driven-Java-Development-Viktor-Farcic-ebook/dp/B00YSIM3SC
)
