### ISSUE TITLE
Preserve client IP

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/docker-flow-proxy#114]
Add the feature to preserve client IP

**Comment by flaviuspopan** [comment]
This would be extremely helpful as it would allow you to filter by whitelisted, VPN-only IPs :)

**Comment by vfarcic** [comment]
That is, at the moment, not possible if  Overlay network is used. Docker is working on this issue and this ticket is more of a reminder to myself to add it to the proxy as soon as Docker releases the fix.

**Comment by morsik** [comment]
You need to use workaround right now: http://stackoverflow.com/questions/39854682/log-clients-real-ip-address-in-docker-swarm-1-12-when-accessing-a-service

```
--publish mode=host,target=80,published=80 \
--publish mode=host,target=443,published=443 \
```

You must be aware that with this you won't be able to run more than 1 docker-flow-proxy replica on the same node, so I run that with `--mode global` anyway.

**Comment by joelchen** [comment]
@vfarcic Is https://github.com/moby/moby/issues/25526 the issue to follow for Docker's fix?

**Comment by vfarcic** [comment]
@joelchen That's the one.

**Comment by remy-tiitre** [comment]
Preserving client ip with overlay (or to be more accurate - ingress) is not possible but we should still have an option to restrict IPs from accessing certain services. Like morsik pointed out, you can publish docker-flow-proxy to host and then you have the correct client ip.

**Comment by vfarcic** [comment]
I'll close this issue since there does not seem to be anything we can do from DFP side. Publishing DFP to host is a workaround. Docker folks are unlikely to change how ingress network works.

**Comment by Jacq** [comment]
> You need to use workaround right now: http://stackoverflow.com/questions/39854682/log-clients-real-ip-address-in-docker-swarm-1-12-when-accessing-a-service
> 
> ```
> --publish mode=host,target=80,published=80 \
> --publish mode=host,target=443,published=443 \
> ```
> You must be aware that with this you won't be able to run more than 1 docker-flow-proxy replica on the same node, so I run that with `--mode global` anyway.

I am running also the proxy in mode global but I would like to agregate the stats from all haproxy instance. I am currently running a haproxy exporter to scrape the stats and send them to prometheus but with this recent change to global mode I will need to instance the exporters also in global mode and perform then an agregation of the stats. Do you know if there is an easier way to agregate the stats from the different haproxy?

**Comment by vfarcic** [comment]
I don't think there's an easier way to do that @Jacq
