### ISSUE TITLE
Allow modifying global section of haproxy.cfg

### ISSUE THREAD

**Issue by faisyl** [vfarcic/docker-flow-proxy#129]
I need to add a "stats socket ..." line to the global section of haproxy so I can monitor haproxy stats using a unix socket bound to a local volume when running as a service. Would it be possible to add a new env var for this on the lines of EXTRA_FRONTEND? I could implement it and send you a PR if needed.

**Comment by vfarcic** [comment]
Sending a PR is great :)

**Comment by faisyl** [comment]
Change is tested and ready. Can I have a branch to send a PR against?

**Comment by vfarcic** [comment]
Just created a branch `issue-129`.

**Comment by vfarcic** [comment]
Do you feel it's working correctly? Shall I close this issue?

**Comment by faisyl** [comment]
Yes please. All tests work fine.  Now my whole stack works without custom
modifications.  Thanks a bunch for all the help and support!

On Feb 14, 2017 11:39 PM, "Viktor Farcic" <notifications@github.com> wrote:

Do you feel it's working correctly? Shall I close this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vfarcic/docker-flow-proxy/issues/129#issuecomment-279787522>,
or mute the thread
