### ISSUE TITLE
Standing up a flow proxy on google cloud

### ISSUE THREAD

**Issue by faddat** [vfarcic/docker-flow-proxy#13]
Here's what I got:

**docker-flow-proxy-demo-environments.sh**
```
#!/usr/bin/env bash

set -e

docker-machine create -d google --google-project hip-hangout-126906 proxy

export DOCKER_IP=$(docker-machine ip proxy)

export CONSUL_IP=$(docker-machine ip proxy)

eval "$(docker-machine env proxy)"

docker-compose up -d consul proxy
docker-machine create -d google --google-project hip-hangout-126906 --google-disk-size 200 \
    --swarm --swarm-master \
    --swarm-discovery="consul://$CONSUL_IP:8500" \
    --engine-opt="cluster-store=consul://$CONSUL_IP:8500" \
    --engine-opt="cluster-advertise=0.0.0.0:2376" \
    swarm-master
docker-machine create -d google --google-project hip-hangout-126906 --google-disk-size 200 \
    --swarm \
    --swarm-discovery="consul://$CONSUL_IP:8500" \
    --engine-opt="cluster-store=consul://$CONSUL_IP:8500" \
    --engine-opt="cluster-advertise=0.0.0.0:2376" \
    swarm-node-1
docker-machine create -d -google --google-project hip-hangout-126906 --google-disk-size 200 \
    --swarm \
    --swarm-discovery="consul://$CONSUL_IP:8500" \
    --engine-opt="cluster-store=consul://$CONSUL_IP:8500" \
    --engine-opt="cluster-advertise=0.0.0.0:2376" \
    swarm-node-2
eval "$(docker-machine env swarm-master)"
export DOCKER_IP=$(docker-machine ip swarm-master)
docker-compose up -d registrator
eval "$(docker-machine env swarm-node-1)"
export DOCKER_IP=$(docker-machine ip swarm-node-1)
docker-compose up -d registrator
eval "$(docker-machine env swarm-node-2)"
export DOCKER_IP=$(docker-machine ip swarm-node-2)
docker-compose up -d registrator
```

THe error message:  After setting up the first worker node, when the second begins, I get this:

```
Error creating machine: Error running provisioning: Error while creating container: 409 Conflict: Conflict. The name "/swarm-agent" is already in use by container 5b6d8cc08a44dc6d862f1b4d13a77f7de8617dd0eaaa3872d636f22cdcd2547d. You have to remove (or rename) that container to be able to reuse that name.
```

Found it.  Failed to change docker environment back to default when starting the cluster.

**Comment by vfarcic** [comment]
Great! I'm glad it worked. Please let me know what you think of the project. Feel free to contact me if you have any questions or you need help.

**Comment by faddat** [comment]
Ya wanna know what I think about the project, okay here goes!

**Your workflow is the first automated docker reverse proxy system that I've used that actually functions as advertised.  **

I think it's utterly fantastic, because it does everything you claim it does, and nothing more.  Youve done very well with this one, @vfarcic

**Comment by vfarcic** [comment]
Thank you. It feels great hearing something like that and motivates me to proceed.

Proxy failover feature is coming soon.

**Comment by faddat** [comment]
Nice!  How will/does the fail over feature work?  I spotted the branch, but haven't played with it at all.

**Comment by vfarcic** [comment]
I merged the branch into the main yesterday. The feature is now part of the release 1.0.

When the proxy is started, it loads all the data from Consul and creates HAProxy configurations. That way as long as at least one Consul instance is running, data is always available and the proxy can be started or moved anywhere. If, for example, the whole server with the proxy dies, all you have to do is bring it up somewhere else and it will continue where it left. You can find more information in [Proxy Failover](https://github.com/vfarcic/docker-flow-proxy#proxy-failover) section of the project README. Soon I'll write a more detailed article on the subject.

Try it out and let me know what you think. Please note that you'll have to upgrade the proxy container.
