### ISSUE TITLE
Allow to use "http_x_forwarded_proto" as the real "host" for "httpsOnly" redirection

### ISSUE THREAD

**Issue by ecentinela** [vfarcic/docker-flow-proxy#130]
At this moment, I’m using an AWS Elastic Load Balancer that is sending the incoming 443 (https) to internal 80 (http). This allows me to set the SSL certificate in AWS (super easy setup) and not inside all my containers.

But now, I have the problem that HAProxy thinks that the request comes from a 80 port and with the "httpsOnly" setting, it redirect the request to the port 443.

Then, the ELB detects the incoming from 443 and forward it to 80. Again to the HAProxy...

This is a never-ending-loop.

If we can configure the "http_x_forwarded_proto" as the real "host" for being used in the "httpsOnly" this loop will never occur.

At this moment, I'm facing this situation, configuring the NGINX that exists after the HAProxy, but then I need to configure it in every service.

**Comment by vfarcic** [comment]
Could you provide a sample that could be used for testing whether the feature is implemented correctly and, later on, as documentation? That would save me a bit of time...

**Comment by vfarcic** [comment]
I just added `http-request add-header X-Forwarded-Proto https if { ssl_fc }` to the backend of a service that has `httpsOnly` set to true. However, I'm in a middle of an event and could not test the change. Can you try it out and let me know whether it fixes the problem? It's available as release 1.184 in Docker Hub.

**Comment by ecentinela** [comment]
I have tested your code and I think that is really solving the problem I posted.

In the commit code (https://github.com/vfarcic/docker-flow-proxy/commit/95dcfd41793e14008d94742c70b09c2c4be0ceaa) I can see that you set the proto property (client scheme) if I configure the service with the httpsOnly setting. This is ok, but it's not the problem I was facing.

In a "normal" case, setting the httpsOnly as true, will redirect the http request to https successfully and without the need to use the "proto".

1.- "Normal" AWS ELB configuration:

Load Balancer Port: 80 => Instance Port 80
Load Balancer Port: 443 => Instance Port 443

In this scenario, just setting the httpsOnly to true will work. All 80 requests will be redirected to 443. The only drawback with this setting is that you will need to configure every service with the SSL certificate in order to handle the 443.

2.- "My scenario" AWS ELB configuration:

Load Balancer Port: 80 => Instance Port 80
Load Balancer Port: 443 => Instance Port 80

In this scenario, setting the httpsOnly to true will create a never-ending-loop. All 80 requests will be redirected to 443. Internally, the ELB receives the 443 and forward them to instance port 80. Then HAProxy receives the request in port 80 and redirect it again to 443.

That was the reason I requested to detect the proto in HAProxy. If HAProxy detects the proto too and not only the real scheme, then it can detect that the client scheme is HTTPS regardless the protocol that the AWS ELB is forwarding and then HAProxy stops the redirection.

This is something that I can do directly with NGINX when not using HAProxy:

```
location / {
    if ($http_x_forwarded_proto != 'https') {
        rewrite ^ https://$host$request_uri? permanent;
    }
    proxy_pass http://web-upstream;
}
```

Hope it helps.

**Comment by vfarcic** [comment]
Normally, you would expose 443 to outside traffic (as you do with ELB), and forward it to HTTP reports internally. Is there a reason you need `httpsOnly`? Without it, the current configuration should work. External traffic is coming to 80 or 443 and forwarded to the rest of the system (to DFP and from there other services).

Or... configure ELB to forward 80>80 and 443>443 (instead 80).

I'm just trying to understand the use case so that I can add the correct feature that would be useful to others as well.

**Comment by ecentinela** [comment]
If I configure the 443>443 I need to configure all the services to handle the SSL certificate, right?

I was trying to solve this case using just the ELB configuration (it's waaaaay easier than setting nginx / anything up).

If I configure NGINX instead of DFP for being used as proxy, I have available the $http_x_forwarded_proto property and I can redirect the user accordingly using this procedure.

But it seems that this is not posible using the DFP. If I don't set the httpsOnly, I do not get the http_x_forwarded_proto, and if I set it, because the requests that HAProxy does not have the HTTPS (is converted by the ELB) it is redirected every time.

I need a solution for this, because using DFP instead of NGIN for the proxy it's a lot better. But this is a stopper at this moment.

**Comment by hamburml** [comment]
But why do you need this scenario:

`outside -> [443 ELB -> 443 DF-P -> 80 Service]`

This should work, shouldn't it?

`outside -> [443 ELB -> 80 DF-P -> 80 Service]`

Note `[ ... ]` is your private cloud/system/docker swarm/...

httpsOnly only says to DF-P that when a HTTP-Request for this domain comes redirect it to HTTPS. But the TLS termination is done from ELB and not from DF-P. So it's not necessary to set httpsOnly. If you want a redirect from HTTP to HTTPS you need so set this option at the ELB level (I have no idea if this is possible). Every request from outside via HTTP (80) would then be redirected at ELB level to the client with `use https (443)`. 

If maybe you want to secure the connection inside your docker swarm you can also `--opt encrypted` on your docker network. You can use port 80 inside your docker swarm but it's still unreadable (see https://docs.docker.com/engine/userguide/networking/overlay-security-model/)

> If I configure the 443>443 I need to configure all the services to handle the SSL certificate, right?

Yes, when you really want `outside -> [443 ELB -> 443 DF-P -> 80 Service]`. Because ELB does TLS termination and redirects to DF-P via HTTPS (443) and DF-P does TLS termination, too.

**Comment by ecentinela** [comment]
Hi @hamburml,

What I'm trying to do is your second option:

`outside -> [443 ELB -> 80 DF-P -> 80 Service]`

But then I need to redirect the http requests to the https version inside my services. It's ok for me, but I cannot do it, because I'm not receiving the "https" or the "proto" header, so, I can't know if the requests comes from http or https, because HAProxy always sends me in http.

Any idea about doing this?

PD: at this moment I have NGINX instead of HAProxy in this way:

`outside -> [443 ELB -> 80 NGINX PROXY -> 80 Service]`

In this scenario with NGINX, I have the proto header and I know that the requests comes in https even when NGINX receives it in HTTP by the ELB.

```
location / {
    if ($http_x_forwarded_proto != 'https') {
        rewrite ^ https://$host$request_uri? permanent;
    }
    proxy_pass http://web-upstream;
}
```

**Comment by vfarcic** [comment]
I, finally, got it. There should be a logic that redirects to https if scheme is NOT https and there is NO proto https. I can add that logic to the proxy.

The only problem is time. I'm fully engaged this week and won't be able to dedicate much time to this project. What would help me a lot if you could find the condition that should be added (i.e. HAProxy equivalent of "is there https proto"). With that info, I'd need only a few minutes to add it to the code.

**Comment by hamburml** [comment]
@vfarcic Could this work?

At first we check if x-forwarded-proto is found in the header of the request (which is set via ELB for example). When it is found dont-redirect backend is used (which forwards to the service via port 80 for example). When it's not found this means the redirect is from http (DF-P is directly used, without ELB for example) and browser should redirect to https.

```
acl hdr_x-forwarded-proto hdr(x-forwarded-proto)
use_backend dont-redirect if hdr_x-forwarded-proto
use_backend redirect-to-https if [!]hdr_x-forwarded-proto
```

**Comment by ecentinela** [comment]
I'm afraid I cannot help you with this, guys. This is the first time I'm working with HAProxy :(
I can, of course, tests any docker image you need.

As I understand, the logic should be something like:

`if $scheme AND $scheme = http && $proto AND $proto = https > redirect`

If it's ok, I think that your previous code is not this case, right?

**Comment by vfarcic** [comment]
@ecentinela I just made a new release but did not have time to test it with AWS (I do have automated tests though). Can you try it out and let me know how it went.

**Comment by vfarcic** [comment]
@ecentinela I forgot to add the most important info... Please add `com.df.redirectWhenHttpProto=true` to service labels.

**Comment by ecentinela** [comment]
@vfarcic sorry for the delay in testing this, but it has been a busy day. The good news is that seems that it works perfectly!

I will do more tests this weekend, so, please, don't close this issue yet. I will report here the results I get.

Thank you very much!

**Comment by vfarcic** [comment]
That's great to hear. Looking forward to your feedback...

**Comment by ecentinela** [comment]
I deployed a few services putting this setting and all of them are working perfectly.

Just a question: in case I do not enable the "com.df.redirectWhenHttpProto", the "proto" property is still there in order to use it inside the service (for ex: nginx)? If not, I think that it should because it opens so many possibilities to manually control the redirection depending on the "proto" + "host" in the same service.

**Comment by ecentinela** [comment]
@vfarcic I have create other services without this setting and seems that they are being redirected to https too. Makes it sense?

**Comment by vfarcic** [comment]
> Just a question: in case I do not enable the "com.df.redirectWhenHttpProto", the "proto" property is still there in order to use it inside the service (for ex: nginx)?

I just added it to all backend configs.

`http-request add-header X-Forwarded-Proto https if { ssl_fc }`

I made a beta release as `vfarcic/docker-flow-proxy:beta`. Can you please try it out and let me know if that's what you were looking for?

> I have create other services without this setting and seems that they are being redirected to https too. This makes sense?

That was not the intention of the change I made. Can you post proxy config and the commands you used to create services?

**Comment by ecentinela** [comment]
@vfarcic the beta version is working perfectly! thank you.

**Comment by rsalimian** [comment]
I'm having almost same issue. I have my own haproxy(with ssl termination) pointed to 3 nodes that are clustered in a swarm mode.

@vfarcic can you please also add 
`http-request set-header X-Forwarded-Port %[dst_port]`
to all backends. I guess this going to fix it.

**Comment by vfarcic** [comment]
@ecentinela Great. Closing the issue.

**Comment by vfarcic** [comment]
@rsalimian I closed this issue since the changes I pushed are fixing the original problem. 

A new release will be available in a few minutes. Can you please try it out and let me know whether it fixes your problem as well. If it doesn't, can you please open a new issue with a short description of your use case. That will help me track things easier.
