### ISSUE TITLE
Proxy Service based on incoming port

### ISSUE THREAD

**Issue by lhenry7** [vfarcic/docker-flow-proxy#137]
I'm trying to define services for the same domain/path, using multiple frontend/backend ports. So service,domain/path,port 80 and then either the same or a different service,domain/path,port 443. Currently the first one wins and the second is ignored. Can the acl's be made to include matching the dest_port to the service port? Here is the flow from client to AWS ELB, to DF-P to service:
outside -> [443 ELB -> 443 DF-P -> 443 Service] AND 
outside -> [80 ELB -> 80 DF-P -> 80 Service]
for the same domain/path
This way I can terminate SSL on ELB and keep cert out of HAProxy, but the service still knows the original port the request was sent on.

**Comment by vfarcic** [comment]
This feature is already developed (even though I forgot that it exists). You can use the `srcPort` with an index. You can see an example in https://proxy.dockerflow.com/swarm-mode-auto/#using-tcp-request-mode . Even though the example uses `tcp`, the same applies to `http` as well.

Can you please let me know if that's what you were looking for?

**Comment by lhenry7** [comment]
Here is what I've tried:
 - com.df.port.1=80
 - com.df.srcPort.1=80
 - com.df.port.2=443
 - com.df.srcPort.2=443

Also, just
 - com.df.srcPort.1=80
 - com.df.srcPort.2=443 

 and just:
 - com.df.port.1=80
 - com.df.port.2=443

In all cases, the proxy log repeats
2017/02/17 13:54:03 Processing request /v1/docker-flow-proxy/reconfigure?distribute=true&port.1=80&port.2=443&serviceDomain=...

for 4 mins and then stops, having not updated the config at all.

What I was able to do is define a service using
 - com.df.port=80
 - com.df.srcPort=80
and then a second service (using the same container) with
 - com.df.port=443
 - com.df.srcPort=443

and this will accomplish what I need, same container logic processing 2 different ports (across 2 different services though). I was wondering if this is what you had intended? Not suer I get how the port indexing is supposed to work.

P.S.
I don't mind so much doing this, as I might need to config this way to work around another problem: on ELB's I can support sticky session cookies to enforce using the same EC2 instance(service), where docker network mesh does not support sticky sessions. So this config allows me to run any service/port combination that can't be load-balanced as a separate service with a single replica, while running the same service on another port that can have multiple replicas.  

Now I've seen some talk of having HAProxy provide the sticky session part. Any thoughts on that with DF-P?

**Comment by vfarcic** [comment]
The idea behind indexing is to treat a single service as if there are multiple services or endpoints. They can provide a similar result as what you did with two services that use the same image.

The most likely problem with your attempt to use indexes is that you missed `servicePath`. Labels should be something like:

```
com.df.srcPort.1=80
com.df.srcPort.1=80
com.df.servicePath.1=/something
com.df.srcPort.2=443
com.df.srcPort.2=443
com.df.servicePath.2=/something
```

Can you please try it out with `servicePath` indexed as well? If that didn't work, please post logs from `swarm-listener`. There should be the response from the proxy that will, hopefully, give us a clue why it rejected reconfigure requests.

**Comment by lhenry7** [comment]
Perfect! Adding servicePath.1 and .2 did the trick (with srcPort and port   .1 and .2)
