### ISSUE TITLE
FQDN are not being resolved

### ISSUE THREAD

**Issue by aisamu** [vfarcic/docker-flow-proxy#140]
FQDN names (e.g. absolute domain names, ending in a dot) are not being forwarded by the proxy

* [www.example.com](www.example.com) (ok)
* [www.example.com.](www.example.com.) (503)

Is that the expected behavior?

**Comment by vfarcic** [comment]
FQDN is currently not supported directly. Normally, people/clients do not end domain with dot. However, I can add this feature if you think it would be useful.

**Comment by aisamu** [comment]
Oh, sure! They are mostly used by dns-centric tooling.

I only brought it up because adding the proxy made all my http health-checks go red. It’s a relatively common setup (AWS + Terraform), and I suppose other setups would benefit from it as well!

In any case, thanks again for the nice proxy!

**Comment by vfarcic** [comment]
I though that dot at the end would not work but it does (at least in the example I run).

I created hostname `proxytest.local` and executed the following commands:

```bash
docker network create --driver overlay proxy

curl -o docker-compose-stack.yml \
    https://raw.githubusercontent.com/\
vfarcic/docker-flow-proxy/master/docker-compose-stack.yml

docker stack deploy -c docker-compose-stack.yml proxy

curl -o docker-compose-go-demo.yml \
    https://raw.githubusercontent.com/\
vfarcic/go-demo/master/docker-compose-stack.yml

docker stack deploy -c docker-compose-go-demo.yml go-demo

docker stack ps go-demo

curl -i "localhost/demo/hello"

docker service update \
    --label-add com.df.serviceDomain=proxytest.local \
    go-demo_main

curl -i "http://proxytest.local./demo/hello"
```

I got response 200 from the last curl (it ends with dot). I'm probably missing something but I'm not sure what. Could you send a set of commands that I could use to reproduce the problem? At the same time, I could evaluate those commands and get back to you in case some of the arguments are wrong or missing.

**Comment by aisamu** [comment]
I've just tested it with `curl`, and it is indeed working! 

But only with `curl` :disappointed: 

`wget` and browsers[1] still get a `503`.

Could you verify if other tools also work on your setup? I tried to run your example locally but the go stack wouldn't come up, with the containers exiting after a go panic.

[1] (Linux FF, Linux Chrome, iOS Safari)

**Comment by vfarcic** [comment]
Current domain matching algorithm uses strict checking that looks for an exact domain match. The release [1.206](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.206) added the `serviceDomainMatchAll` parameter that will match any variation of a domain.

Can you please add `-l com.df.serviceDomainMatchAll=true` to the service and try it out?

**Comment by aisamu** [comment]
Worked nicely, thanks a lot!
