### ISSUE TITLE
flow-proxy doesn't retrieve conf from consul

### ISSUE THREAD

**Issue by jonlatorre** [vfarcic/docker-flow-proxy#141]
Hi,

I've an issue with docker-flow-proxy that I'm not able to track down. The scenario is as follows:

- 1 consul service
- 2 flow proxy, each with his SERVICE_NAME correctly set

The both proxys generates KV-s in consul when rencofigure commands are send. But when the service is updated (or container removed) the new flow-proxy doesn't retrieve the configuration from the KV. In the attachmments are the relevant parts of the scenario (proxy stack part, proxy env-s and information stored in the KV).

[service_stack.txt](https://github.com/vfarcic/docker-flow-proxy/files/789608/service_stack.txt)
[consul_1.txt](https://github.com/vfarcic/docker-flow-proxy/files/789610/consul_1.txt)
[consul_2.txt](https://github.com/vfarcic/docker-flow-proxy/files/789612/consul_2.txt)
[proxy_1_env.txt](https://github.com/vfarcic/docker-flow-proxy/files/789613/proxy_1_env.txt)
[proxy_2_env.txt](https://github.com/vfarcic/docker-flow-proxy/files/789614/proxy_2_env.txt)

What I'm missing? 

Thanks in andvance.

**Comment by vfarcic** [comment]
You're using Docker Swarm Mode (Docker v.12+)? If you're not, please discard the rest of this comment?

There is no reason to use Consul with Docker Swarm Mode (v1.12+). Consul was only a temporary solution for the old Swarm (standalone version before v1.12). Back then, Docker did not have service discovery. When 1.12 was released, I created [Docker Flow Swarm Listener](https://github.com/vfarcic/docker-flow-swarm-listener) that transmits Docker events (service creation and removal) to the proxy.

You can find an example stack in https://github.com/vfarcic/docker-flow-swarm-listener.

A detailed tutorial can be found in https://proxy.dockerflow.com/swarm-mode-auto/. A bit less detailed but with Docker stacks can be found in https://proxy.dockerflow.com/swarm-mode-stack/. 

Please let me know if Proxy with Swarm Listener is something you'd like to try. I strongly suggest that combination over Proxy with Consul (which, by the way, still does not support Swarm Mode). If you must (or want to) use Consul, I'll take a deeper look into your issue.

**Comment by jonlatorre** [comment]
Hi,

Thanks for the reply. I explained quite bad my scenario :) I have two sets of services that need to be accessed through two different docker-flow-proxys. As I understand from the documentation, there is no way of doing some kind of filtering in swarm-listener. If I run 2 different swarm-listeners pointing to two different flow-proxys all the services will be pushed to the two flow- proxy. I'm wrong? After all I suppose this could be OK. I'll give it a try.

Fortunately in the last day the project has make an not expected turn and possible we could use a single flow-proxy.

Thanks again for the great proyect, book and help!

By.
