### ISSUE TITLE
Remove Authentication Header when proxy is authenticating.

### ISSUE THREAD

**Issue by s4s0l** [vfarcic/docker-flow-proxy#143]
I don't think it will do harm to anyone if it was the default behavior. Also it kinda makes sense not to pass passwords downstream as they may be in clear text. 

I was looking how to work around this and it seems to be easier to fix it in DFP code than write reusable template for that (at least for me reproducing whats happening in getBackTemplateProtocol method as a template is quite challenging, btw why tis method is not a template). 

So if you find this idea reasonable I can prepare PR.

--------------
Long reason why i need it: I'm fighting with grafana, and i want proxy to terminate ssl and authenticate, so I enabled anonymous access in graphana. Then graphana is picking up Authentication header and tries to authenticate against it and fails if username/password are not in sync. If i disable basic authentiacation in grafana, /api endpoint stops working for internal access (without proxy). And I kinda need it. Its possible to overcome it with simulated Anonymous login but my http client is complaining that cookies are generated for  /grafana path and api is accessed through /api, and /grafana/api gives 404. This is because grafana has no ability to simply change its context path. It uses some hacks to support being behind proxy that has path != '/'. Sometimes I hate technology.

**Comment by vfarcic** [comment]
PR is more than welcome. Please make the PR and, if there's anything to be discussed, we can do it over code. The main preoccupation is that existing users do not get affected while, at the same time, we do not unnecessarily complicate the code. As a side note, I'm guilty of failing both of those rules quite a few times :(.

It would be great if the change is followed with tests. I'm practicing continuous deployment and every commit to the main branch is directly made into a release. If you're not sure whether anything will break, please make a PR to one of the branches.

P.S. Content of the getBackTemplateProtocol function was a template. With time, things got so complicated that Go templates could not handle it and I had to move it to code. What was one a combination of templates that describe whole proxy config, is now reduced only to the `global` section.

**Comment by s4s0l** [comment]
So i'll create PR but I must honestly warn you I have spend exactly 1 day in my life working with go, I'm confident in my coding skills but I'm not feeling the go tooling to well. Few questions before I begin:
* which branch to create PR against
* stupid novice question: how do you handle "local import in non local package"? I can compile and test everything with docker command from travis.yml but its hard to debug I think https://proxy.dockerflow.com/feedback-and-contribution/ is missing some step.

**Comment by vfarcic** [comment]
> which branch to create PR against

No need. You commits are great and you are not escaping from writing tests.

> stupid novice question...

I see from your commits that you already got on top of this :)

**Comment by vfarcic** [comment]
Closed with the release 1.203.
