### ISSUE TITLE
Ability to force a proxy instance to reconfigure itself

### ISSUE THREAD

**Issue by patrickleet** [vfarcic/docker-flow-proxy#144]
It would be useful to be able to tell a proxy instance to reconfigure itself if it happens to get out of sync.

In a cluster I'm running with scale=3, I noticed every 3rd request was returning a 503, which led me to realize that one of the three proxies did not have the same configuration as the other two.

As a solution, I scaled down, and back up. It would have been better to just tell the incorrect instance to apply the same start-up logic to configure itself again.

**Comment by n1b0r** [comment]
@patrickleet why don't you use the [/reconfigure](http://proxy.dockerflow.com/usage/#reconfigure) endpoint ?

**Comment by s4s0l** [comment]
I've seen it also. @n1b0r the problem is not how to reconfigure it but how to detect it is out of sync. Just comparing configs and reacting upon differences may do more harm than good.

**Comment by vfarcic** [comment]
The plan is to have two new parameters for the `reload` request.

* `recreate=[true|false]` would create config from scratch using information already available in the proxy.
* `requestFromSwarmListener=[true|false]` would request the data from DFSL. If set to true, config would be recreated no matter the value of the `recreate` param.


Any thoughts?

**Comment by vfarcic** [comment]
Added to the [release 1.205](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.205).

Can you please try it out and let me know whether it works as you expected.
