### ISSUE TITLE
Support for 'encrypted' passwords. 

### ISSUE THREAD

**Issue by s4s0l** [vfarcic/docker-flow-proxy#146]
currently USERS env and com.df.users requires opentext passwords. Maybe add [USERS_ENCRYPTED|com.df.usersEncrypted]=true|false with default value of true?

**Comment by vfarcic** [comment]
I think this issue can be closed with the [release 1.224](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.224). Can you confirm @s4s0l ?

**Comment by s4s0l** [comment]
Confirmed.
