### ISSUE TITLE
Load certs from secrets

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/docker-flow-proxy#148]
* The proxy should automatically load all certs stored as Docker secrets in `/run/secrets` directory.
* Since secrets hold other information as well, there should be a way to distinguish certs from other files. Since the list of possible certificate extensions is quite big and Docker tends store secrets by the name (not file name), the proxy shall consider that any file with a name that starts with `cert-` or `cert_` is a certificate (case insensitive).
* There should be a variable that can overwrite naming convention for certificates with a custom regex (e.g. `*.pem`).

Any comments or suggestions are welcome.

**Comment by n1b0r** [comment]
Will the action be triggered at reconfigure step ?
Can you provide an endpoint to trigger the reload of certs from secrets ? 

Other services could inject secrets to docker-flow-proxy, and then ask for a reload_cert.

**Comment by vfarcic** [comment]
Available in the [release 1.212](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.212).

All certificate files are reevaluated on every action that changes proxy config (e.g. reconfigure request). If a cert is added without one of the actions that will recreate the config, the [reload request](https://proxy.dockerflow.com/usage/#reload) with the `recreate` parameter can be used to reevaluate certificates.

Can you please try it out?
