### ISSUE TITLE
domain name with wildcard

### ISSUE THREAD

**Issue by mcctomsk** [vfarcic/docker-flow-proxy#155]
Hello. 
I've tried to run docker in swarm mode with docker-flow-proxy but I had small problem.
For example, I have two web services.
One of them uses domain data.foo.bar with option
--label "com.df.serviceDomain=data.foo.bar
Another one service must reply to all other requests for all other subdomains. So I tried to set for it this setting:
--label "com.df.serviceDomain=*.foo.bar
But when I start second service it gets all requests and for domain data.foo.bar too

For a stand alone nginx with conf file written manually it's work perfectly.

**Comment by vfarcic** [comment]
The proxy evaluates ACLs in alphabetic order. The proxy uses `aclName` to sort entries. If it is not set, it uses service name instead. So, if service name of the first example is after the service name of the second, `*.foo.bar` will catch both cases. You can fix that by adding `--label "com.df.aclName=xxx` to the service with domain `*.foo.bar`. It doesn't have to be `xxx`. As long as it is alphabetically lower than the name of other service, it will be placed after it. You can also choose to put `aclName` to all services (e.g. `10-service-1`, `20-service-2` but that would require more changes.

You can find short info about `aclName` in the [reconfigure](https://proxy.dockerflow.com/usage/#reconfigure) section of the documentation.

Please let me know if this tip fixes you problem. If it doesn't, we can look for a better solution.

**Comment by vfarcic** [comment]
Please let me know if the previous answer solved your problem and this ticket can be closed.

**Comment by mcctomsk** [comment]
Give me one more week please. I was very busy on other project. Early I tried at local environment, but now I have real domain name for testing. I'll necessarily report the results.

**Comment by mcctomsk** [comment]
It's working! Your project is awesome! I read this part of documentation and found out that you have special option for domain names with wildcard:
`  --label com.df.serviceDomainMatchAll=true \`
So, now I have event two sites with the same domain name with wildcard, but with different locations!
Site with root location I set to the end of list with aclName.
And few words about documentation. The part about how to add to http request header additional information not so clear.  The examples can be more informational or at least add quotes there. 
`  --label com.df.addHeader="X_FORWARDED_HOST %H" \`

**Comment by vfarcic** [comment]
Not long ago I changed the code so that a service with `servicePath=/` is put to the bottom automatically. You don't need `aclName` for that anymore.

I'll work on improving the documentation. Feel free to send a PR if you notice something you might be able to improve yourself. They are located in the `docs` directory.
