### ISSUE TITLE
SSL backend with self signed certificates

### ISSUE THREAD

**Issue by morph027** [vfarcic/docker-flow-proxy#163]
Just read through the whole docs again and only found SSL-2-SSL ;)

Is it possible to have a ssl backend (non-ssl frontend) with self signed certs?

HAProxy config will be something like:

```
my-backend
  server insecure-bastard insecure-bastard:443 ssl verify none
```

**Comment by vfarcic** [comment]
I can add an option for that. You can expect it in a day or two.

**Comment by morph027** [comment]
No hurry, was just a question ;)

But sure, it would be nice. Thank you!

**Comment by vfarcic** [comment]
My memory failed me. There is `sslVerifyNone` parameter that adds `ssl verify none` to the backend associated with the service. You'll find it in the [reconfigure](https://proxy.dockerflow.com/usage/#reconfigure) docs. Can you please try it and let me know how it went?

**Comment by morph027** [comment]
Oh, thanks. Will try tomorrow!

**Comment by morph027** [comment]
Works like it should, next time i should double check the docs after getting caffeinated :)
