### ISSUE TITLE
haproxy log

### ISSUE THREAD

**Issue by aaron0428** [vfarcic/docker-flow-proxy#167]
HI
  why docker-flow-proxy have not haproxy log??  thanks!!

**Comment by aaron0428** [comment]
HOW CAN I ADD THE haproxy log??

**Comment by vfarcic** [comment]
If the environment variable `DEBUG` is set to `true`, the proxy will log every request. You can find more info in the [Environment Variables](http://proxy.dockerflow.com/config/#environment-variables) and [Debug Format](http://proxy.dockerflow.com/config/#debug-format) sections of the documentation. The [Debugging Docker Flow Proxy](http://proxy.dockerflow.com/debugging/) is available as well.

Please note that the debug mode should be enabled only for testing and debugging purposes. Logging every request in production can have a negative impact on performance.

**Comment by vfarcic** [comment]
Please let me know if you have a suggestion how to improve debugging and whether this issue can be closed.

**Comment by Loyz07** [comment]
Hello vfaric,

You could implement debug level that allow to log only haproxy error (code 50x) and not all requests.

What do you think about that ?

**Comment by vfarcic** [comment]
This feature has been added to the [release 1.255](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.255).

Can you please try it out and let me know whether it matches your needs. Any suggestions for improvement are welcome.

**Comment by aaron0428** [comment]
I am sorry, because I am in China, I just received an e-mail, your URL address (http://proxy.dockerflow.com/haproxy.tmpl) can not open. Then, I still have a question, how to HAPROXY log output to the file, so that I can always view!

**Comment by vfarcic** [comment]
The logs are now sent to stdout and available through `docker container logs` or `docker service logs` commands (the latter only if Docker experimental features are enabled).

Are you sure you want logs to be available as a file instead of through Docker logs? That would be antipattern but it can be added.

As for http://proxy.dockerflow.com/haproxy.tmpl, that address was never available. Are you trying to see proxy config I use for that site or you wrote it by error? If you're looking for documentation, it is available from http://proxy.dockerflow.com. The [release notes](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.255) should give you more detailed links of the documentation related to logging.

**Comment by Loyz07** [comment]
For information, we will only use logs sent to console on our side.

Thanks.

Loïc Guéguen
06 59 51 08 83

**Comment by vfarcic** [comment]
@Loyz07 By console, do you mean stdout or something else?

**Comment by aaron0428** [comment]
Hello vfaric,
How can i add the logs to be available as a file instead of through Docker logs?
THS!!!

**Comment by vfarcic** [comment]
Logging from containers to a file is, especially in distributed system, an anti-pattern. You will probably run multiple replicas and different nodes. With time, some of those replicas will fail (or be updated) and Swarm will reschedule them on, potentially, different nodes.

I strongly suggest outputting debug logs only to stdout. If you need to store them somewhere (e.g. ElasticSearch, files, and so on), you should use one of the [Docker Logging Drivers](https://docs.docker.com/engine/admin/logging/overview/) or use [LogSpout](https://github.com/gliderlabs/logspout). That way you can decide how to treat logs and where to store them. An example would be to ship all the logs to LogStash and, from there, to ElasticSearch or, if that's what you're looking for, to a file.

As long as the logs are sent to stdout, you can leverage Docker features, plugins, and third-party tools to do with them whatever you want/need.

@aaron0428 Please let me know if this answers your question.

**Comment by Loyz07** [comment]
@vfarcic,

You're right i mean stdout.

Loïc Guéguen
06 59 51 08 83

Le 11 mars 2017 10:49 PM, "Viktor Farcic" <notifications@github.com> a
écrit :

**Comment by aaron0428** [comment]
@vfarcic,
thank you for your answer!
I use the Docker Logging Drivers to debug logs to json-file!

**Comment by vfarcic** [comment]
I'll close this issue since I think that all the questions were answered. Feel free to reopen if you disagree.
