### ISSUE TITLE
Dynamic Service Port

### ISSUE THREAD

**Issue by patran** [vfarcic/docker-flow-proxy#174]
I went through the documentation and not sure if it would be possible to let docker select the service port (-P) dynamically and randomly when using docker swarm mode.

client --https://abc.com --> haproxy --> abcServiceDockerContainer-1:33012
client --https://abc.com --> haproxy --> abcServiceDockerContainer-2:33012 
client --https://def.com --> haproxy --> defServiceDockerContainer-1:36022
client --https://def.com --> haproxy --> defServiceDockerContainer-2:37022

The idea is when we create the  abcServiceDockerContainer and defServiceDockerContainer services, we would let docker assign service ports (using -P). We don't want to manage the port mappings and would just have Docker pick the ports dynamically/randomly such as 33012, 36022, 37022, etc. Would that be possible?

From the internet in, customers can use different domains or URL to reach a given service -- always using the standard 80 or 443 ports.

**Comment by vfarcic** [comment]
Assuming that you are using Docker networking, there is no need to open any ports. If you take a look at the examples from http://proxy.dockerflow.com/swarm-mode-auto/ or http://proxy.dockerflow.com/swarm-mode-stack/, you'll notice that the *go-demo*  service that not open any ports.

As long as the proxy and a service belong to the same network, the proxy will find its way to forward requests. The only requirement is that the destination service has the proper service labels. One of those labels is the port the service is listening to inside a container.

Can you please join http://slack.devops20toolkit.com/ and ping me? I can walk you through the process.

**Comment by patran** [comment]
all good...thanks
