### ISSUE TITLE
Haproxy log

### ISSUE THREAD

**Issue by aaron0428** [vfarcic/docker-flow-proxy#175]
I am sorry, because I am in China, I just received an e-mail, your URL address (http://proxy.dockerflow.com/haproxy.tmpl) can not open. Then, I still have a question, how to HAPROXY log output to the file, so that I can always view in the docker-flow-proxy!

**Comment by vfarcic** [comment]
Closing this issue as a duplicate of https://github.com/vfarcic/docker-flow-proxy/issues/167. It contains the same comment.
