### ISSUE TITLE
Service Specific Customer Frontend and Backend Template

### ISSUE THREAD

**Issue by patran** [vfarcic/docker-flow-proxy#177]
It would be nice to be able to specify custom frontend and backend templates on a per service basis. Here are the additional headers I'd like to add for certain services. It would probably be a good idea to add them for all services, but not certain if that would mess up for someone

http-request set-header X-Forwarded-Port %[dst_port]
http-request add-header X-Forwarded-Proto https if { ssl_fc }
http-request add-header X-Forwarded-Protocol https if { ssl_fc }
http-request set-header X-Forwarded-Ssl on if { ssl_fc }
http-request add-header X-Url-Scheme https if { ssl_fc }

References:

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_headers

http://stackoverflow.com/questions/16042647/whats-the-de-facto-standard-for-a-reverse-proxy-to-tell-the-backend-ssl-is-used

**Comment by vfarcic** [comment]
Added `addHeader` and `setHeader` reconfigure parameters. They can be used to add or set additional headers before they get forwarded to a destination service.

More info can be found in [General HTTP Query Parameters](https://proxy.dockerflow.com/usage/#general-http-query-parameters).

New params are available from the [release 1.275](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.275).

Please let me know if this fits your needs.

**Comment by patran** [comment]
Works great. Thanks
