### ISSUE TITLE
Throw an error if no IPs are found when resending distribute request

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/docker-flow-proxy#178]
If the service hosting the proxy is not called `proxy` and the environment variable `SERVICE_NAME` is not set, proxy cannot resend distribute requests. This is expected behavior since the proxy doesn't know where to resend requests but it is confusing since there is no indication in logs that such a thing happened.

Under such circumstance, the proxy should log an error message "*No replicas of the `[SERVICE_NAME]` are found. Could not resend distribution requests. Please check that the name of the proxy is set as the environment variable `SERVICE_NAME`*".

**Comment by vfarcic** [comment]
@patran This should make the solution to the problem we worked on much easier to spot.

**Comment by patran** [comment]
I found another case where specifying the environment variable SERVICE_NAME is necessary. If the proxy is running a stack S1 and the service ABC is running as part of stack S2, then, ABC will need to set the SERVICE_NAME environment variable

**Comment by vfarcic** [comment]
@patran I'm not sure I understood your use case. If the name of the proxy service is `proxy`, it should not be necessary to specify the environment variable `SERVICE_NAME`. That should be required only if your proxy service is named differently and should not depend on stacks defined for other services that should be reconfigured in the proxy.

Would it be possible to put a set of commands that prove this behavior wrong? That would help me debug the problem and fix it.

**Comment by vfarcic** [comment]
The error message is available in the image vfarcic/docker-flow-proxy:1.265.

Please try it out and let me know whether it works as expected. Feel free to reopen this issue if you find a problem.

**Comment by patran** [comment]
I'll give it a spin and will retry me scenario.

**Comment by patran** [comment]
It works as you described it. There is no need for SERVICE_NAME for service ABC. Something else somewhere else was probably incorrect at the time and SERVICE_NAME was added as part of a set of other updates, conflating the root cause.
