### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by patran** [vfarcic/docker-flow-proxy#186]
The proxy can read STATS_USER and STATS_PASS from the secret dfp_stats_user and dfp_stats_pass. It would be nice if there was an easy way to specify different secret names.

Perhaps, introduce a STATUS_USER_ENV, STATUS_PASS_ENV and the value would be the secret value or the actual environment variables holding the user names and password

**Comment by vfarcic** [comment]
It's done and available in the [release 1.276](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.276).

Please try it out and let me know if it fits your needs.

**Comment by patran** [comment]
I could not get it to work. My end goal is to be able to use a custom secret name other than dfp_stats_user and dfp_stats_pass.

Nevertheless, I tried a few combos and still ended up with the default user/pass: admin/admin.

environment:
  STATS_USER_ENV=myuserenv
  myuserenv=abc
  dfp_myuserenv=abc

Also tried
environment:
  STATS_USER_ENV=myuserenv
  myuserenv=dfp_myuserenv
  dfp_myuser=dfp_myuserenv

And I created a secret called "dfp_myuserenv" and "myuserenv", the haproxy.cfg still lists the default use/pass admin;admin.

Since, dfp_stats_user is a secret covering STATS_USER, I figure if I set STATS_USER_ENV to myuserenv, the equivalent secret ought to be dfp_myuserenv. Maybe, I went to deep into the "how" in my feature request :)

Thx

**Comment by patran** [comment]
Hold a second. It would seem like the default "dummy" configuration will always be admin:admin. I am going to add a service to see if stats_user and stats_pass will be updated accordingly.

**Comment by patran** [comment]
Confirmed everything works as expected. The default "dummy" configuration will not get updated until there a service is deployed and has notified the proxy.

**Comment by vfarcic** [comment]
HAProxy cannot start without a valid configuration so I had to create a dummy one only to get it going. To be honest, I haven't put much thought into it thinking that it does not really matter what's inside a dummy config as long as it does not crash the proxy.
