### ISSUE TITLE
haproxy.cfg references non-existent secret

### ISSUE THREAD

**Issue by patran** [vfarcic/docker-flow-proxy#187]
docker secret add cert_blabla_pem
docker service update --secret-add service-node-1
haproxy.cfg is updated properly

docker service update --secret-rm cert_blabla_pem service-node-1
docker secret rm cert_blabla_pem
haproxy.cfg is updated mostly correct. haproxy still incorrectly refers to cert_blabla_pem (see excerpt). Since cert_blabla_pem is no longer available to proxy, haproxy.cfg must not reference it

frontend services
    bind *:80
    bind *:443 ssl crt /run/secrets/cert_blabla_pem

**Comment by vfarcic** [comment]
Let me start by apologising for not responding earlier. I could not get a free moment...

I executed the following set of commands. You'll see the result in comments I added.

```
docker secret create cert-mycert xip.io.pem

docker service update --secret-add cert-mycert proxy_proxy

ID=[...] # Get the ID of one of the proxy replicas and replace [...] with it

docker container exec -it ${ID} cat /cfg/haproxy.cfg # Cert is inside the config

docker container exec -it ${ID} ls -l /run/secrets # Cert is in the /run/secrets dir

docker service update --secret-rm cert-mycert proxy_proxy

ID=[...] # Get the ID of one of the proxy replicas and replace [...] with it

docker container exec -it ${ID} cat /cfg/haproxy.cfg # Cert is NOT inside the config

docker container exec -it ${ID} ls -l /run/secrets # Cert is NOT in the /run/secrets dir
```

My best guess is that you had multiple replicas of the proxy and, since Docker is doing rolling updates by default, you got info from one of the replicas that were still not updated. If that's not the case, maybe we can go through it together and debug the difference between my and your tests.

**Comment by vfarcic** [comment]
Please let me know if the previous comment helped and whether we can solve this issue.

**Comment by patran** [comment]
It is still not working, not updating haproxy.cfg to remove the reference to the secret.

1. start proxy (docker stack style with compose file) (1 replica on a manager node)
2. docker service update --secret-add cert_ssl_abc_com_pem proxy
3. start service abc_com 
3. haproxy.cfg is updated properly
4. All works fine
5. docker stack rm abc_com
6. haproxy.cfg is updated but still references the secret (see below)
7. docker service update --secret-rm cert_ssl_abc_com_pem proxy
8. haproxy.cfg remains unchanged, still referencing the secret (see below)


haproxy.cfg

frontend services
    bind *:80
    bind *:443 ssl crt /run/secrets/cert_ssl_abc_com_pem
    mode http


    acl url_dummy path_beg /dummy
    use_backend dummy-be if url_dummy

backend dummy-be
    server dummy 1.1.1.1:1111 check

**Comment by patran** [comment]
After step 8, the following showed up in the log, which makes sense.

[ALERT] 108/185928 (11) : parsing [/cfg/haproxy.cfg:49] : 'bind *:443' : unable to load SSL certificate file '/run/secrets/cert_ssl_abc_com_pem' file does not exist.
[ALERT] 108/185928 (11) : Error(s) found in configuration file : /cfg/haproxy.cfg
[ALERT] 108/185928 (11) : Proxy 'services': no SSL certificate specified for bind '*:443' at [/cfg/haproxy.cfg:49] (use 'crt').
[ALERT] 108/185928 (11) : Fatal errors found in configuration.
2017/04/19 18:59:28 Starting "Docker Flow: Proxy"
2017/04/19 18:59:33 Got configuration from http://dfs_reverse_proxy:8080.

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I was away (DockerCon) until today.

Looks like the secret was not removed from containers on step 8.

I just tried to recreate the problem and, in my case, it worked correctly. Can you confirm that the secret was removed in step 8 (e.g. `docker container exec -it [PROXY_CONTAINER_ID] ls -l /var/secrets`) and that the containers were rescheduled (e.g. check the status with `docker service ps proxy`).

Would you be open to a screen sharing session? I think we'd figure it out faster if I could look at your terminal. I'll be travelling tomorrow but today I'm mostly free.

**Comment by patran** [comment]
It is working in version: 1.308 (latest on docker hub). I think we can close this one.
