### ISSUE TITLE
[Security] Disable HAProxy statistics page if username/password is not explicitly set in the configuration

### ISSUE THREAD

**Issue by rommik** [vfarcic/docker-flow-proxy#189]
Currently, If STATS_USER and STATS_PASS are not set,  then, the HaProxy stats page username and password are defaulted to Admin and Admin. 
see https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/ha_proxy.go#L201 

This is a vulnerability because administrators can easily forget to overwrite these variables.

I recommend not to set them at all and disable stats page by default.

**Comment by vfarcic** [comment]
Starting from the [release 1.277](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.277), if the environment variables`STATS_USER` and `STATS_PASS` or Docker secrets `dfp_stats_user` and `dfp_stats_pass` are not set, statistics will not be available.

**Comment by je-al** [comment]
@vfarcic Is there a regression on this?, I'm testing with version 1.317 and it's not being honored.

**Comment by vfarcic** [comment]
@je-al I made a mistake by not merging the correct code so both the implementation and the code were missed. That was a big mistake from my part. The latest release should fix that. Can you please pull the latest release, try it out, and let me know if it works as expected?

**Comment by je-al** [comment]
@vfarcic yup, 1.326 seems fine.
