### ISSUE TITLE
Forward ssh traffic

### ISSUE THREAD

**Issue by n1b0r** [vfarcic/docker-flow-proxy#194]
I'm using gitlab-ce/gitlab docker image. 

One container handle everything (ssh, gitlab, prometheus, docker registry, ...).

For the moment I handle gitlab and docker registry with DFP using 2 serviceDomain, and forwarding 443 requests.

For ssh connexion I am currently publishing port 10022:22.

There should be a way to also use port 443 to redirect ssh traffic to port 22 of gitlab service.

**Comment by morsik** [comment]
If you setup your own SSH on different port then answer is: "yes".

Currently Docker Swarm does not allow binding on specific IP, so you need to use differrent port for regular traffic.

**Comment by vfarcic** [comment]
A port can only listen to one protocol (e.g. HTTP, HTTPS, TCP, and so on). Also, TCP (SSH is TCP) does not have headers so a proxy cannot use things like domain and path to forward traffic to one service or another.

If you'd use `443` for SSH traffic, you would not be able to do HTTPS on that port. The result would be, more or less, the same as when you published `10022`.

Please let me know if that answers your question or you'd like us to explore this a bit further.

**Comment by vfarcic** [comment]
Closing the issue due to inactivity. Please post a comment if you'd like me to reopen it and continue the discussion.
