### ISSUE TITLE
DFP doesn't get the right information from Consul

### ISSUE THREAD

**Issue by slapic** [vfarcic/docker-flow-proxy#195]
`
Consul has the data: `curl http://$(docker-machine ip swarm-1):8500/v1/kv/docker-flow?recurse
[{“LockIndex”:0,“Key”:“docker-flow/go-demo/color”,“Flags”:0,“Value”:null,“CreateIndex”:43,“ModifyIndex”:60},{“LockIndex”:0,“Key”:“docker-flow/go-demo/consultemplatebepath”,“Flags”:0,“Value”:null,“CreateIndex”:37,“ModifyIndex”:59},{“LockIndex”:0,“Key”:“docker-flow/go-demo/consultemplatefepath”,“Flags”:0,“Value”:null,“CreateIndex”:36,“ModifyIndex”:58},{“LockIndex”:0,“Key”:“docker-flow/go-demo/domain”,“Flags”:0,“Value”:null,“CreateIndex”:41,“ModifyIndex”:62},{“LockIndex”:0,“Key”:“docker-flow/go-demo/hostname”,“Flags”:0,“Value”:null,“CreateIndex”:38,“ModifyIndex”:63},{“LockIndex”:0,“Key”:“docker-flow/go-demo/path”,“Flags”:0,“Value”:“L2RlbW8=“,”CreateIndex”:42,“ModifyIndex”:61},{“LockIndex”:0,“Key”:“docker-flow/go-demo/pathtype”,“Flags”:0,“Value”:“cGF0aF9iZWc=“,”CreateIndex”:39,“ModifyIndex”:56},{“LockIndex”:0,“Key”:“docker-flow/go-demo/port”,“Flags”:0,“Value”:“ODA4MA==“,”CreateIndex”:35,“ModifyIndex”:55},{“LockIndex”:0,“Key”:“docker-flow/go-demo/skipcheck”,“Flags”:0,“Value”:“ZmFsc2U=“,”CreateIndex”:40,“ModifyIndex”:57},{“LockIndex”:0,“Key”:“docker-flow/service/go-demo”,“Flags”:0,“Value”:“c3dhcm0=“,”CreateIndex”:34,“ModifyIndex”:54}]`
`

`
logs from proxy.2:

[11:44]  
2017/04/03 10:37:08 Starting HAProxy
2017/04/03 10:37:08 Configuring existing services
2017/04/03 10:37:08     Found 1 services
2017/04/03 10:37:08 Reloading the proxy
2017/04/03 10:37:08 Starting “Docker Flow: Proxy”
2017/04/03 10:37:39 Could not reach the service go-demo. Is the service running and connected to the same network as the proxy?
2017/04/03 10:37:44 Could not reach the service go-demo. Is the service running and connected to the same network as the proxy?
2017/04/03 10:37:52 Sending distribution request to http://10.0.0.3:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=8080&serviceName=go-demo&servicePath=%2Fdemo
2017/04/03 10:37:52 Could not reach the service go-demo. Is the service running and connected to the same network as the proxy?
2017/04/03 10:37:52 Sending distribution request to http://10.0.0.5:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=8080&serviceName=go-demo&servicePath=%2Fdemo
2017/04/03 10:37:52 Sending distribution request to http://10.0.0.4:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=8080&serviceName=go-demo&servicePath=%2Fdemo
2017/04/03 10:38:06 Could not reach the service go-demo. Is the service running and connected to the same network as the proxy?
2017/04/03 10:38:41 Could not reach the service go-demo. Is the service running and connected to the same network as the proxy?
2017/04/03 10:39:57 Sending distribution request to http://10.0.0.3:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=8080&serviceName=go-demo&servicePath=%2Fdemo
2017/04/03 10:39:57 Creating configuration for the service go-demo
2017/04/03 10:39:57 Reloading the proxy
2017/04/03 10:39:57 Sending distribution request to http://10.0.0.4:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=8080&serviceName=go-demo&servicePath=%2Fdemo
2017/04/03 10:39:57 Sending distribution request to http://10.0.0.5:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=8080&serviceName=go-demo&servicePath=%2Fdemo

[11:44]  
than scaled to 6 proxies, logs from 4 (same for 5 and 6):

[11:44]  
2017/04/03 10:41:17 Starting HAProxy
2017/04/03 10:41:17 Configuring existing services
2017/04/03 10:41:17     Found 1 services
2017/04/03 10:41:17 Reloading the proxy
2017/04/03 10:41:17 Starting “Docker Flow: Proxy”

[11:45]  
but 4/5/6 has the default config:

[11:45]  
frontend services
   bind *:80
   bind *:443
   mode http

   acl url_dummy path_beg /dummy
   use_backend dummy-be if url_dummy

backend dummy-be
   server dummy 1.1.1.1:1111 check
`

It looks for me that DFP doesn’t read the (right) information from Consul

**Comment by vfarcic** [comment]
I went through the code and there seem to be some breaking changes in Consul. It's time to sunset it. It was added before Docker 1.12 and baked in service discovery. It does not serve a purpose anymore.

**Comment by vfarcic** [comment]
Are you referring to the tutorials from http://proxy.dockerflow.com/? If that's the case, please take a look at http://proxy.dockerflow.com/swarm-mode-auto/ and http://proxy.dockerflow.com/swarm-mode-stack/.

**Comment by vfarcic** [comment]
@slapic Please let me know if the previous comment resolved your question and whether this issue can be closed.
