### ISSUE TITLE
Default Backend Dummy-BE IP and Port

### ISSUE THREAD

**Issue by sven-carstens-udg** [vfarcic/docker-flow-proxy#196]
Hi,

is there a chance to disable the "backend dummy-be" or configure it with a different/saner IP?

It swamps our firewall with connection attempts to 1.1.1.1:1111 (0.5 million per month).

CU Sven

**Comment by vfarcic** [comment]
HAProxy cannot start without at least one backend so a "dummy" config is required until the first service is created. Do you have a suggestion of what would be a good "dummy" IP/port? Do you think that it should be configurable as a parameter?

**Comment by sven-carstens-udg** [comment]
Maybe 127.0.0.1 is a better solution as it will keep the pakets in the localhost and won't swamp the outbound firewalls with unwanted traffic.

**Comment by vfarcic** [comment]
It's done and available as vfarcic/docker-flow-proxy:1.299.

**Comment by sven-carstens-udg** [comment]
Thanks a lot. Now everything is quiet (firewall related).
