### ISSUE TITLE
Feature: per-backend http-keep-alive

### ISSUE THREAD

**Issue by morsik** [vfarcic/docker-flow-proxy#198]
Please make `http-keep-alive` configurable per backend, not only globally.

For example, if there's already `CONNECTION_MODE=http-keep-alive` envvar to set that, make `com.df.connectionMode=http-keep-alive` to keep options consistent.

**Comment by st3sch** [comment]
That would be great.

**Comment by vfarcic** [comment]
I could not find time to do it today. Since I'll be offline for a week starting this weekend, I'm afraid to make any change to the project and, potentially, cause problems while I'm not available. I'll work on this start from the week after next.

**Comment by vfarcic** [comment]
Available in the release [1.310](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.310). Can you please try it out and let me know it went?

**Comment by st3sch** [comment]
It is working for me, thank you very much.
