### ISSUE TITLE
 Could not read the /var/run/haproxy.pid file --- /var/run/haproxy.pid: no such file or directory

### ISSUE THREAD

**Issue by patran** [vfarcic/docker-flow-proxy#201]
Started and stopped services (docker stack swarm mode) and noticed the following errors a few time. I will see if I can narrow down the steps to reproduce, but not certain I will be able to do that. 

vfarcic/docker-flow-proxy:1.299
docker_stack_docker_flow_swarm_listener_image_tag: vfarcic/docker-flow-swarm-listener:1.32

Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 8
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ifn9omdpb9d0vl8ki4ay9jhdi
 Is Manager: true
 ClusterID: xgmaicj0u7nfa4chlvkpul0w6
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.10
 Manager Addresses:
  192.168.1.10:2377
  192.168.1.11:2377
  192.168.1.12:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.81 GiB
Name: aulac-1-0
ID: IANG:AAAV:VMKY:LED7:DZVV:Z3HO:FIPC:CW2A:4GB7:OACF:MKM7:F6I6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

2017/04/10 01:59:04 Sending distribution request to http://10.0.0.8:8080/v1/docker-flow-proxy/reconfigure?addHeader=X-Forwarded-Ssl+on+if+%7B+ssl_fc+%7D%2C+X-Forwarded-Proto+https+if+%7B+ssl_fc+%7D%2C+X-Forwarded-Protocol+https+if+%7B+ssl_fc+%7D%2C+X-Url-Scheme+https+if+%7B+ssl_fc+%7D&distribute=false&port=8081&serviceDomain=artifactory.abcdef.uite.com&serviceName=rg_dz_prod_artifactory_artifactory&servicePath=%2F&setHeader=X-Forwarded-Port+%25%5Bdst_port%5D%2C+X-Artifactory-Override-Base-Url+https%3A%2F%2Fartifactory.abcdef.uite.com%2Fartifactory
2017/04/10 01:59:04 Creating configuration for the service rg_dz_prod_artifactory_artifactory
2017/04/10 01:59:04 Reloading the proxy
2017/04/10 01:59:04 Could not read the /var/run/haproxy.pid file
open /var/run/haproxy.pid: no such file or directory
2017/04/10 01:59:04 Could not read the /var/run/haproxy.pid file
open /var/run/haproxy.pid: no such file or directory

**Comment by patran** [comment]
compose file for the registry


version: '3.1'

networks:
  qwerty_reverse_proxy:
    external: true

volumes:
  dfp_reverse_proxy_cfg:
  dfp_reverse_proxy_errorfiles:

secrets:
  dfp_qwerty_dfp_reverse_proxy_stats_user:
    external: true
  dfp_qwerty_dfp_reverse_proxy_stats_pass:
    external: true

services:

  ################################################################################
  # Docker Flow Swarm Listener
  ################################################################################

  dfs_reverse_proxy:
    image: "vfarcic/docker-flow-swarm-listener:1.32"
    networks:
      qwerty_reverse_proxy:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "0.000"
          memory: "1024m"
        reservations:
          cpus: "0.000"

          memory: "512m"
      mode: "replicated"
      replicas: 1
      update_config:
        parallelism: 1
        delay: "30s"

      placement:
        constraints:
          - node.role == manager
          - node.labels.qwerty_dfs_reverse_proxy == yes
    environment:
#      - DF_RETRY=400
#      - DF_RETRY_INTERVAL=5
      - DF_NOTIFY_CREATE_SERVICE_URL=http://dfp_reverse_proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://dfp_reverse_proxy:8080/v1/docker-flow-proxy/remove

  ################################################################################
  # Docker Flow Proxy
  ################################################################################

  dfp_reverse_proxy:
    image: "vfarcic/docker-flow-proxy:1.299"
    ports:
      - '443:443'
    networks:
      qwerty_reverse_proxy:
    volumes:
      - dfp_reverse_proxy_cfg:/cfg
      - dfp_reverse_proxy_errorfiles:/errorfiles
    secrets:
      - dfp_qwerty_dfp_reverse_proxy_stats_user
      - dfp_qwerty_dfp_reverse_proxy_stats_pass
    deploy:
      resources:
        limits:
          cpus: "0.000"
          memory: "1536m"
        reservations:
          cpus: "0.000"
          memory: "1024m"

      mode: "replicated"
      replicas: 1
      update_config:
        parallelism: 1
        delay: "60s"

      placement:
        constraints:
          - node.role == manager
          - node.labels.qwerty_dfp_reverse_proxy == yes
    environment:
      - MODE=swarm
      - LISTENER_ADDRESS=dfs_reverse_proxy
      - SERVICE_NAME=dfp_reverse_proxy
      - STATS_USER_ENV=qwerty_dfp_reverse_proxy_stats_user
      - STATS_PASS_ENV=qwerty_dfp_reverse_proxy_stats_pass

**Comment by s4s0l** [comment]
Do you by any chance have a full log? Or remember if there was a chance of multiple reload events in same time? And maybe most important: was there any problem with proxy apart from suspicious logs?

**Comment by patran** [comment]
Perhaps due to too many http headers -- not sure if "BAD INDEX" is blowing the max size of an array of http headers.

1. Started proxy
2. Started a service A
3. Started gitlab service (the one in the log below)
4. The log is from the active haproxy service instance. The other ones exited when gitlab service was started.


docker logs rg_ogh_prod_dfp_reverse_proxy.1.u3z16pj5b26t6xs4mj0x2ye1d
2017/04/10 05:36:29 Starting HAProxy
2017/04/10 05:36:29 Starting "Docker Flow: Proxy"
2017/04/10 05:36:31 Sending distribution request to http://10.0.0.10:8080/v1/docker-flow-proxy/reconfigure?addHeader=X-Forwarded-Ssl+on+if+%7B+ssl_fc+%7D%2C+X-Forwarded-Proto+https+if+%7B+ssl_fc+%7D%2C+X-Forwarded-Protocol+https+if+%7B+ssl_fc+%7D%2C+X-Url-Scheme+https+if+%7B+ssl_fc+%7D&distribute=false&port=80&serviceDomain=gitlab.dvorak.qwerty.com&serviceName=ab_dc_prod_gitlab_gitlab&servicePath=%2F&setHeader=X-Forwarded-Port+%25%5Bdst_port%5D
2017/04/10 05:36:31 Creating configuration for the service ab_dc_prod_gitlab_gitlab
2017/04/10 05:36:31 Reloading the proxy
[ALERT] 099/053631 (15) : parsing [/cfg/haproxy.cfg:66] : 'server ab_dc_prod_gitlab_gitlab' : could not resolve address 'ab_dc_prod_gitlab_gitlab'.
[ALERT] 099/053631 (15) : Failed to initialize server(s) addr.
2017/04/10 05:36:31 Command haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 12

exit status 1
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    #disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-server-close
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s

    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats auth oghstatsadmin:oghstats123qwe
    stats uri /admin?stats

frontend services
    bind *:80
    bind *:443 ssl crt /run/secrets/cert_ssl_artifactory_dvorak_qwerty_com_pem crt /run/secrets/cert_ssl_gitlab_dvorak_qwerty_com_pem
    mode http

    acl url_ab_dc_prod_gitlab_gitlab80 path_beg /
    acl domain_ab_dc_prod_gitlab_gitlab hdr(host) -i gitlab.dvorak.qwerty.com
    use_backend ab_dc_prod_gitlab_gitlab-be80 if url_ab_dc_prod_gitlab_gitlab80 domain_ab_dc_prod_gitlab_gitlab




backend ab_dc_prod_gitlab_gitlab-be80
    mode http
    http-request add-header X-Forwarded-Ssl on if { ssl_fc }
    http-request add-header  X-Forwarded-Proto https if { ssl_fc }
    http-request add-header  X-Forwarded-Protocol https if { ssl_fc }
    http-request add-header  X-Url-Scheme https if { ssl_fc }
    http-request set-header X-Forwarded-Port %!
(BADINDEX)    server ab_dc_prod_gitlab_gitlab ab_dc_prod_gitlab_gitlab:80
2017/04/10 05:36:31 Command haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 12

exit status 1
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    #disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-server-close
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s

    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats auth oghstatsadmin:oghstats123qwe
    stats uri /admin?stats

frontend services
    bind *:80
    bind *:443 ssl crt /run/secrets/cert_ssl_artifactory_dvorak_qwerty_com_pem crt /run/secrets/cert_ssl_gitlab_dvorak_qwerty_com_pem
    mode http

    acl url_ab_dc_prod_gitlab_gitlab80 path_beg /
    acl domain_ab_dc_prod_gitlab_gitlab hdr(host) -i gitlab.dvorak.qwerty.com
    use_backend ab_dc_prod_gitlab_gitlab-be80 if url_ab_dc_prod_gitlab_gitlab80 domain_ab_dc_prod_gitlab_gitlab




backend ab_dc_prod_gitlab_gitlab-be80
    mode http
    http-request add-header X-Forwarded-Ssl on if { ssl_fc }
    http-request add-header  X-Forwarded-Proto https if { ssl_fc }
    http-request add-header  X-Forwarded-Protocol https if { ssl_fc }
    http-request add-header  X-Url-Scheme https if { ssl_fc }
    http-request set-header X-Forwarded-Port %!
(BADINDEX)    server ab_dc_prod_gitlab_gitlab ab_dc_prod_gitlab_gitlab:80
2017/04/10 05:36:34 Got configuration from http://dfs_reverse_proxy:8080.
2017/04/10 05:36:34 Creating configuration for the service ab_dc_prod_gitlab_gitlab
2017/04/10 05:36:34 Creating configuration for the service ab_dc_prod_artifactory_artifactory
2017/04/10 05:36:34 Reloading the proxy
[ALERT] 099/053634 (16) : parsing [/cfg/haproxy.cfg:82] : 'server ab_dc_prod_gitlab_gitlab' : could not resolve address 'ab_dc_prod_gitlab_gitlab'.
[ALERT] 099/053634 (16) : Failed to initialize server(s) addr.
2017/04/10 05:36:34 Command haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 12

exit status 1
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    #disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3

**Comment by patran** [comment]
Ok, so there seems to be 2 cases:

1. The original case: proxy stopped working. The service instances were still working but the proxy would not proxy requests.

2. The 2nd case: the log marked as "2nd case", the proxy was till working, serving requests just fine.

**Comment by patran** [comment]
Continuing the scenario:

Started proxy
Started a service A (artifactory)
Started gitlab service (the one in the log below) (seeing BADINDEX)
proxy still works
Shutdown gitlab
Restarted gitlab

Seeing BADINDEX in haproxy.cfg (see logs) below.
Proxy stopped working and started to work again after gitlab has fully started
gitlab can take a very long time to start, so this may have put the proxy in some bad pending state, only to recover after gitlab has fully started...maybe...?!?

backend ab_dc_prod_artifactory_artifactory-be8081
    mode http
    http-request add-header X-Forwarded-Ssl on if { ssl_fc }
    http-request add-header  X-Forwarded-Proto https if { ssl_fc }
    http-request add-header  X-Forwarded-Protocol https if { ssl_fc }
    http-request add-header  X-Url-Scheme https if { ssl_fc }
    http-request set-header X-Forwarded-Port %!
(BADINDEX)    http-request set-header  X-Artifactory-Override-Base-Url https://artifactory.qwerty.dvorak.com/artifactory
    server ab_dc_prod_artifactory_artifactory ab_dc_prod_artifactory_artifactory:8081


backend ab_dc_prod_gitlab_gitlab-be80
    mode http
    http-request add-header X-Forwarded-Ssl on if { ssl_fc }
    http-request add-header  X-Forwarded-Proto https if { ssl_fc }
    http-request add-header  X-Forwarded-Protocol https if { ssl_fc }
    http-request add-header  X-Url-Scheme https if { ssl_fc }
    http-request set-header X-Forwarded-Port %!
(BADINDEX)    server ab_dc_prod_gitlab_gitlab ab_dc_prod_gitlab_gitlab:80
2017/04/10 05:56:39 Sending distribution request to http://10.0.0.10:8080/v1/docker-flow-proxy/reconfigure?addHeader=X-Forwarded-Ssl+on+if+%7B+ssl_fc+%7D%2C+X-Forwarded-Proto+https+if+%7B+ssl_fc+%7D%2C+X-Forwarded-Protocol+https+if+%7B+ssl_fc+%7D%2C+X-Url-Scheme+https+if+%7B+ssl_fc+%7D&distribute=false&port=80&serviceDomain=gitlab.qwerty.dvorak.com&serviceName=ab_dc_prod_gitlab_gitlab&servicePath=%2F&setHeader=X-Forwarded-Port+%25%5Bdst_port%5D
2017/04/10 05:56:39 Creating configuration for the service ab_dc_prod_gitlab_gitlab
2017/04/10 05:56:39 Reloading the proxy

**Comment by patran** [comment]
Ok, I can confirm that if a service is taking a long time (3-4 or more minutes), proxy will not work meanwhile. Scenario is described below:

Start proxy
Start service A (artifactory)
Start gitlab
Confirm everything works
Shutdown gitlab
Proxy still serving Artifactory
Restart gitlab

During the time it takes for gitlab to start (becoming healthy) servicing requests, proxy does not serve requests to artifactory. proxy hung and simply stopped working for all intent and purposes.
After gitlab has fully started (became healthy as per docker ps), proxy started to serve requests to both artifactory and gitlab again

**Comment by s4s0l** [comment]
you may be right, haproxy has this nasty behavior of crushing when dns address in config is not resolvable:/ Could you try setting environment variable SKIP_ADDRESS_VALIDATION=false in proxy? It may help.

**Comment by patran** [comment]
Fantastic. That works.

**Comment by vfarcic** [comment]
Since a few releases ago, the environment variable `SKIP_ADDRESS_VALIDATION` is set to `true` by default.

@patran I was away for a while and am still not on top of all the issues. Can you please let me know if this one is solved?

**Comment by patran** [comment]
@vfarcic, yes, setting it to false worked out well for this situation.
