### ISSUE TITLE
Wrong haproxy configuration when container tcp port is different from the published in proxy

### ISSUE THREAD

**Issue by marceloaguero** [vfarcic/docker-flow-proxy#203]
Suppose I want to run the example detailed in "Using TCP Request Mode" in the docs (http://proxy.dockerflow.com/swarm-mode-auto/#using-tcp-request-mode)

But port 6379 is already taken. I want to publish port 6380 in the proxy instead of 6379. 

So, once docker-flow-swarm-listener and docker-flow-proxy are running, I did:

`docker service update --publish-add 6380:6380 proxy`

```
docker service create --name redis \
    --network proxy \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.port=6379 \
    --label com.df.srcPort=6380 \
    --label com.df.reqMode=tcp \
    redis:3.2
```

The haproxy config generated was:

```
...
frontend services
    bind *:80
    bind *:443
    mode http

frontend tcpFE_6380
    bind *:6380
    mode tcp
    default_backend redis-be6380

backend redis-be6379
    mode tcp
    server redis redis:6379
```

There is an error in the redis backend naming. As you can see, names don't match. Perhaps I'm doing something wrong.

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I was offline most of the last two weeks.

This is (probably) but in the proxy. I'll do my best to fix it this Monday (if not before). I hope that's not too late.

**Comment by vfarcic** [comment]
Actually, it was simpler than I thought. A quick fix is committed and available in the latest release. I did it while waiting to board a plane so I didn't have time to test it properly. Can you please try it out and let me know if you experienced any problems?
