### ISSUE TITLE
Reading Docker stats without authentication

### ISSUE THREAD

**Issue by valuecourse** [vfarcic/docker-flow-proxy#205]
I am also introducing metricbeat from ELK and would like to read metrics of DockerFLow HAProxy. However, HAProxy module of metricbeat seems not to have username/password to authenticate to DockerFlow proxy stats interface.
Can you please add having statistics without authentication requirement?

**Comment by vfarcic** [comment]
It's done and available from the [release 1.314](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.314).
