### ISSUE TITLE
Multiple proxies in one consul cluster trample on each other's configuration

### ISSUE THREAD

**Issue by tazle** [vfarcic/docker-flow-proxy#21]
When multiple proxies use a single consul cluster to persist configuration, they all are configured to proxy all the services in the cluster upon restart. For example, if proxy A is supposed to proxy services X and Y, and proxy B is supposed to proxy service Z, and both A and B (and X, Y and Z) use the same consul cluster, both proxies A and B will discover all three services from consul upon restart.

The root cause is that the proxy configuration in consul is stored in a shared location (under /docker-flow).

One way to resolve this would be to name each proxy instance, and use that name as part of the key structure in consul. For example, configurations from the proxies would be stored under /docker-flow/A and /docker-flow/B, so there would be /docker-flow/A/X, /docker-flow/A/Y and /docker-flow/B/Z in consul.

The name could be set via environment variables passed to the container, I guess.

**Comment by vfarcic** [comment]
The PROXY_INSTANCE_NAME environment variable has been added to the release 1.0.2.

Can you please try it out and let me know if it fits your use case? Please reopen this ticket in case it doesn't work as expected.
