### ISSUE TITLE
support for multiple rows with EXTRA_FRONTEND & EXTRA_GLOBAL

### ISSUE THREAD

**Issue by leostarcevic** [vfarcic/docker-flow-proxy#216]
I'd like to be able to use multiple values in EXTRA_FRONTEND 
just like addHeader can handle multiple values separated with (,)

What do you think? 👍 or 👎

**Comment by leostarcevic** [comment]
also EXTRA_GLOBAL would benefit from multiple row support.

**Comment by vfarcic** [comment]
At the moment, multiple rows are added as multiple lines (separated with `\n`). For example:

```
line1\nline2\nline3
```

The problem with changing `\n` with `,` is that config snippets might require commas. If every comma is replaced with a new line, the result might be not what's expected. That would mean that when a user wants a new line it would be a comma and when comma is needed it would need to be escaped (e.g. `\,`). I'm not sure that using comma instead new lines would provide enough benefit.

I'm not rejecting this PR. It's, at this moment, only a brainstorming. What do you think? Is there a special reason for not using `\n`?

**Comment by leostarcevic** [comment]
hmm, I tried that a couple of days ago and didn't get it to work, let med try again...
If it works there is no need to add ```,```.

**Comment by vfarcic** [comment]
I reopened the issue in case it doesn't work. 

I'll close it if it works. If it doesn't, please post the command you used to create the proxy service and the haproxy.cfg file and I'll fix it.

**Comment by leostarcevic** [comment]
I tried now by adding this to an existing (working) proxy.yaml 
```- EXTRA_FRONTEND=option http-buffer-request\ncapture request header Referrer len 64\ncapture request header Content-Length len 10\ncapture request header Host len 32\ncapture request header User-Agent len 64\ncapture request header X-Unique-ID len 64\ndeclare capture request len 40000\nhttp-request capture req.body id 0 ```

Here is the result in /cfg/haproxy.cfg
```frontend services
    bind *:80
    bind *:443
    mode http
option http-buffer-request\ncapture request header Referrer len 64\ncapture request header Content-Length len 10\ncapture request header Host len 32\ncapture request header User-Agent len 64\ncapture request header X-Unique-ID len 64\ndeclare capture request len 40000\nhttp-request capture req.body id 0
```
Also my other service is not showing up in haproxy stats after adding this extra_frontend, it seems like haproxy can't reload with the new config?

**Comment by vfarcic** [comment]
Sorry for that. My bad... Can you revert to what you had before and I'll work on a fix ASAP.

**Comment by leostarcevic** [comment]
No problem, I'm still running a custom haproxy.cfg.
hopefully soon I won't need to, when we can set everything with env/labels :)

**Comment by vfarcic** [comment]
It's finished. Lines can now be separated with comma (*,*). Can you please pull the latest release (1.319) and let me know if it works as expected?

**Comment by leostarcevic** [comment]
I can confirm that it works, thanks!
