### ISSUE TITLE
Changing ssl-default-* settings with env params?

### ISSUE THREAD

**Issue by leostarcevic** [vfarcic/docker-flow-proxy#219]
Wouldn't it be nice to configure ssl-default-* settings via env params?
Currently we are using our own haproxy.cfg to set a different cipher.

**Comment by vfarcic** [comment]
It's available in the [release 1.316](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.316). Can you please try it out and let me know if it works as expected.
