### ISSUE TITLE
Multiple services in one proxy produce invalid configuration

### ISSUE THREAD

**Issue by tazle** [vfarcic/docker-flow-proxy#22]
When multiple services are configured in one proxy, the following configuration is produced (global and defaults omitted):

    frontend sercice-1-fe
            bind *:80
            bind *:443
            option http-server-close
            acl url_service-1 path_reg ^/api/v0/.*service-1-identifier.*
            use_backend service-1-be if url_service-1

    backend service-1-be

            server host-1_0_32773 1.2.3.4:32773 check

    frontend service-2-fe
            bind *:80
            bind *:443
            option http-server-close
            acl url_service-2 path_reg ^/api/((v0/.*service-2-1.*)|(v0/service-2-2.*))
            use_backend service-2-be if url_service-2

    backend service-2-be

            server host-2_0_32782 1.2.3.5:32782 check

The configuration is wrong because haproxy will round-robin between service-1-fe and service-2-fe for all requests to ports 80 and 443. The acls are only considered after frontend has only been selected. Thus every other request to e.g. /api/v0/service-1-identifier/foo will fail with 503 when it happens to hit service-2-fe, fails the acl check and is left with no backend.

A correct configuration could be:

    frontend sercice-1-fe
            bind *:80
            bind *:443
            option http-server-close
            acl url_service-1 path_reg ^/api/v0/.*service-1-identifier.*
            acl url_service-2 path_reg ^/api/((v0/.*service-2-1.*)|(v0/service-2-2.*))
            use_backend service-1-be if url_service-1
            use_backend service-2-be if url_service-2

    backend service-1-be

            server host-1_0_32773 1.2.3.174:32773 check

    backend service-2-be

            server host-2_0_32782 1.2.3.130:32782 check

but even this way care must be taken to ensure that the path regexps supplied are disjoint, that is no URL matches multiple regexps.

**Comment by vfarcic** [comment]
Fixed in release 1.0.1
