### ISSUE TITLE
haproxy.tmpl doesn't set a default_backend 

### ISSUE THREAD

**Issue by leostarcevic** [vfarcic/docker-flow-proxy#220]
Possible issue when haproxy.cfg doesn't specify a default_backend in the frontend section?

Example:
We run two services:
Service 1 
serviceDomain: web.example.com

Service 2 
serviceDomain: api.example.com

We add both subdomains to our DNS and everything works fine.
Imagine then that Service 1 is removed/dies. "web.example.com" will be removed from haproxy. 
By visiting web.example.com at that moment we got the response from the service running at "api.example.com". I then looked at the cfg/haproxy.cfg and it seemed like the last acl rule in the config would work for any subdomain we had in our dns.

I looked at our old haproxy config (where this wasn't happening) and the only difference I saw was that we used default_backend to redirect all traffic that wouldn't match any specified acl rules. 

This might not be expected behavior for DFP users? What do you think?
Maybe a service label to make one of the service's the default_backend would be good?

**Comment by vfarcic** [comment]
I probably missunderstood it but... In the scenario you described, only `api.example.com` would show results. The other one that was removed (`web.example.com`) would return status code not found.

**Comment by leostarcevic** [comment]
I've updated the description, hope it makes more sense now...

**Comment by vfarcic** [comment]
Having a default (catch all) backend is a good idea. Would you like to give it a try with a PR?

**Comment by leostarcevic** [comment]
Yes 👍  I'll probably add it tomorrow!
