### ISSUE TITLE
proxy  service getting 503 

### ISSUE THREAD

**Issue by chengoldbond1** [vfarcic/docker-flow-proxy#221]
configure one of the services only with that 2 com.df labels and without servicePath or mode=tcp :
--label com.df.notify=true \
--label com.df.distribute=true \
make the proxy service result  "503" for every call made to the system.
only after deleting the service the proxy service keeps working good.

**Comment by vfarcic** [comment]
The fix is finished. I would appreciate if you could pull the latest release and repeat the same steps and check whether the `503` status disappeared.
