### ISSUE TITLE
Docker registry in swarm behind docker-flow-proxy on non-default port (5000)

### ISSUE THREAD

**Issue by mborejdo** [vfarcic/docker-flow-proxy#223]
as discussed in Slack and following up https://github.com/vfarcic/docker-flow-proxy/issues/107 I tried running a docker-registry behind dfp, but without specifying port 5000 (resulting in nicer docker-image names)

Trying different kinds of configurations (using label-notation in compose files) of port, srcPort, mode, sslPort, etc I was not successful. Currently I unfortunately cannot provide more logs or info.
Requesting registry.local(:443) resulted in time-outs and default dfp-errorpages

**Comment by mborejdo** [comment]
Using sslVerifyNone=true seems to solve the problem for me for now. I have valid certificates though.

**Comment by vfarcic** [comment]
Would you mind making a PR to https://github.com/vfarcic/docker-flow-stacks with the stack and short instructions in the README.md? Both should be added to the `docker` directory.
