### ISSUE TITLE
HAProxy does not start if can't resolve DNS of one of services

### ISSUE THREAD

**Issue by morsik** [vfarcic/docker-flow-proxy#224]
HAProxy fails with:

```
[ALERT] 118/170701 (14) : parsing [/cfg/haproxy.cfg:109] : 'server letsencrypt-companion' : could not resolve address 'letsencrypt-companion'.
[ALERT] 118/170701 (14) : Failed to initialize server(s) addr.
```

It's possible to omit this behaviour by using `init-addr` since HAProxy 1.7. Docs: https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#init-addr

Since this allows multiple values (as docs says), best option should be `last,none` so HAProxy will use previously known value (which can mostly work if you reload only proxy but not services), and do not try to resolve address when address is not known yet and it prevent failing HAProxy.

Of couse, best is to have it configurable, like:

`INIT_ADDR` env var for global configuration, and `com.df.initAddr` for per-service configuration.

**Comment by vfarcic** [comment]
Test failed...

**Comment by vfarcic** [comment]
Results (so far):

`default-server init-addr last,libc,none` in the `defaults` section works.
`init-addr none` next to a backend server doesn't.

**Comment by morsik** [comment]
Well… docs says it only works in `default-server`, so looks like we both missed this ;)
