### ISSUE TITLE
SNI routing broken for multi-port service

### ISSUE THREAD

**Issue by faisyl** [vfarcic/docker-flow-proxy#231]
When using SNI routed  service with multiple exposed ports, the front-end code is rendered multiple times. Also, the ACL names generated for each SNI match is duplicate. This breaks the haproxy configuration. 

Have a patch ready.

**Comment by vfarcic** [comment]
@faisyl How's the patch going?

**Comment by faisyl** [comment]
Need to add one testcase to verify the fix and I can send a PR. Do I create a PR against master?

**Comment by vfarcic** [comment]
If you add a test, PR against master is OK. It would be even better if you could add a test to integration_test_swarm.go. If not, I can add one if you could tell me the steps.

**Comment by faisyl** [comment]
I'll try and wrap up the unit tests and send you the PR. What information do you need for adding integration tests? Also in that case, I can send you a PR against a new branch so you can add integration steps and then merge back to trunk. The SNI routing is working quite nicely for me and I think it should be documented better. Please let me know what I can do to help.

**Comment by vfarcic** [comment]
If you can send me commands you would use to test the feature manually, I can easily translate them to integration tests. Making a PR against a branch is safe and, as you said, allows me to add tests before merging with the master.

I really appreciate your help with the project.

**Comment by faisyl** [comment]
Can you please create a branch for me to send the PR. I'll also send you an email about how I use it right now with example compose yml files and resulting configurations to create the integration tests.

**Comment by vfarcic** [comment]
Done :). New branch `sni` was created. There was one from quite some time before so I removed it.

Please let me know if you need anything else.

**Comment by vfarcic** [comment]
Closed with the PR #252
