### ISSUE TITLE
Enable GZIP compression

### ISSUE THREAD

**Issue by jleuleu** [vfarcic/docker-flow-proxy#232]
Is it possible to enable HTTP compression (similarly to GZIP_COMPRESSION_TYPE of dockercloud-haproxy)?
The idea would be to add something like the following in the HAproxy configuration:
```
 compression algo gzip
 compression type text/css text/html text/javascript application/javascript text/plain text/xml application/json
```

**Comment by vfarcic** [comment]
Available in the [release 1.368](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.368).

**Comment by vfarcic** [comment]
Can you please try it out and let me know if everything works as expected.

**Comment by jleuleu** [comment]
Thank you. It works as expected with env variables COMPRESSION_ALGO and COMPRESSION_TYPE.
