### ISSUE TITLE
Add possibility to configure response parameters via rspadd directive 

### ISSUE THREAD

**Issue by mcctomsk** [vfarcic/docker-flow-proxy#236]
As result haproxy.cfg will be able to contain parameters look like this:
```
rspadd Strict-Transport-Security:\ max-age=31536000;
rspadd X-Frame-Options:\ DENY
rspadd X-XSS-Protection:\ 1;\ mode=block
rspadd X-Content-Type-Options:\ nosniff
```

**Comment by vfarcic** [comment]
I think it would be better to add the option to use `http-response  add-header` instead `rspadd`. Prior was added in HAproxy 1.5 and has additional functionality and flexibility. There would be a new reconfigure parameter `addResponseHeader` which would contain a comma-separated list of values. If would add the `http-response add-header` to the backend that belongs to the service. On top of that, I would add an environment variable called `ADD_RESPONSE_HEADER` that would be added to all frontends. It would be useful in cases when a set of response header should be added to all services.

What do you think? Should we proceed with that idea?

**Comment by V1ct0rV** [comment]
Hi,

would be great to have the possibility to add header to the request, for example, I need to add the current authenticated user (when basic authentication is enabled) to do I need to add a request header `http-request set-header X-Username %[http_auth_group(GROUP_NAME)]`

**Comment by vfarcic** [comment]
@V1ct0rV There is already that option in form of `addReqHeader`, `addResHeader`, `delReqHeader`, `delResHeader`, `setReqHeader`, and `setResHeader` parameters.

@mcctomsk Is there a special reason why above mentioned parameters are not good for your use case and you'd like to add `rspadd` instead `http-response`? From HAProxy documentation: "*sing "rspadd"/"rspdel"/"rsprep" to manipulate request headers is discouraged
in newer versions (>= 1.5).*". It's possible that DFP implementation of `http-response` is not correct. If that's the case, I'd prefer we fix it instead adding another instruction. Can you provide more info?

**Comment by mcctomsk** [comment]
Finally I made test environment to test it. I've tried to use both parameters and addResHeader setResHeader but DFP doesn't work with my options. I don't know why but when I add  for example `com.df.addResHeader: "X-XSS-Protection\ 1;\ mode=block;"` parameter to my service in log of proxy container I see next:

> (BADINDEX)    http-request set-path %!

In attached file yaml files to repeat this.
[test.zip](https://github.com/vfarcic/docker-flow-proxy/files/1044795/test.zip)

**Comment by vfarcic** [comment]
Can you please change the `com.df.addResHeader` label to:

```
com.df.addResHeader: 'X-XSS-Protection "1; mode=block"'
```

The major difference is that I put the value of the `X-XSS-Protection` header under quotes so that HAProxy treats it all as a single value.

Can you please try it out and let me know if it worked?

**Comment by mcctomsk** [comment]
With this parameters `com.df.addResHeader: 'X-XSS-Protection "1; mode=block",X-Frame-Options "DENY",X-Content-Type-Options "nosniff"` it's works! 
> curl -v ...
> ...
> < X-XSS-Protection: 1; mode=block
> < X-Frame-Options: DENY
> < X-Content-Type-Options: nosniff

But I have no idea how to pass another one parameter in yaml file to get in a browser this response header:
> Content-Security-Policy: script-src 'self';

**Comment by vfarcic** [comment]
I think (but didn't try it myself) that it should be:

```
Content-Security-Policy "script-src 'self'"
```

The whole label could be:

```
com.df.addResHeader: 'X-XSS-Protection "1; mode=block",X-Frame-Options "DENY",X-Content-Type-Options "nosniff", Content-Security-Policy "script-src self"'
```

The point is to use double quotes when value of a header has more than one word. I'm not sure whether it's mandatory (from browser perspective) to have `self` inside quotes. If it is, I'll get back to you with the modified syntax.

**Comment by mcctomsk** [comment]
Yes, in this case it works, but header has next view:
> < Content-Security-Policy: script-src self

In same time this document https://www.w3.org/TR/2012/CR-CSP-20121115/  contains a mention about quotation marks:
 > 4. If the source expression is a case insensitive match for 'self' (including the quotation marks), then return does match if the URI has the same scheme, host, and port as the protected resource's URI (using the default port for the appropriate scheme if either or both URIs are missing ports).

As variant in yaml file I should write &#39; and you convert it into ' in haproxy.cfg

**Comment by vfarcic** [comment]
Can you check whether this label works? If it doesn't, can you please paste proxy config?

```
com.df.addResHeader: "X-XSS-Protection \"1; mode=block\",X-Frame-Options \"DENY\",X-Content-Type-Options \"nosniff\", Content-Security-Policy \"script-src 'self'\""
```

Using & # 39; should work I well. I think that it will be converted to '  automatically and that there's no reason to modify the code. Can you please try it with & # 39; (no spaces)?

**Comment by mcctomsk** [comment]
& # 39; doesn't work
> < Content-Security-Policy: script-src & # 39;self & #39;;

but 

`com.df.addResHeader: "X-XSS-Protection \"1; mode=block\",X-Frame-Options \"DENY\",X-Content-Type-Options \"nosniff\", Content-Security-Policy \"script-src 'self'\""
`
it works!

**This is what the doctor ordered! Thank you very much!**
