### ISSUE TITLE
Exclude some url's from basic authentication.

### ISSUE THREAD

**Issue by V1ct0rV** [vfarcic/docker-flow-proxy#242]
Hi, I have a service with basic auth and configures to use a domain: 

```
com.df.serviceDomain=sitebuilderqa.vmaxcompass.com
com.df.servicePath=/
com.df.users=admin:password
```

There is a way to exclude some urls from basic auth in the same service?, for example I need the urls `/foo*` and  `/bar/*` in the same service to be excluded from basic authentication.

**Comment by vfarcic** [comment]
I can add `users` param to be indexable. In that case, your labels could be:

```
com.df.serviceDomain=sitebuilderqa.vmaxcompass.com
com.df.servicePath.1=/foo
com.df.servicePath.2=/bar
com.df.users.1=admin:password
com.df.servicePath.3=/
com.df.users.3=admin:password
```

That way there would be three possible paths. Since they are evaluated sequentially, the proxy would first look for `foo`, then `bar`, and finally for `/`. Since `foo` and `bar` do not have authentication, they would be excluded from it.

Do you think that something like that would work for you?

**Comment by V1ct0rV** [comment]
Sure, would be great!

**Comment by vfarcic** [comment]
The plan changed a bit from the original idea. I added the `ignoreAuthorization` parameter.

The labels you could use could be:

```
...
com.df.serviceDomain=sitebuilderqa.vmaxcompass.com
com.df.users=admin:password
com.df.servicePath.1=/foo
com.df.ignoreAuthorization.1=true
com.df.servicePath.2=/bar
com.df.ignoreAuthorization.2=true
com.df.servicePath.3=/
...
```

The result would be that any request with the path that starts with `/foo` or `/bar` would not require authorization. Anything else would.

Please let me know if that fits your use case. If it does, please pull the [release 1.393](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.393), try it out, and let me know whether it works as expected. If it doesn't, please reopen the issue.
