### ISSUE TITLE
Add configuration for Basic Authentication

### ISSUE THREAD

**Issue by chrispolley** [vfarcic/docker-flow-proxy#244]
Some services deployed on docker do not have authentication built in, but instead expose controls or operating information insecurely via a built-in http server.  It would be nice to be able to use DFP to control access to these services.

Would it be possible to add the ability for DFP to specify that Basic Authentication be performed at the HAProxy layer?  

This would require specifying a named userlist at the global level, and adding to the haproxy.cfg file: (a) a named userlist directive, (b) a named ACL that refers to the named userlist, and (c) a "http-request auth" directive in the backend for the client service that refers to the named ACL .  

Possibly the label "com.df.auth=userlist-name" would trigger the inclusion of the applicable acl and http-request auth directives in the service backend, and the userlist itself could be loaded similarly to how certs are managed: either in a folder [creating a new image or mounting a volume], by HTTP PUT to the DFP api, or as a docker secret. 

See HAProxy Manual sections [3.4](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#3.4) and [7.3.6](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#7.3.6-http_auth);  and this [example](https://serverfault.com/questions/239749/possible-to-add-basic-http-access-authentication-via-haproxy) on serverfault.

Thanks!

**Comment by vfarcic** [comment]
Can you please take a look at the parameters `users`, `usersSecret`, and `usersPassEncrypted` from the [HTTP Mode HTTP Query Parameters](http://proxy.dockerflow.com/usage/#http-mode-http-query-parameters) section of the documentation. Those params are applied per-service. There are also environment variables that provide authentication that is applied to all services.

Also, please take a look at [Basic Authentication](http://proxy.dockerflow.com/swarm-mode-auto/#basic-authentication) section of the [Running Docker Flow Proxy In Swarm Mode With Automatic Reconfiguration](http://proxy.dockerflow.com/swarm-mode-auto/).

I think that those resources cover your use case. Please let me know if they don't or if you have a suggestion for improvements.

**Comment by chrispolley** [comment]
Yes, that's exactly it. Sorry, I should have RTFM before posting!

On an unrelated note, can servicePath and serviceDomain be used together?

**Comment by vfarcic** [comment]
No worries. The documentation is constantly growing and it's often not so easy to find what you're looking for.

As for `servicePath` and `serviceDomain` question, the answer is yes. You can combine both.

**Comment by patrickleet** [comment]
Pretty sure the “tutorial” section covers that too
