### ISSUE TITLE
Rewrite URL with an empty value

### ISSUE THREAD

**Issue by eonicle** [vfarcic/docker-flow-proxy#251]
Hello! 
I have a bunch of services behind proxy which I want to acess via base URL, e.g. **example.com/store** will point to my store service, but it only accepts requests without **/store** part (e.g. /api/v1). Basicly what I am trying to do is to transform **example.com/store** to **/** for service. I have already tried reqPathSearch and reqPathReplace:
`com.df.reqPathSearch: /store/`
`com.df.reqPathReplace: /`
It works for URL's like example.com/store/blabla, but obviously breaks on **/store**. Using 
`com.df.reqPathSearch: /store`
`com.df.reqPathReplace: /`
leaves me with double slash. I recon that I need kinda replace **/store** with nothing (just cut it off), but `reqPathReplace` does not let me leave it empty. Is there any workaround or possible solution? I've done it previously with nginx pretty easily, but would like to use this awesome project instead. Thanks in advance!

**Comment by vfarcic** [comment]
You're right. `reqPathReplice` should not be mandatory and could result in an empty string. I hope to have the fix tomorrow.

**Comment by vfarcic** [comment]
I made a change that should allow you to leave `reqPathReplace` empty or skip it altogether. However, I am about to board a plane so I could not test it properly. Can you please help me out and test whether it works as expected? You can, for example, set `com.df.reqPathSearch: /store` and skip the other label.

**Comment by vfarcic** [comment]
One more note... It's not yet available. It'll be released in 5 minutes.

**Comment by vfarcic** [comment]
That's strange...

I wrote a test with that scenario. If you take a look at https://github.com/vfarcic/docker-flow-proxy/blob/master/integration_tests/integration_swarm_test.go#L257 you'll see that the expression is `xxx|/something/`. Later on I send a request https://github.com/vfarcic/docker-flow-proxy/blob/master/integration_tests/integration_swarm_test.go#L289 . It proves that `|` acts as **or**.

Would it be possible to get your app for additional testing?

**Comment by vfarcic** [comment]
Closing the issue due to inactivity. Please reopen it if you'd like us to continue discussing the issue and if you can provide help replicating it.
