### ISSUE TITLE
Timed-out/refused connections on long-running proxy instances under docker swarm mode

### ISSUE THREAD

**Issue by aisamu** [vfarcic/docker-flow-proxy#253]
We're having some issues with docker-flow inside a docker swarm mode, but I can't really pinpoint the underlying cause nor reproduce it on demand. Per your instructions on the slack channel, I'm bringing the discussion here!

Occasionally, some machines start refusing/timing-out connections to port 80. Restarting the proxy service sometimes fixes everything, sometimes it fixes some and breaks others, sometimes nothing changes. Removing and re-creating the service has the same effect. The role of the machines doesn't seem to matter, nor is it a machine-specific issue: every machine has shown this behavior at some point.

### Swarm setup
5 EC2 t2.small machines running swarm mode - (3 managers + 2 workers) - using 1 (one) docker-proxy container as the http proxy. 
Everything is configured as per the tutorial:

#### Listener
```
docker service create --name swarm-listener \
    --network proxy \
    --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
    -e DF_NOTIF_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure \
    -e DF_NOTIF_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove \
    --constraint 'node.role==manager' \
    vfarcic/docker-flow-swarm-listener
```

#### Proxy
```
docker service create \
       --name proxy \
       -p 8080:8080 -p 80:80 -p 443:443 \
       --network proxy \
       -e MODE=swarm \
       -e LISTENER_ADDRESS=swarm-listener \
       -e STATS_USER=haproxyuser \
       -e STATS_PASS=haproxypass \
       vfarcic/docker-flow-proxy:1.384
```

Here's what we've already tried:

### Testing setup
There's a python SimpleHTTPServer configured with docker-proxy-flow to test.domain.com on port 8080.
```
docker service create \
  --name pythonhttp \
  --network proxy \
  --mount type=bind,src=/path/to/files,dst=/var/www \
  --label com.df.notify=true \
  --label com.df.distribute=true \
  --label com.df.serviceDomain=test.domain.com \
  --label com.df.servicePath=/ \
  --label com.df.port=8080 \
trinitronx/python-simplehttpserver
```

There's another identical python http server, with the addition of port 8888:8080 exposed directly on the swarm.

```
docker service create \
  --name pythonhttp2 \
  --network proxy -p 8888:8080 \
  --mount type=bind,src=/path/to/files,dst=/var/www \
  --label com.df.notify=true \
  --label com.df.distribute=true \
  --label com.df.serviceDomain=test2.domain.com \
  --label com.df.servicePath=/ \
  --label com.df.port=8080 \
trinitronx/python-simplehttpserver
```

Port 80 and 8888 are exposed on the EC2 VPC inbound rules.

### Tests
**working-machine-ip** is any of the working machines.
**non-working-machine-ip** is any of the non-working machines.

curl -H "Host: test.domain.com" **working-machine-ip**      ==> :small_blue_diamond: OK. Web page
curl -H "Host: test.domain.com" **working-machine-ip**:80   ==> :small_blue_diamond: OK. Web page
curl -H "Host: test.domain.com" **working-machine-ip**:81   ==> :small_red_triangle_down: No. Timeout
curl -H "Host: test.domain.com" **working-machine-ip**:8888 ==> :small_blue_diamond: OK. Web page

curl -H "Host: test.domain.com" **non-working-machine-ip**      ==> :small_red_triangle_down: No. Timeout/Refused
curl -H "Host: test.domain.com" **non-working-machine-ip**:80   ==> :small_red_triangle_down: No. Timeout/Refused
curl -H "Host: test.domain.com" **non-working-machine-ip**:81   ==> :small_red_triangle_down: No. Timeout
curl -H "Host: test.domain.com" **non-working-machine-ip**:8888 ==> :small_blue_diamond: OK. Web page

(The same behavior is observed with "Host: test2.domain.com")

When we try to connect to an unopened (in VPC) port (such as the 81 in the example), we always get a *"timeout"*. Port 80 gets either *"refused"* or *"timeout"*.
This means we have a working TCP connection and that the proxy service is working at least partially, since connecting through the other hosts works properly.

```
curl non-working-machine-ip:8888 ==> Gives web page
```
This shows that the **non-working-machine** is correctly receiving connections on ports exposed by services in the swarm, as expected.

### Inside `proxy` container

From inside the proxy container, everything seems to be working:

```
/ # >$ docker ps 
...
6b85c1d6a1bf vfarcic/docker-flow-proxy "/docker-entrypoin..." 80/tcp, 443/tcp, 8080/tcp   proxy.1.tvxdgkgl7vdmk
...

$> docker exec -it 6b8 sh
/ # apk add --update curl

```

#### Docker DNS sanity-check
```
/ # ping pythonhttp
PING pythonhttp (192.168.1.16): 56 data bytes
64 bytes from 192.168.1.16: seq=0 ttl=64 time=0.043 ms

/ # ping pythonhttp2
PING pythonhttp2 (192.168.1.35): 56 data bytes
64 bytes from 192.168.1.35: seq=0 ttl=64 time=0.039 ms

/ # ping pythonhttp3
ping: bad address 'pythonhttp3'
(Expected, there's no pythonhttp3)
```

#### Regular curl tests

Calling the service directly with curl:

/ # curl -v pythonhttp      ==> :small_red_triangle_down: No. Refused (expected, since it tries port 80)
/ # curl -v pythonhttp:8080 ==> :small_blue_diamond: OK. Web page

/ # curl -v pythonhttp2      ==> :small_red_triangle_down: No. Refused (see above)
/ # curl -v pythonhttp2:8080 ==> :small_blue_diamond: OK. Web page

Calling the container directly gives the same results:

```
>$ docker inspect 09a
...
        "Name": "/pythonhttp2.1.t4v847ogocaqk2wntup01xtou",
...
        "Labels": {
                 ...
                "com.docker.swarm.service.name": "pythonhttp2",
...
     "NetworkSettings": {
            ...
            "Networks": {
                ...
                "proxy": {
                    ...
                    "IPAddress": "192.168.1.26",
```

/ # curl -v 192.168.1.26      ==> :small_red_triangle_down: No. Refused (see above)
/ # curl -v 192.168.1.26:8080 ==> :small_blue_diamond: OK. Web page

This shows that the proxy container has complete access to the services being routed. 

### Misc
I've also checked the iptables, netstat of every machine and they are identical.
The only interesting findind is a lot of dangling "veth" links on some of the machines (both working and non-working).

Do you have any suggestions or pointers as to what else should I investigate?

**Comment by vfarcic** [comment]
Can you install `drill`inside the proxy container (e.g. `apk add --update drill`) and execute:

```bash
drill pythonhttp

drill tasks. pythonhttp

drill pythonhttp2

drill tasks. pythonhttp2
```

**Comment by aisamu** [comment]
Unfortunately, I've just rebooted a couple of machines, so it'll probably take a while for the issue to reappear. Here are the current results:

```
/ # drill pythonhttp
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 65096
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; pythonhttp.	IN	A

;; ANSWER SECTION:
pythonhttp.	600	IN	A	192.168.1.16

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Thu Jun  1 12:18:06 2017
;; MSG SIZE  rcvd: 54
```

```
/ # drill tasks. pythonhttp
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 45037
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; pythonhttp.	IN	A

;; ANSWER SECTION:
pythonhttp.	600	IN	A	192.168.1.16

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Thu Jun  1 12:26:55 2017
;; MSG SIZE  rcvd: 54
```

```
/ # drill pythonhttp2
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 18422
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; pythonhttp2.	IN	A

;; ANSWER SECTION:
pythonhttp2.	600	IN	A	192.168.1.35

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Thu Jun  1 12:27:35 2017
;; MSG SIZE  rcvd: 56
```
```
/ # drill tasks. pythonhttp2
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 44195
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; pythonhttp2.	IN	A

;; ANSWER SECTION:
pythonhttp2.	600	IN	A	192.168.1.35

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Thu Jun  1 12:28:02 2017
;; MSG SIZE  rcvd: 56
```

As soon as the issues reappear I'll re-run the `drill` commands and post it here.
In any case, thank you!

**Comment by vfarcic** [comment]
Let's hope it won't reappear :)

**Comment by vfarcic** [comment]
I'll close the issue. Feel free to reopen it if the problem reappears.
