### ISSUE TITLE
Reload config failed, ssl string very long

### ISSUE THREAD

**Issue by luongphamit** [vfarcic/docker-flow-proxy#254]
Hi @vfarcic,

My system has a lot of domains, resulting in very long ssl sequences

Ex: cat haproxy.cfg >> bind *:443 ssl crt /certs/abc.com.pem crt /certs/xyz.com.pem .....(>50 domain)

That is why the proxy does not reload the configuration. I think you can replace it with crt-list
https://www.haproxy.com/doc/aloha/7.0/haproxy/tls.html

Thank you,
PVL

**Comment by vfarcic** [comment]
I never tried it with such a long list of certs. `crt-list` sounds like a good idea. I think that I can have it done the beginning of the next week. The major obstracle is testing. If you'd be willing to test it, I should be able to have it done this Friday.

**Comment by vfarcic** [comment]
I did the change and pushed it as a temporary release. Can you please use vfarcic/docker-flow-proxy:issue254 image and let me know if you experience any problems. I'll wait for your confirmation before making the official release.

**Comment by luongphamit** [comment]
Hello @vfarcic,
Thank you for your enthusiasm and hard working
I will test the image you provided and will confirm it for you today.

**Comment by luongphamit** [comment]
Hello @vfarcic,

I have tested the image you provided vfarcic / docker-flow-proxy: issue254, when the number of domains on hundreds of proxies is still running fine.
The problem has been fixed
Thank you for your effort

**Comment by vfarcic** [comment]
Great! Code is merged to the main branch and will be available in the release 1.405.
