### ISSUE TITLE
 [Feature request] Support suffix for serviceDomain

### ISSUE THREAD

**Issue by preinking** [vfarcic/docker-flow-proxy#256]
As a docker service I would like to be able to use multiple domain names e.g. service1.example.com and service2.example.com.

For this I would like to request support for an index as a suffix to serviceDomain similar to servicePath
Use case would be for Nexus where you would use nexus.example.com and registry.example.com or www.example.com and api,example.com served from within the same docker service.

**Comment by vfarcic** [comment]
This is a bit more complex than I thought. I hope to have it finished by the end of next week. I hope that's not too late for you.

**Comment by dave08** [comment]
+1

**Comment by vfarcic** [comment]
I could not make the change (yet). I hope to have it done by the end of next week (unless someone would like to try to do a PR).

**Comment by zener79** [comment]
+1

I really need this feature because servicePath is mandatory unless serviceDomain is specified, even in  a "multiple destinations for a single service" environment.
In my use case I need to route using the serviceDomain, so I'm stucked on this.

**Comment by vfarcic** [comment]
I'll do my best to work on it during the weekend. I'm sorry for not finishing it earlier but the amount of requests is huge and not much help is coming in form of PRs.

**Comment by vfarcic** [comment]
Available in the release [1.415](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.415).

I tried it through automated tests (mostly unit) but did not have time to try it manually with a service that would benefit from this feature (e.g. Nexus). Can you please give it a try and let me know if it works as expected.

**Comment by zener79** [comment]
Actually it does not seems to work for me. Please, tell me how can I help to debug the problem. What informations do you need?

**Comment by preinking** [comment]
Its working for me as well  and below a small piece of the configuration and the generated haproxy config 

version: '3.1'

networks:

  default:
    external: false

  proxy:
    external: true

services:

  nexus:
    image: sonatype/nexus3
    networks:
      - proxy
    volumes:
      - /registry/nexus-data:/nexus-data
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomainMatchAll=true
        - com.df.xForwardedProto=true
        - com.df.serviceDomain.1=nexus.example.com
        - com.df.servicePath.1=/
        - com.df.port.1=8081
        - com.df.srcPort.1=443
        - com.df.serviceDomain.2=registry.example.com
        - com.df.servicePath.2=/
        - com.df.port.2=18443
        - com.df.srcPort.2=8123
        - com.df.serviceDomain.3=registry.example.com
        - com.df.servicePath.3=/
        - com.df.port.3=18444
        - com.df.srcPort.3=8124
      placement:
        constraints: [node.role == worker]



frontend services
    bind *:80
    bind *:443 ssl crt-list /cfg/crt-list.txt
    mode http

    bind *:8123 ssl crt /run/secrets/cert-asterix-lan-dtg-nl.pem
    bind *:8124 ssl crt /run/secrets/cert-asterix-lan-dtg-nl.pem

    acl url_jenkins_jenkins8080 path_beg /
    acl domain_jenkins_jenkins8080 hdr(host) -i jenkins.example.com
    use_backend jenkins_jenkins-be8080 if url_jenkins_jenkins8080 domain_jenkins_jenkins8080
    acl url_nexus_nexus8081 path_beg /
    acl srcPort_nexus_nexus443 dst_port 443
    acl domain_nexus_nexus8081 hdr_dom(host) -i nexus.example.com
    acl url_nexus_nexus18443 path_beg /
    acl srcPort_nexus_nexus8123 dst_port 8123
    acl domain_nexus_nexus18443 hdr_dom(host) -i registry.example.com
    acl url_nexus_nexus18444 path_beg /
    acl srcPort_nexus_nexus8124 dst_port 8124
    acl domain_nexus_nexus18444 hdr_dom(host) -i registry.example.com
    use_backend nexus_nexus-be8081 if url_nexus_nexus8081 domain_nexus_nexus8081 srcPort_nexus_nexus443
    use_backend nexus_nexus-be18443 if url_nexus_nexus18443 domain_nexus_nexus18443 srcPort_nexus_nexus8123
    use_backend nexus_nexus-be18444 if url_nexus_nexus18444 domain_nexus_nexus18444 srcPort_nexus_nexus8124
