### ISSUE TITLE
Docker stack and reqMode=tcp

### ISSUE THREAD

**Issue by gilleslabs** [vfarcic/docker-flow-proxy#257]
Hi,

I'm currently running a Swarm Cluster where I've deployed docker-flow-proxy using below docker stack:

==========
version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
      - 6379:6379
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - DEBUG=true
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.zone == dmz]

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    driver: overlay
=============

What I'd like to achieve is to be able to launch a stack behind proxy-flow using tcp and access them using their fqdn (an example could be ssh test.example.com)

So in order to try it, I've tried to use the redis sample provided in the documentation.

Unfortunatelly I didn't succeed to have it working, even setting ServiceDomain (example.com).

The expected result should be that when I telnet to serviceName.serviceDomain 6379 I shall be able to send PING an receive a pong.

Below is the stack I use and lauch using docker stack deploy -c docker-stack.yml redis:

============
version: "3"
services:
  redis:
    image: redis:3.2
    deploy:
     placement:
        constraints: [node.labels.zone == internal]
     labels:
      - "com.df.notify=true"
      - "com.df.distribute=true"
      - "com.df.port=6379"
      - "com.df.srcPort=6379"
      - "com.df.reqMode=tcp"
      - "com.df.serviceDomain=example.com"
    networks:
      - redis
      - proxy_proxy
networks:
  proxy_proxy:
    external: true
  redis:
     driver: overlay
============

Note: if I don't set com.df.serviceDomain=example.com I can access the service with no problem (because I have wildcard DNS on example.com) however it  is not an acceptable behaviour, because won't scale well if I want for sample a prod, preprod etc...

Maybe it is an enhancement feature but would be nice to have.

**Comment by faisyl** [comment]
If you want to route TLS connections without terminating them on haproxy, you could use SNI based routing that docker-flow-proxy supports. Works really well for services identified by unique FQDNs. If it's plain TCP traffic, there's no way haproxy can inspect the traffic to determine how to route the traffic.

**Comment by gilleslabs** [comment]
Thanks for the reply, in fact it is for plain tcp traffic. So I understand it won't work.

**Comment by vfarcic** [comment]
@gilleslabs Yes. It will not work for plain TCP traffic since, as @faisyl pointed out, there are no headers and HAProxy cannot determine almost any information.

I'll close the ticket. Feel free to reopen it if you any workaround comes to your mind.
