### ISSUE TITLE
It is possible apply oauth2 authentication to df-proxy?

### ISSUE THREAD

**Issue by paulhkhsu** [vfarcic/docker-flow-proxy#259]
Hi,
I have try df-proxy and listener and it works pretty well. I know df-proxy provide user/password protected, but most of enterprise solution can use oauth2 etoken to auth api. My question is can oauth2 can be set up with df-proxy. In toher word, proxy get the etoken and send to auth server to verify the token before redirect to service.

**Comment by vfarcic** [comment]
HAProxy itself does not have OAuth so it would need to be a service lying in between the proxy and the destination services. That would be, in my opinion, too much coupling. I'd prefer keeping DFP do what proxies do (request evaluation and forwarding) and leave authentication to other services. I suggest you use a service dedicated for that purpose. You can easily run some form of authentication in parallel with the proxy.
