### ISSUE TITLE
How to manage multiple proxy containers?

### ISSUE THREAD

**Issue by dtmistry** [vfarcic/docker-flow-proxy#26]
If the node serving the proxy container goes down, swarm will take some time to start it somewhere else. So my backends will be unaccessible for a while. So it makes sense to have multiple instances (perhaps a global proxy service). 

But in that case, how do I reconfigure the proxy with new services? 

The only thing I can do right now is to make an external process aware of the swarm nodes where the proxy is running and reconfigure on those nodes.

Just wanted to check if you have a better solution.

**Comment by vfarcic** [comment]
The idea is as follows.

If a request has "distribute=true", the instance that receives it will resend it to all the other instances. The same logic will be applied to both *reconfigure* and *remove* request types.

What do you think? Would that solve the problem you explained?

**Comment by dtmistry** [comment]
That would work. 

Are you thinking about inspecting the 'proxy' service to figure out the IP addresses of containers running on the 'proxy' network?

**Comment by vfarcic** [comment]
With the new networking, you can inspect DNS record *tasks.[SERVICE_NAME]*. That entry returns the IPs of all the containers. The trick is that it is available only inside a container that belongs to the same network. You cannot do that from "outside". The *tasks.[SERVICE_NAME]* DNS record is one of the still undocumented Docker 1.12 features.

When the proxy receives a request to reconfigure a service and *distribute=true* is present in the query, it will take the name of the service, find all the IPs in the DNS *tasks.[SERVICE_NAME]* and resend the same request to all of them.

I just finished the code but did not have time to do integration tests. It's very late where I live (5:15h). Tomorrow I'll run them and, if everything works correctly, make a new release. Unlike most other tests, those are a bit tricky to automate.

**Comment by vfarcic** [comment]
The feature is done. An example can be found in https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode.md#scaling-the-proxy .

Can you please try it out and let me know if it works as expected.

**Comment by dtmistry** [comment]
@vfarcic Thanks for the quick implementation. Will try it out and report and issues.

**Comment by vfarcic** [comment]
Please reopen the ticket if you experience a problem.
