### ISSUE TITLE
Swarm-listener unable to send create notification

### ISSUE THREAD

**Issue by thomaco** [vfarcic/docker-flow-proxy#262]
Hello,

I'm trying to run docker-flow-proxy with swarm-listener, however, swarm-listener seems unable to update the proxy, as the logs are filled with the following lines;

> 2017/06/06 21:53:00 Retrying service created notification to http://haproxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=80&serviceName=mywebsite&servicePath=%2F
> 2017/06/06 21:53:35 Retrying service created notification to http://haproxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=80&serviceName=mywebsite&servicePath=%2F
> 2017/06/06 21:54:10 Retrying service created notification to http://haproxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=80&serviceName=mywebsite&servicePath=%2F

I also entered the container, installed curl and tried to do it manually, which left me with this;

> / # curl -v http://haproxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true\&port=80\&serviceName=mywebsite\&servicePath=%2F
> *   Trying 10.0.0.6...
> * TCP_NODELAY set
> * connect to 10.0.0.6 port 8080 failed: Operation timed out
> * Failed to connect to haproxy port 8080: Operation timed out
> * Closing connection 0
> curl: (7) Failed to connect to haproxy port 8080: Operation timed out

The commands for creating the two services are these two;
> $ docker service create --name swarm-listener --network backend --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" -e DF_NOTIFY_CREATE_SERVICE_URL=http://haproxy:8080/v1/docker-flow-proxy/reconfigure -e DF_NOTIFY_REMOVE_SERVICE_URL=http://haproxy:8080/v1/docker-flow-proxy/remove --constraint 'node.role==manager' vfarcic/docker-flow-swarm-listener
> $ docker service create --name haproxy -p 80:80 --network backend -e MODE=swarm -e LISTENER_ADDRESS=swarm-listener -e DEBUG=true -e STATS_USER=stats -e STATS_PASS=stats --constraint 'node.labels.type == proxy' vfarcic/docker-flow-proxy

Pinging between the two works, but netstat -tulpn in the proxy container only lists :::8080 for port 8080 - is that an issue? Any other issues that you can see, or other info I should include?

Docker is version 17.03 on both nodes(actually, all 4 nodes), all nodes run Ubuntu 16.04 and the swarm were initialized with listener-address. Both on the first and second attempt to create a swarm.

On my previous attempt to get all this to work, haproxy was eventually updated with the service definition of the webpage, but would only return 503 error messages. When I attempted to curl the servicename from the proxy container, I got an "Host unreachable" message, even though curling from another container on the same node, but which belonged to another service, worked. So I settled with no sense made..

**Comment by vfarcic** [comment]
@thomaco Is the service you're creating public? If it is, I could run it in my cluster and debug the problem.

**Comment by vfarcic** [comment]
Can you enter into the `swarm-listener` container and execute:

```
curl -v http://haproxy:8080/v1/docker-flow-proxy/config
```

That operation is not related with any target service and outputs DFP config. We'll use it to verify whether the communication between the two services works. If you don't get response 200, the problem is in the `backend`.

Also, can you please let me know which ports are opened?

**Comment by thomaco** [comment]
It's for a school project, so I just found a working service to proxy.
> $ docker service create --name mywebsite --network backend --constraint "node.labels.type == worker" --label com.df.notify=true --label com.df.distribute=true --label com.df.servicePath=/ --label com.df.port=80 dockercloud/hello-world

Based on the output below, I guess the communication between the two services work?

> $ curl -v http://haproxy:8080/v1/docker-flow-proxy/config
> *   Trying 10.0.0.2...
> * TCP_NODELAY set
> * Connected to haproxy (10.0.0.2) port 8080 (#0)
> > GET /v1/docker-flow-proxy/config HTTP/1.1
> > Host: haproxy:8080
> > User-Agent: curl/7.52.1
> > Accept: */*
> > 
> < HTTP/1.1 200 OK
> < Content-Type: text/html
> < Date: Wed, 07 Jun 2017 09:35:06 GMT
> < Content-Length: 716
> < 
> global
>     pidfile /var/run/haproxy.pid
> 
> defaults
>     mode    http
>     balance roundrobin
> 
>     option  dontlognull
>     option  dontlog-normal
>     option  forwardfor
>     option  redispatch
> 
>     maxconn 5000
>     timeout connect 5s
>     timeout client  20s
>     timeout server  20s
>     timeout queue   30s
>     timeout http-request 5s
>     timeout http-keep-alive 15s
> 
>     stats enable
>     stats refresh 30s
>     stats realm Strictly\ Private
>     stats auth admin:admin
>     stats uri /admin?stats
> 
> frontend dummy-fe
>     bind *:80
>     bind *:443
>     mode http
>     option http-server-close
>     acl url_dummy path_beg /dummy
>     use_backend dummy-be if url_dummy
> 
> backend dummy-be
>     mode http
>     server dummy 127.0.0.1:1111
> * Curl_http_done: called premature == 0
> * Connection #0 to host haproxy left intact

Open/listening ports in the haproxy container;
> / # netstat -tulpn
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
> tcp        0      0 127.0.0.11:35896        0.0.0.0:*               LISTEN      -
> tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      12/haproxy
> tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      12/haproxy
> tcp        0      0 :::8080                 :::*                    LISTEN      1/docker-flow-proxy
> udp        0      0 127.0.0.11:48784        0.0.0.0:*                           -
> udp        0      0 127.0.0.1:1514          0.0.0.0:*                           1/docker-flow-proxy

**Comment by thomaco** [comment]
After letting the haproxy/swarm-listener sit for a while, this error is seen in the logs on the listener;

> 2017/06/07 09:36:49 Retrying service created notification to http://haproxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=80&serviceName=mywebsite&servicePath=%2F
2017/06/07 09:36:54 ERROR: Request http://haproxy:8080/v1/docker-flow-proxy/remove?distribute=true&serviceName=mywebsite returned status code 500
2017/06/07 09:36:54 ERROR: Request http://haproxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=80&serviceName=mywebsite&servicePath=%2F returned status code 500
{"Mode":"swarm","Status":"NOK","Message":"Could not perform DNS tasks.proxy lookup. If the proxy is not called 'proxy', you must set SERVICE_NAME=\u003cname-of-the-proxy\u003e.","ServiceName":"mywebsite","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomain":null,"ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"IgnoreAuthorization":false,"Port":"80","ReqMode":"http","ReqModeFormatted":"","ServicePath":["/"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}

**Comment by thomaco** [comment]
@vfarcic So I looked at it again with a fresh set of eyes, and found issue #76, which subsequently solved all my problems.

Just as a tip for the future - might it be possible to specify the error message even more for dumb users like myself? Also, might it be an idea to add a small info-note on http://proxy.dockerflow.com/swarm-mode-auto/ ?

Anyways, closing the issue, as this was a matter of PEBCAC.

**Comment by vfarcic** [comment]
Was it  `SERVICE_NAME` that fixed the problem?

I'll reopen this ticket as a reminder to make error messages easier to understand as well as to improve the tutorial. Thanks for the feedback.

As a side note, I'd appreciate a pull request with the improvements to the tutorial. It is difficult to put myself into shoes of other people. Would you be willing to modify the docs?

**Comment by thomaco** [comment]
Yes, adding `SERVICE_NAME` as an environmentvariable to the proxy fixed the problem.

Sure, I'll create a pull request with suggested improvement to the tutorial.

**Comment by vfarcic** [comment]
Any suggestions what would be a more appropriate error message?

**Comment by thomaco** [comment]
Seeing as the current error message is currently `"Could not perform DNS tasks.proxy lookup. If the proxy is not called 'proxy', you must set SERVICE_NAME=<name-of-the-proxy>."`, only a small clarification is needed. Something like `"Could not perform DNS lookup for tasks.proxy. If the proxy is not called 'proxy', you must set SERVICE_NAME=<name-of-the-proxy> on the proxy service."` maybe?

Moving tasks.proxy to the end of the sentence makes the sentence clearer, as I was somewhat confused on what 'DNS tasks.proxy lookup' meant. For the rest, it's just needed to specify that the variable need to be set on the proxy, to avoid confusion as to where it needs to be set.

**Comment by vfarcic** [comment]
Thanks!

It's done and will be available in a few minutes in the release 1.409.
