### ISSUE TITLE
How to use It with a PHP-FPM Container?

### ISSUE THREAD

**Issue by gcavalcante8808** [vfarcic/docker-flow-proxy#264]
Hello Folks,

How can I Use dockr-flow-proxy with an FPM application?

Normally I have something like that on my NGINX:

        include fastcgi_params;
        fastcgi_pass fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;

It it possible to use docker-flow-proxy as a reverse proxy for a fpm application? If Yes, what labels should I put on my docker-compose file?

Thanks in advance.

**Comment by vfarcic** [comment]
I'm not familiar with FPM applications.

Can you clarify whether you are looking for a Web server (e.g. to serve PHP files) or for a reverse proxy (e.g. forward requests based on their path, domains, or other criterias)?

I would appreciate if you can tell me what you're trying to do. If you provide a bit more info, I can tell you whether DFP is a good option (or option at all).

**Comment by gcavalcante8808** [comment]
Oh Hello,

PHP FPM is used in conjunction with nginx on lemp stacks. In truth, my question is: can overflow proxy replace nginx in this scenario?

Example of how to setup lemp stacks: https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-in-ubuntu-16-04

In this case the reverse proxy receive a request, pass some params to php-fpm which return the result.

**Comment by vfarcic** [comment]
The problem was of semantical nature. What you need is a web server, not a reverse proxy (nginx can act as both).

The short answer is that DFP does not act as a web server. You should use nginx to serve your PHP pages. If you need a reverse proxy that forwards requests to your services, than DFP might be a good option.
