### ISSUE TITLE
HAProxy disables servers too soon.

### ISSUE THREAD

**Issue by rommik** [vfarcic/docker-flow-proxy#266]
Info:

DFP 1.346
DF Listener: 1.34

When deploying a new stack to Docker Swarm, HAProxy marks it as disabled because it was not able to resolve address.

``[WARNING] 159/153555 (965) : parsing [/cfg/haproxy.cfg:2802] : 'server ricoh_felix-on-swarm' : could not resolve address 'ricoh_felix-on-swarm', disabling se
rver.
[WARNING] 159/153555 (965) : parsing [/cfg/haproxy.cfg:2807] : 'server ricoh_uxserver-on-swarm' : could not resolve address 'ricoh_uxserver-on-swarm', disabl
ing server.``

However, when I exec into proxy container, I am able to ping both addresses successfully.

I believe, the issue is in the race condition. The container is too slow to become available, and HaProxy flags it as not resolved.

The current workaround is to spin up another stack, and HaProxy is forced to resolve all previous addresses again.

**Comment by vfarcic** [comment]
By design, DFP should retry after a few seconds. Can you confirm that it didn't?

**Comment by rommik** [comment]
it is not in the logs, how else can I confirm it?

**Comment by vfarcic** [comment]
When HAProxy fails to configure, DFP repeats it. Normally, if you do not see those errors repeated, it means that it succeeded. However, I cannot guarantee that I did not miss an error and failed to repeat the process in cases like this. Let me double check...

**Comment by rommik** [comment]
You will need a container that takes a while to start...in my case, it can take 20-30 seconds. or longer if an image needs to be downloaded.

**Comment by vfarcic** [comment]
I managed to reproduce a similar, but not exactly the same situation. In my case, even though the error was similar, `swarm-listener` (you're using it?) continued trying. DFSL is configured to retry a failed `reconfigure` request 50 times with a pause for 5 seconds in between each.

Can you send me the stack and/or commands you used to create services? Also, I'd appreciate if you can send me a complete log or, at least, a bit more than those two lines? Attach logs of both the `proxy` and the `swarm-listener`. That would help me reproduce the problem fully.

**Comment by rommik** [comment]
I was able to reproduce the issue with this public stack

``
version: '3'
services:
  whoami:
    image: jwilder/whoami

    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.hostname == swarm-node-0
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=whoami.domain.com
        - com.df.servicePath=/
        - com.df.port=8080
        - com.df.httpsOnly=true
    networks:
        proxy2:

networks:
  proxy2:
    external: true

``

logs in Listener
``
2017/06/12 20:12:32 Sending service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&httpsOnly=true&port=80
80&serviceDomain=whoami.overture.barco.com&serviceName=whoami_whoami&servicePath=%2F
``
Logs in DFP
``
[WARNING] 162/201232 (987) : parsing [/cfg/haproxy.cfg:3150] : 'server whoami_whoami' : could not resolve address 'whoami_whoami', disabling server.
2017/06/12 20:12:32 Proxy config was reloaded
``

**Comment by vfarcic** [comment]
I had to remove some of the constraints so that it can run on my cluster. I also changed your image for the same image based on `vfarcic`. The modified stacks are in https://github.com/vfarcic/docker-flow-proxy/tree/master/issues/266 directory.

I executed the commands from the https://github.com/vfarcic/docker-flow-proxy/blob/master/issues/266/README.md. The first execution produced proxy logs that follow.

```
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:41 Starting HAProxy
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:41 Starting "Docker Flow: Proxy"
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:45 Sending distribution request to http://10.0.1.3:8080/v1/docker-flow-proxy/reconfigure?distribute=false&httpsOnly=true&port=8080&serviceDomain=whoami.domain.com&serviceName=stack_whoami&servicePath=%2F
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:45 Creating configuration for the service stack_whoami
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:45 Reloading the proxy
proxy_proxy.1.jgd7tyb4bzkv@moby    | [WARNING] 163/184545 (16) : parsing [/cfg/haproxy.cfg:58] : 'server stack_whoami' : could not resolve address 'stack_whoami', disabling server.
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:45 Proxy config was reloaded
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:46 Got configuration from http://swarm-listener:8080.
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:46 Creating configuration for the service stack_whoami
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:46 Reloading the proxy
proxy_proxy.1.jgd7tyb4bzkv@moby    | 2017/06/13 18:45:46 Proxy config was reloaded
```

I got the same message as you. It was caused by the container not running at the time proxy tried to reconfigure itself. However, a few moments later (less than a second), it tried again and succeeded.

To be on the safe side, I run the same commands one more time. The log of the proxy is as follows.

```
proxy_proxy.1.8jhl00uvrkgx@moby    | 2017/06/13 18:46:19 Starting HAProxy
proxy_proxy.1.8jhl00uvrkgx@moby    | 2017/06/13 18:46:19 Starting "Docker Flow: Proxy"
proxy_proxy.1.8jhl00uvrkgx@moby    | 2017/06/13 18:46:21 Sending distribution request to http://10.0.0.3:8080/v1/docker-flow-proxy/reconfigure?distribute=false&httpsOnly=true&port=8080&serviceDomain=whoami.domain.com&serviceName=stack_whoami&servicePath=%2F
proxy_proxy.1.8jhl00uvrkgx@moby    | 2017/06/13 18:46:21 Creating configuration for the service stack_whoami
proxy_proxy.1.8jhl00uvrkgx@moby    | 2017/06/13 18:46:21 Reloading the proxy
proxy_proxy.1.8jhl00uvrkgx@moby    | 2017/06/13 18:46:21 Proxy config was reloaded
```

It worked.

The problem I'm facing is that I cannot reproduce it myself. I'm not (yet) sure whether it is related to your customized proxy image, your environment, or that I was lucky and you weren't.

**Comment by vfarcic** [comment]
@rommik I'll close this issue since there was no response on the last message. Feel free to reopen it if you'd like to continue the discussion.

**Comment by rommik** [comment]
@vfarcic just a quick update, I see that in the latest version of DFP this issue is not present anymore.
