### ISSUE TITLE
Allow df-proxy to route using headers

### ISSUE THREAD

**Issue by joskfg** [vfarcic/docker-flow-proxy#269]
Currentyl the proxy allow you to add headers in response or request, but doesn't allow route to a container using them.

For example if I create a service like:
```
docker service create \
    --name nginx-demo-v1 \
    --label com.df.notify=true \
    --label com.df.serviceDomain="www.test.com.dev" \
    --label com.df.serviceHeader="X-Version: 1" \
    nginxdemos/hello`

docker service create \
    --name nginx-demo-v2 \
    --label com.df.notify=true \
    --label com.df.serviceDomain="www.test.com.dev" \
    --label com.df.serviceHeader="X-Version: 2" \
    nginxdemos/hello`
```
Swarm-listener should be able to create the rules in HA-Proxy and allow the next curl executions to reach the specified service.
`curl -H "X-Version: 1" www.test.com.dev # This should reach nginx-demo-v1`
`curl -H "X-Version: 2" www.test.com.dev # This should reach nginx-demo-v2`

The label should allow you to add more than one header separated by commas, like for example:
```
docker service create \
    --name nginx-demo \
    --label com.df.notify=true \
    --label com.df.serviceDomain="www.test.com.dev" \
    --label com.df.serviceHeader="X-Version: 2, User-Agent: secret-user-agent" \
    nginxdemos/hello`
```
so the next two commands won't route:
`curl -H "X-Version: 1" www.test.com.dev # 5XX error`
`curl -H "User-Agent: secret-user-agent" www.test.com.dev # 5XX error`
because you will need to send both headers like in the next example:
`curl -H "X-Version: 1" -H "User-Agent: secret-user-agent" www.test.com.dev # This routes to the service`

**Comment by vfarcic** [comment]
@joskfg I made the changes but could not run functional tests to confirm that everything works as expected. I'm in a place with very poor connection and cannot pull required images. Not sure whether there's something wrong with Docker Hub or my internet is just too bad.

Can you do me a favor and try the release 1.269? The only new thing is the `serviceHeader` parameter. An example would be:

```
...
  -- label com.df.serviceHeader="X-Version:3,name:Viktor"
...
```

Just as you suggested, key/value is separated with `:` and multiple headers are separated with `,`.

Try it with one header only. If that works, try with multiple headers.

**Comment by vfarcic** [comment]
I managed to test it. The [release 1.419](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.419) should work correctly. Please try it out and let me know if it fits your use case.

**Comment by joskfg** [comment]
I've been busy lately, but from your examples I see that it accomplish my requirements, thanks. I'll try it ASAP.

Thanks a lot!
