### ISSUE TITLE
Segfaulting swarm-listener and go-demo

### ISSUE THREAD

**Issue by basz** [vfarcic/docker-flow-proxy#271]
Since I'm new to this it took some time to figure out that it looks like stuff is segfaulting.

I've created a repo to help with replicating it...

https://github.com/basz/docker-provision

**Comment by basz** [comment]
I'v created an ubuntu16.04 box with vagrant and created a machine with the generic driver. Then ran the same commands. I can confirm it also crashes...

```
docker-machine ssh node-1 docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by vfarcic** [comment]
Can you post the commands you used with Vagrant? It'll be easier for me to reproduce it with it than with DO.

**Comment by vfarcic** [comment]
Did you create those machines on your laptop? Is it a company laptop with firewall/proxy/VPN?

**Comment by basz** [comment]
Ill post my vagrant file later tonight. My own MacBook pro. On a WiFi connected to my phone hotspot.

**Comment by basz** [comment]
@vfarcic see your slack private messages

**Comment by vfarcic** [comment]
Can you please try the latest (yesterday's) release of `swarm-listener`. I made a hotfix for some other issue but I think it might be the solution for this one as well.
