### ISSUE TITLE
Logging request headers

### ISSUE THREAD

**Issue by valeriomazzeo** [vfarcic/docker-flow-proxy#274]
When specifying `DEBUG_HTTP_FORMAT="%hr\ "`, request headers are not logged because they have to be captured.

In order to do that is necessary to specify also:
`EXTRA_FRONTEND="capture request header NAME len BYTES_LENGTH`

Would be useful to have an option to do that.

**Comment by vfarcic** [comment]
It's available in the [release 17-07-5](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17-07-5). Can you please try it out and let me know if it fits your use case?

**Comment by valeriomazzeo** [comment]
great, thanks 👍
