### ISSUE TITLE
[Feature request] Limit allowed http methods

### ISSUE THREAD

**Issue by ClaudiuGeorgiu** [vfarcic/docker-flow-proxy#279]
Hello,
I think it could be useful to add the possibility to limit the allowed http methods (POST, GET etc.) for a certain service.
Example use case: a swarm cluster with 2 services, service_A and service_B, where service_A can make POST, DELETE and GET requests to service_B, but only the GET endpoint should be available outside the proxy. The idea is to provide read-only access to some services from outside the proxy but to let the full access to the other services inside the proxy.

I was thinking of something like this:

    services:
      service_B:
        ...
        deploy:
          labels:
            # If not specified, all methods should be allowed by default.
            # If specified, only the chosen methods should be allowed in the request.
            - com.df.allowedMethods=GET,HEAD,OPTIONS

            # If not specified, all methods should be allowed by default.
            # If specified, the requests with the chosen methods should be rejected.
            # In case of conflict with the previous setting for a specific method,
            # this setting should take the precedence and disable the method.
            - com.df.disabledMethods=POST,PUT,DELETE

As a workaround, at the moment I'm editing the `haproxy.tmpl` file to obtain the same behavior:

    # Deny all DELETE requests coming to service_B
    acl is_delete_method method DELETE
    http-request deny if is_delete_method { hdr(host) -i my-service.example.com }

Do you think this could be a useful feature? Thanks in advance.

**Comment by vfarcic** [comment]
It's done and available in the [release 17-06-1](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17-06-1). Please try it out and let me know whether it works as expected.

**Comment by ClaudiuGeorgiu** [comment]
I tried the last version of the proxy and works perfectly, exactly how I was expecting! Thank you very much!
