### ISSUE TITLE
Unable to block HTTP connection through docker flow proxy.

### ISSUE THREAD

**Issue by avikatgithub** [vfarcic/docker-flow-proxy#283]
I have tried rreqMode label as below but still http url is forwarding the request to https. What should be the correct label if I want to block http call for that microservice.

     labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.port: "8080"
        com.df.servicePath: "/eibcontroller"
        com.df.reqPathSearch: "/eibcontroller/"
        com.df.reqPathReplace: "/"
        com.df.verifyClientSsl: "$verifyssl"
        com.df.reqMode: "https"

**Comment by vfarcic** [comment]
It's done and available from the [release 17-07-8](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17-07-8). Please try it out and let me know whether it fits your use case.

**Comment by avikatgithub** [comment]
Thanks a lot. Appreciate your help.
