### ISSUE TITLE
Problems with custom frontend template - bug or wrong usage?

### ISSUE THREAD

**Issue by narcoticfresh** [vfarcic/docker-flow-proxy#289]
## The good
I have a working docker-flow-proxy in my local swarm. So far so good ;-)

## The need
Because of my requirements, I need to change way it generates the frontend. Specifically, I want to change the acl line in case of a domain match in tcp mode..

From
```
   acl domain_stack_app443 hdr(host) -i myhostname
```

To
```
   acl domain_stack_app443 req.ssl_sni -i myhostname
``` 

This is an important change if we want to proxy a server that handles his own certificates. `req.ssl_sni` is a level 4 fetch (= flow-proxy doesn't need to TLS negotiate itself), whereas `hdr(host)` is level 7, which (AFAIK) makes us need to TLS negotiate in flow-proxy.

## The problem

So i looked through many issues, all the docs (from top to bottom maaaany times) and found the `templateFePath` parameter.

What I did then was:
* Forced proxy only to manager node (volumes are easier for me there)
* I took the string from [here](https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/template.go#L62) and saved it to a file on the node
* I mounted that into the container - yes I verified it contains what i want it to contain and that it's readable from the container.
* Please see my config file [here](https://gist.github.com/narcoticfresh/4b89b547cece20f8c67dea2e1f311e3a) - the line i changed is [here](https://gist.github.com/narcoticfresh/4b89b547cece20f8c67dea2e1f311e3a#file-fe-template-tmpl-L11)
* I fired a request to `/v1/docker-flow-proxy/reconfigure?distribute=true&port=443&reqMode=tcp&serviceDomain=mydomain&serviceName=myservice&srcPort=443&templateFePath=/tmp/owntmpl/fe-template.tmpl` (local path verified)

And then I get in the proxy log:

```
2017/07/13 15:31:16 Sending distribution request to http://10.0.2.4:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=443&reqMode=tcp&serviceDomain=mydomain&serviceName=myservice&srcPort=443&templateFePath=%2Ftmp%2Fowntmpl%2Ffe-template.tmpl
2017/07/13 15:31:16 Creating configuration for the service szkb_nginx
2017/07/13 15:31:16 http: panic serving 10.0.2.4:57320: runtime error: invalid memory address or nil pointer dereference
goroutine 163 [running]:
net/http.(*conn).serve.func1(0xc8203dc400)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x893020, 0xc82000e120)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x7fa4ae245780, 0xc820368620, 0x7a5e60, 0xc82028a048, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:101 +0x34
_/src/actions.(*Reconfigure).parseFrontTemplate(0xc82028a000, 0xc820085b00, 0x8b5, 0xc82028a048, 0x0, 0x0)
	/src/actions/reconfigure.go:237 +0x435
_/src/actions.(*Reconfigure).GetTemplates(0xc82028a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/src/actions/reconfigure.go:124 +0x431
_/src/actions.(*Reconfigure).createConfigs(0xc82028a000, 0x0, 0x0)
	/src/actions/reconfigure.go:143 +0x166
_/src/actions.(*Reconfigure).Execute(0xc82028a000, 0x1, 0x0, 0x0)
	/src/actions/reconfigure.go:65 +0x2fc
_/src/server.(*serve).ReconfigureHandler(0xc82006e7e0, 0x7fa4ae24ba20, 0xc820370820, 0xc82031e1c0)
	/src/server/server.go:140 +0x792
_/src/server.(Server).ReconfigureHandler-fm(0x7fa4ae24ba20, 0xc820370820, 0xc82031e1c0)
	/src/server.go:69 +0x50
net/http.HandlerFunc.ServeHTTP(0xc820140b00, 0x7fa4ae24ba20, 0xc820370820, 0xc82031e1c0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8200148c0, 0x7fa4ae24ba20, 0xc820370820, 0xc82031e1c0)
	/go/src/github.com/gorilla/mux/mux.go:114 +0x2a8
net/http.serverHandler.ServeHTTP(0xc820017400, 0x7fa4ae24ba20, 0xc820370820, 0xc82031e1c0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8203dc400)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

# My question

Could this be:
* That my template is wrong? There is no examples in the documentation, so i thought i just copy the string literal from the class? Is that assumption wrong?
* A bug in docker-flow-proxy?
* Any other cause? 

Thanks for any help and keep up the good work! It's a very promising and really needed project!

**Comment by vfarcic** [comment]
The template is getting more and more complicated with each new feature added to the problem. Indeed, there is no easy way to find out what the current template is except looking at it from code.

I recommend not providing a custom template based on the one used in the code. It is too complex. Instead, I'd recommend creating your own template based on the structs defined in https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/types.go. The good news is that with that approach you'll get a specific template that does what you need and not more. The bad news is that creating a new template is not as trivial as it might sound.

To make things more complicated, when a template processing fails, Go does not inform which part of the template is faulty. The only information I have from the stack trace you provided is that the template cannot be processed.

We can proceed with the issue in two directions. One would be for me to find out why template failed and fix the problem or show you what you did wrong (not sure which one it is until I try it out myself). The alternative would be for me to add a new parameter that would allow you to use `req.ssl_sni`. It could be `serviceDomainAlgo` (short for algorithm). One of the supported values could be `ssl_sni`. I guess that approach would be better but I'd like to confirm with you first.

**Comment by narcoticfresh** [comment]
@vfarcic as you point out, adding a new template doesn't seem to be easy.. Especially considering I'm not familiar with go at all.. 

Incredible how the contributors in this project could author those templates using a template engine that doesn't show what is wrong if complication fails! Amazing work then :-) 

So yes.. if you can somehow make it happen that we can use other fetches like req.ssl_sni via labels, that would be highly appreciated! 

Thanks

**Comment by vfarcic** [comment]
It's done as [release 17.07.13-2](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17.07.13-2). Can you please try it out and let me know if it works as expected.

**Comment by narcoticfresh** [comment]
@vfarcic works great! thanks so much!

only problem is that the env variable `DFP_SERVICE_SERVICE_DOMAIN_ALGO` on the container seems to be ignored(?).. i need to pass it via http to every reconfigure call.. had the same problem yesterday specifying the template.. i'll open a new ticket for that..
