### ISSUE TITLE
[Swarm mode] Host/Domain based routing

### ISSUE THREAD

**Issue by justinsoliz** [vfarcic/docker-flow-proxy#29]
Given a proxy instance load balancing multiple containers, is it possible to route based on the incoming Host headers from the request?

e.g.
HOST:domain_one.com => port:3000
HOST:domain_two.com => port:3001

I see an argument for `serviceDomain`, would that work for host based routing

**Comment by JanSchroeder** [comment]
Here is the Solution?


> Optionally, serviceDomain can be used as well. If specified, the proxy will allow access only to requests coming from that domain. The example that follows sets serviceDomain to my-domain.com. After the proxy is reconfigured, only requests for that domain will be redirected to the destination service.

`curl "$(docker-machine ip node-1):8080/v1/docker-flow-proxy/reconfigure?serviceName=go-demo&servicePath=/demo&serviceDomain=my-domain.com&port=8080"`

https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode.md

**Comment by JanSchroeder** [comment]
I have another problem.
How can I forward 2 ports on the same container?

HOST:domain_one.com:80 => web_container:80
HOST:domain_one.com:443 => web_container:443

I try this commands, but the second command overwrite the first command. Is there a options to assign 2 port to one container?

`0.0.0.0:8080/v1/docker-flow-proxy/reconfigure?serviceName=web_container&servicePath=/&serviceDomain=ml-master.local&port=80

0.0.0.0:8080/v1/docker-flow-proxy/reconfigure?serviceName=web_container&servicePath=/&serviceDomain=ml-master.local&port=443`

**Comment by vfarcic** [comment]
Sorry for not responding earlier. ServiceDomain can be used to configure the proxy to accept requests from a specific domain.

As for forwarding two ports, in most cases you don't need/want to do that. Normally, you'd accept requests from ports 80 and 443 and redirect them to a single port of a service (e.g. 8080). What you normally want is to restrict external traffic to your service to HTTPS (443) and forward it internally to whichever port the service is running. The proxy is, by default, configured to accept requests from both 80 and 443.

So, you if run:

```
0.0.0.0:8080/v1/docker-flow-proxy/reconfigure?serviceName=web_container&servicePath=/&serviceDomain=ml-master.local&port=8081
```

... all requests to the path / and entering through the port 80 or 443, will be redirected to the service web_container running on port 8081.

We can discuss further the need for forwarding to two ports. If there is a good use case, I'll be glad to add the feature to the proxy. Can you please ping me on Skype (user: vfarcic) or HangOuts (user: viktor@farcic.com)?

**Comment by JanSchroeder** [comment]
I have a container with an nginx.
The nginx accepted port 80 and 443 to provide SSL and non-SSL content

How can I Docker flow configure so that both ports are forwarded to one container?
Is this not a normal use case?

Currently I need for each port one container?

**Comment by vfarcic** [comment]
The base configuration of the proxy is in https://github.com/vfarcic/docker-flow-proxy/blob/master/haproxy.tmpl . It accepts ports 80 and 443. Requests to those ports will be forwarded to services running on any port.

The relevant part of the haproxy.tmpl is:

```
frontend services
    bind *:80
    bind *:443
```

You are free to change the base config (template) by extending the container.

**Comment by vfarcic** [comment]
Closing the ticket due to inactivity. Please reopen it if you feel some additional tasks should be done related with this issue.
