### ISSUE TITLE
Make possible to add backend servers under existing backend

### ISSUE THREAD

**Issue by karolyczovek** [vfarcic/docker-flow-proxy#296]
Hi, 
seems with the (legacy) consul mode it was possible, to populate already existing backends with new servers, but since DFL swarm mode is in place, it is only adding strictly one server definition and HA is provided by the overlay L4 HA - what breaks L7 session stickiness for legacy (stateful) services.

Seems #171 covers the same, container id could be added as default cookie prefix.

**Comment by vfarcic** [comment]
I made the first draft of the feature. Please take a look at my last message in the issue #171 . I'd appreciate if you can test it and send me your feedback before making it an official release.

**Comment by karolyczovek** [comment]
as first look working fine, many thanks.

**Comment by vfarcic** [comment]
@karolyczovek I think it would be great to add a tutorial with this feature to the documentation. Do you have a public service that could demonstrate stickiness? I don't have any at hand and that would save me from making one from scratch. It would be even better if you could write a tutorial doc and make a PR but that might require too much of your time.

Please let me know if you can provide any of the two (sticky service and/or tutorial).
