### ISSUE TITLE
Allow httpsOnly conditionally

### ISSUE THREAD

**Issue by jorianvo** [vfarcic/docker-flow-proxy#299]
Currently we use DFP as the TLS termination point after which we redirect requests (using plain HTTP) to the appropriate backend. Using LetsEncrypt to obtain the certificates for our domains. I would like to redirect all HTTP traffic which hits DFP to be redirected to HTTPS, which works fine by using the `httpsOnly` query parameter. But here comes the problem: this will redirect all requests to HTTPS, hence LetsEncrypt fails initially (as I have no certificates yet).

So the flow I would like to achieve is something like:
![letsencrypt-flow](https://user-images.githubusercontent.com/3626932/28589480-a52a81c6-717e-11e7-8016-2fc5db4bfa76.png)
In this case a well known URL `http://example.com/.well-known/acme-challenge` is excluded when redirecting HTTP to HTTPS, which means LetsEncrypt is able to verify the challenge and provide the certificates. Just to see if it would work I wrote the integration tests, but it boils down to: to exclude the URL (the static `/.well-known/acme-challenge` in this case) you can update the [template.go](https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/template.go#L149-L151) to look like:
```	
{{- if $.HttpsOnly}}
 redirect scheme https if !{ ssl_fc } !{ path_beg -i /.well-known/acme-challenge }
{{- end}}
```
And the [reconfigure_test.go](https://github.com/vfarcic/docker-flow-proxy/blob/09aa2d93a89268bfde495faaf13fddd469cfd426/actions/reconfigure_test.go#L499) to also look like ` redirect scheme https if !{ ssl_fc } !{ path_beg -i /.well-known/acme-challenge }`. This can of course be generalised, but I think the LetsEncrypt use case is quite common.

As I have already written the integration tests, I know it should work, but I would like your opinion on this matter.

**Comment by vfarcic** [comment]
I probably misunderstood the scenario so please correct me if I'm wrong. `httpsOnly` is applied on the per-service basis. Those services that have it will be redirected to https and those that don't will not. If DFLE does not have `httpsOnly=true` there will be no redirect. If all other services do have it set to `true` and your scenario would work the same without any changes. All services except DFLE would be required to redirect to https.

I'm sure I missed something in your description thus making the above paragraph incorrect. Can you please help me out to understand what that is?

**Comment by jorianvo** [comment]
No, you understood correctly, it seemed in my previous tests the redirect did happen. But as I currently see (and tested) it works correctly. So I'm not sure what went wrong in my previous tests, but thanks anyway!
