### ISSUE TITLE
Mapping service versions

### ISSUE THREAD

**Issue by wilkko** [vfarcic/docker-flow-proxy#3]
If I have a microservice called ms-books and it provides an API books/api. Microservice follows semantic versioning and major version of the API is carried in the URL for clients to know when a change is backward incompatible. If considering the following versions:

```
name=ms-books path=books/api/v0/ version=0.1.0 color=blue
ms-books books/api/v0/ 0.2.0 green
ms-books books/api/v0/ 0.3.0 blue
ms-books books/api/v0/ 0.9.0 green
ms-books books/api/v0/ 0.9.1 blue
ms-books books/api/v1/ 1.0.0 blue
ms-books books/api/v1/ 1.0.1 green
ms-books books/api/v2/ 2.0.0 blue
ms-books books/api/v2/ 2.1.0 green
```

Where should the service version be mapped? I guess the major version is what counts and could be mapped within the name like ms-books-v0, ms-books-v1, ms-books-v2? Versions v1 and v2 should be both running until all clients have upgraded to v2 so different major versions should likely also have their own blue-green deployment cycle. We were using Registrator, Consul HAProxy and Consul template before and are now evaluating how to complement that with Docker-flow's features.

**Comment by vfarcic** [comment]
The support has been added for multiple paths inside *servicePath* query parameter. Each path should be separated with comma (,). For example,

```bash
curl "$PROXY_IP:8080/v1/docker-flow-proxy/reconfigure?serviceName=books-ms&servicePath=/api/v1/books,/api/v2/books" \
     | jq '.'
```

@wilkko Can you please try it out and let me know whether it works as you expected? Optionally, I can add a second method of obtaining paths by reading the information from Consul.
