### ISSUE TITLE
Adding SSL certificates through http does not seem to update

### ISSUE THREAD

**Issue by adi-raghavendra** [vfarcic/docker-flow-proxy#304]
**Description**

Adding SSL certificates through http does not seem to update
**Steps to reproduce the issue:**
1. ```
curl -i -XPUT \
    --data-binary @certs/xip.io.pem \
    "$(docker-machine ip node-1):8080/v1/docker-flow-proxy/cert?certName=xip.io.pem&distribute=true"
```

2.` curl "$(docker-machine ip node-1).xip.io:8080/v1/docker-flow-proxy/config"`

3. **Expected**
```
frontend services
    bind *:80
    bind *:443 ssl crt /certs/xip.io.pem
    mode http
```

**Actual:**
```
frontend services
    bind *:80
    bind *:443 ssl crt-list /cfg/crt-list.txt
    mode http

```

**Comment by vfarcic** [comment]
Since quite a few releases ago, certificates were moved to `crt-list.txt`. Can you output the contents of the `/cfg/crt-list.txt` file?

**Comment by adi-raghavendra** [comment]
[cfg.zip](https://github.com/vfarcic/docker-flow-proxy/files/1188707/cfg.zip)

**Comment by adi-raghavendra** [comment]
Thanks @vfarcic  for looking into this. Attached zip file of the directoru.

**Comment by vfarcic** [comment]
Are you sure that the `/cfg` dir you sent me is the correct one? Seems that the proxy is in a different state than the one described in the issue. `haproxy.cfg` from the zip file has `bind *:443` while in the issue description it's `bind *:443 ssl crt-list /cfg/crt-list.txt`.

**Comment by adi-raghavendra** [comment]
I sent you the wrong /cfg folder. I checked the /cfg/crt-list.txt and it does point to the pem file. I guess I got confused because the documentation was not caught up. Sorry about that.

**Comment by vfarcic** [comment]
@adi-raghavendra Can you make a PR with a corrected documentation?

**Comment by adi-raghavendra** [comment]
https://github.com/vfarcic/docker-flow-proxy/pull/306
