### ISSUE TITLE
Containers name resolution issue when running proxy

### ISSUE THREAD

**Issue by brunifrancesco** [vfarcic/docker-flow-proxy#307]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Container names are not resolved when running services in SWARM Mode**

Run *proxy* and *swarm-listener* services is not working.
It seems proxy (deployed in a different node) is not able to resolve a container name.

**Steps to reproduce the issue:**

1. init swarm
2. add worker node
3. create the overlay network
4. add services attached to overlay network:

       docker service create --name swarm-listener \
        --network rh_overlay \
        --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
        -e DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure \
        -e DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove \
        --constraint 'node.role==manager' \
        vfarcic/docker-flow-swarm-listener

       docker service create --name proxy \
        -p 80:80 \
        -p 443:443 \
        --network rh_overlay \
        -e MODE=swarm \
        -e LISTENER_ADDRESS=swarm-listener \
        vfarcic/docker-flow-proxy

**Describe the results you received:**

Proxy service is unable to resolve the name *swarm-listener*:

> Fetching config from swarm listener failed: Get http://swarm-listener:8080/v1/docker-flow-swarm-listener/get-services: dial tcp: lookup swarm-listener on 127.0.0.11:53: no such host.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker version:

    Client:
    Version:      17.06.0-ce
    API version:  1.30
    Go version:   go1.8.3
    Git commit:   02c1d87
    Built:        Fri Jun 23 21:23:31 2017
    OS/Arch:      linux/amd64

    Server:
    Version:      17.06.0-ce
    API version:  1.30 (minimum version 1.12)
    Go version:   go1.8.3
    Git commit:   02c1d87
    Built:        Fri Jun 23 21:19:04 2017
    OS/Arch:      linux/amd64
    Experimental: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu Server 16.04

**Comment by vfarcic** [comment]
The good news is that the syntax for the commands you executed is correct. The bad news is that it worked in my cluster meaning that the problem is not directly related to DFP. The cause of the problem is probably in the firewall. 

From your comments on Slack, seems that swarm listener can communicate with the proxy. Can you check whether the same is true the other way around? Enter into the proxy container and execute:

```bash
apk add --update drill

drill swarm-listener
```

Please paste the output here. The IP should be 127.0.0.11.

**Comment by vfarcic** [comment]
I missed to notice the IP from the error message.

> Fetching config from swarm listener failed: Get http://swarm-listener:8080/v1/docker-flow-swarm-listener/get-services: dial tcp: lookup swarm-listener on 127.0.0.11:53: no such host.

`127.0.0.11:53` does not seem to be IP Docker network assigns to services. It seems as if something is hijacking requests. Can you double check that there is no VPN or another proxy somewhere inside your network? Also, the port `53` does not fit the picture.

**Comment by brunifrancesco** [comment]
It turned out you got it right. 
There was an issue with my set of open stack based VM. 
I needed to explicitly open ports without using a "pass all" firewall rule. 
Thanks for supporting me.

Francesco

**Comment by kmyn** [comment]
@brunifrancesco How did you resolve this issue? I'm running into the same issue as well.

Thanks,
Karthik

**Comment by brunifrancesco** [comment]
Are you encountering the issue in a Open Stack VM? 
I configured a **pass all rule** (all TCP/UDP ports were open) to let all the traffic passes through without any limitation. This op was the issue cause: when I explicitly open SWARM UDP/TCP ports and removed the pass all rule, it started working as expected.
Hope it solves your problem too, 

bye
Francesco

**Comment by alexsandro-xpt** [comment]
I'm using AWS with `Docker for AWS` solution, I haven't this problem. It's really bad :|

**Comment by vfarcic** [comment]
@alexsandro-xpt I'm not sure I understood. Are you NOT having that problem?

**Comment by vfarcic** [comment]
@kmyn I don't have an Open Stack cluster I can use to try it out myself. Generally, if ports are open (https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts) Docker networking should work and DFP as well. If networking is messed up, DFP cannot forward requests to your service. Actually, without networking set up, many other things will not work in a Swarm cluster.

**Comment by kmyn** [comment]
The one's I'm using are generic CentOS VM's. Same issue happened in two different setup and for both I had to recreate swarm and the overlay network again to resolve the problem.

**Comment by vfarcic** [comment]
Many are having problems running Docker Swarm cluster on CentOS/RedHat. Networking is often failing on those.

I don't think that the problem is related to DFP. I'd suggest using Ubuntu instead or one of the newer distributions made specifically for containers.
