### ISSUE TITLE
FR: changing redirect code when using httpsOnly

### ISSUE THREAD

**Issue by leostarcevic** [vfarcic/docker-flow-proxy#317]
When using httpsOnly, the http to https redirect will be a 302 redirect by default. I'd like to use 301 or 307 redirects as well. I'll make the necessary changes, how about we call this new param "httpsRedirectCode" ?

**Comment by vfarcic** [comment]
@leostarcevic Are you still interested in making a PR for this? There's no rush... Just wanted to check whether you're still up for it or I should write the code.

**Comment by leostarcevic** [comment]
@vfarcic Sure, I'll hopefully have some time this week :)
