### ISSUE TITLE
FR: new param to set any acl rule supported by haproxy

### ISSUE THREAD

**Issue by leostarcevic** [vfarcic/docker-flow-proxy#318]
I'd like to add a general param to set any ACL rule supported by HaProxy, I'll name this param "addCustomAcl" and make a PR.

**Comment by vfarcic** [comment]
@leostarcevic Do you need help with the PR?

**Comment by leostarcevic** [comment]
@vfarcic I forgot about this feature request, I'll try to look into it this week!

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
