### ISSUE TITLE
Swarm mode with consul doesn't remove from consul

### ISSUE THREAD

**Issue by mackeyja92** [vfarcic/docker-flow-proxy#32]
When running in swarm mode with consul for multiple replicas it doesn't seem to remove stuff from consul when remove services from proxy. I think allowing `distribute=true` on remove would solve that. 

This may be a bug in #26.

**Comment by vfarcic** [comment]
Distribute option has been added to the remove command in the release 1.87. Please reopen this issue if you experience any problems.
