### ISSUE TITLE
Detailed LOG in DFP

### ISSUE THREAD

**Issue by wyxgit** [vfarcic/docker-flow-proxy#321]
I need verbose LOG (with connection informations, client IPs, so on) in DFP.
What is the way to configure it?

**Comment by vfarcic** [comment]
Did you try environment variables `DEBUG`, `DEBUG_ERRORS_ONLY`, `DEBUG_HTTP_FORMAT`, and `DEBUG_TCP_FORMAT`? They are described in the [Environment Variables](http://proxy.dockerflow.com/config/#environment-variables) section of the documentation.

**Comment by vfarcic** [comment]
Closing the issue since it became inactive. Feel free to reopen it if you'd like to continue the conversation.
