### ISSUE TITLE
Provide a way to setup a separate frontend for proxy stats

### ISSUE THREAD

**Issue by je-al** [vfarcic/docker-flow-proxy#324]
Hi, I'm testing the proxy behind a proxy-protocol enabled LB (AWS ELB) and ran into an issue. Since the `stats` configuration is setup in the `default` frontend, scrapers of it would need to support using proxy-protocol when communicating to it. I don't think this is very common or easy to do. So It'd be nice if the possibility of defining a separate frontend (basically another port) which contained only the stats endpoint would be a nice addition. "Bonus points" if the default haproxy-exporter configuration reacted properly.

**Comment by vfarcic** [comment]
The implementation passed automated tests but I did not have time to try it out on a functional level. Can you please give me a hand and test the tag `beta` and report back whether it works as expected? You'll need to define environment variable `STATS_PORT`.

**Comment by je-al** [comment]
You seem to have missed a blank line there somewhere: ```
backend stats
    mode http
    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats uri /proxyStats
    stats auth admin:admin
frontend services
    bind *:80 accept-proxy
```

```
haproxy_server_weight{backend="webs_www-be80_0",server="webs_www"} 1
```
but otherwise, it looks fine.

**Comment by vfarcic** [comment]
Empty lines between frontends and backends is mostly for cosmetic reasons. HAProxy ignores them. I put to my backlog the change to separate them further.

I made a release `17.09.06-7` with the changes required for this FR. Please reopen this issue if you experience any problems.
