### ISSUE TITLE
Securing the :8080 config?

### ISSUE THREAD

**Issue by ascora** [vfarcic/docker-flow-proxy#33]
In the new docker 1.12 swarm mode example of Docker-Flow:Proxy, the 
/v1/docker-flow-proxy/reconfigure
seems to be published to :8080 for all external IPs. Doesn't that mean that anyone will be able to modify the config?

What is the best way to secure it?

**Comment by vfarcic** [comment]
That depends on your firewall policy. Normally you should allow external traffic only through ports 80 and 443 (and 22 to SSH). In such a case, you would be able to reconfigure the proxy only if you are inside your own network.

**Comment by ascora** [comment]
Just as an idea: Wouldn't it be possible/better to not publish the port 8080 at all and to only access the management REST interface via an own container, which is also part of the "proxy" overlay network?

**Comment by vfarcic** [comment]
Yes. You can do that. The example service command would be:

```
docker service create --name proxy \
    -p 80:80 \
    -p 443:443 \
    --network proxy \
    -e MODE=swarm \
    vfarcic/docker-flow-proxy
```

Please note that 8080 is not exposed.

Then you would run a container inside the same network and make a request. It would be something like:

```
docker service create --name request-to-proxy \
```
