### ISSUE TITLE
HEALTHCHECK

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/docker-flow-proxy#336]
**Description**

Create a HEALTHCHECK that will verify that both `docker-flow-proxy` and `haproxy` are up and running.

**Steps to reproduce the issue:**
1. Stop the haproxy process

**Describe the results you received:**

Containers are still running

**Describe the results you expected:**

Containers should be rescheduled.

**Additional information you deem important (e.g. issue happens only occasionally):**

None

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Any

**Comment by johnjelinek** [comment]
might be also nice to be able to have reconfigure/reload docker-flow-proxy on service health checks too (think swarm health checks could help here?).

**Comment by vfarcic** [comment]
I already added `HEALTHCHECK` to the image but forgot to close this issue. Can you please try one of the newer releases. Feel free to reopen this issue if it does not work as expected.
