### ISSUE TITLE
Feature request: domain redirection

### ISSUE THREAD

**Issue by siedentm** [vfarcic/docker-flow-proxy#340]
It would be awesome to get domain redirection specified in labels.

an suggestion for this would be:
```
labels:
  - 'com.df.notify=true'
  - 'com.df.receiveServiceDomains=domain1 domain2 domain3'
```

That eliminates the need of defining it with the template and haproxy does support domain redirection and redirections from [nothing]domain.com to www.domain.com should be occuring rather often.

**Comment by vfarcic** [comment]
A new parameter `redirectFromDomain` was added. The new feature is available from the [release 17.09.30-32](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17.09.30-32). Please try it out and let me know if it works as expected.

**Comment by siedentm** [comment]
i'll try it this evening (~4-5 hours).

**Comment by siedentm** [comment]
@vfarcic i tested it yesterday and it went into deployment today. works flawlessly
