### ISSUE TITLE
Feature Request > IP restriction

### ISSUE THREAD

**Issue by remy-tiitre** [vfarcic/docker-flow-proxy#348]
I don't think there is an option to close down one service to a certain ip range. Sure I can do it with custom templates and as global rules they are fine. Doing it service by service is cumbersome.. At least I didn't notice any acl network_allowed or white_list options. Someone might correct me if I'm wrong.

**Comment by vfarcic** [comment]
That would be difficult to accomplish with Overlay network. When a request enters a cluster, it is forwarded (through Overlay) to a service (in this case DFP). The moment it gets to Overlay it loses IP of the request that initiated it. There are a couple of issues open in Docker but, as far as I know, there is no solution yet.

**Comment by leostarcevic** [comment]
There is a workaround to this issue posted in:
https://github.com/moby/moby/issues/25526

It won't use overlay networking though, the ports will be opened on the host itself.

```docker service update nginx_proxy \
	--publish-rm 80 \
	--publish-add "mode=host,published=80,target=80" \
	--publish-rm 443 \
	--publish-add "mode=host,published=443,target=443"
```

**Comment by vfarcic** [comment]
I don't think that's an acceptable workaround. It skip ingress network. That would mean that requests can enter only through nodes hosting the proxy. If that's OK, publishing it on host should work but, in that case, you'd need to constraint the proxy to run only on specific hosts. That would create problems with fault tollerance and quite a few other things.

**Comment by vfarcic** [comment]
Closing the issue due to inability to capture IP with Overlay network
