### ISSUE TITLE
ip:port/service/url to service:port/url

### ISSUE THREAD

**Issue by velislav** [vfarcic/docker-flow-proxy#349]
Is there a way to use the following setup:
swarm_host_ip:port/service1/URI --> service1:port/URI

In my current setup I have:
`version: "3.3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  service1:
    image: service1
    ports:
      - 8180:8180
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/service1
        - com.df.port=8180
    networks:
      - proxy

networks:
  proxy:
    external: true`

Test:
curl http://example.com/service1/admin/v1/accountgroups

Result:
No mapping found for HTTP request with URI [/service1/admin/v1/accountgroups]

Can the proxy hit URI [/admin/v1/accountgroups] instead of URI [/service1/admin/v1/accountgroups] ?

Is there a way to use the following setup:
swarm_host_ip:port/service1/URI --> service1:port/URI

In my current setup I have:
`version: "3.3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  service1:
    image: service1
    ports:
      - 8180:8180
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/service1
        - com.df.port=8180
    networks:
      - proxy

networks:
  proxy:
    external: true`

Test:
curl http://example.com/service1/admin/v1/accountgroups

Result:
No mapping found for HTTP request with URI [/service1/admin/v1/accountgroups]

Can the proxy hit URI [/admin/v1/accountgroups] instead of URI [/service1/admin/v1/accountgroups] ?

**Comment by vfarcic** [comment]
You can add `com.df.reqPathSearch=/service1` label. The proxy will replace matching parts of requests paths with the value of `com.df.reqPathReplace` or with an empty string if it's not present. Please try it out and let me know if it works as expected.

One thing you should be aware of is that, in case it is a front-end client, paths must be relative.

**Comment by velislav** [comment]
Thanks, com.df.reqPathSearch=/service1 label solved the problem.
