### ISSUE TITLE
Lets Encrypt support

### ISSUE THREAD

**Issue by aleskinen** [vfarcic/docker-flow-proxy#350]
Is it possible to have Lets enrypt support added?

**Comment by hamburml** [comment]
Hello aleskinen,

you can use Docker Flow: Lets Encrypt which is a companion-service to DFP.
https://github.com/hamburml/docker-flow-letsencrypt/

Cheers
Michael

**Comment by vfarcic** [comment]
@aleskinen Please let me know if you have any other question or we can close this issue.
