### ISSUE TITLE
[NFR] Strict Transport Security (HSTS)

### ISSUE THREAD

**Issue by ruudboon** [vfarcic/docker-flow-proxy#353]
Thnx, for this project! Really helpful.
Would it be possible to support Strict Transport Security (HSTS) when using ssl?
And maybe SSL Stapling to reduce the ssl overhead?

**Comment by vfarcic** [comment]
You can use `setReqHeader` parameter to add the header you need (more info is in http://proxy.dockerflow.com/usage/#general-query-parameters).  It would be something like:

```
...
  deploy:
    labels:
      - com.df.setReqHeader=Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
     ...
```

Can you please try it out and let me know if it worked? If it didn't, please enter a node where one of the proxy containers/replicas is running, get the container ID, execute `docker container exec -it [PROXY_CONTAINER_ID] cat /cfg/haproxy.cfg`, and post it here. That would help me debug if there was a typo in the label value.

**Comment by ruudboon** [comment]
Looks like the header is not coming trough.

```
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    # disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

resolvers docker
    nameserver dns 127.0.0.11:53

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-keep-alive
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s


frontend services
    bind *:80
    bind *:443 ssl crt-list /cfg/crt-list.txt
    mode http

    acl url_system_letsencrypt-companion80_0 path_beg /.well-known/acme-challenge
    use_backend system_letsencrypt-companion-be80_0 if url_system_letsencrypt-companion80_0
    acl url_staging_nginx80_0 path_beg /
    acl domain_staging_nginx80_0 hdr(host) -i www.staging.devokozijnen.nl
    http-request redirect code 301 prefix http://www.staging.devokozijnen.nl if { hdr(host) -i staging.devokozijnen.nl }
    use_backend staging_nginx-be80_0 if url_staging_nginx80_0 domain_staging_nginx80_0







backend staging_nginx-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    http-request set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
    http-request redirect scheme https if !{ ssl_fc }
    server staging_nginx staging_nginx:80


backend system_letsencrypt-companion-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server system_letsencrypt-companion system_letsencrypt-companion:80
```

Tried to add it to my nginx conf also but looks like it's getting removed by the proxy.

**Comment by vfarcic** [comment]
The header is defined in the `staging_nginx-be80_0` backend. Do you mean that your nginx is not receiving it?

**Comment by ruudboon** [comment]
I don't see the headers in the reply of the proxy when accessing it from the browser.
I tried to add the headers to nginx also but they were also stripped from the reply.

**Comment by ruudboon** [comment]
@vfarcic Sure! Take your time.

**Comment by vfarcic** [comment]
I made a few of tests and did not experience a problem. Headers were propagated to destination services.

> I don't see the headers in the reply of the proxy when accessing it from the browser.

If you're expecting to see that header in the reply (not in request forwarded to the service), you should try with:

```
- com.df.setResHeader=Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
```

The change is in `Res` (short for response) instead `Req` (short for response).

**Comment by ruudboon** [comment]
Ah, that was it. I was looking for setResHeader. 
Working perfect now, A+ Score on SSL Labs now :D
