### ISSUE TITLE
[NFR] Http/2 support

### ISSUE THREAD

**Issue by ruudboon** [vfarcic/docker-flow-proxy#355]
Not sure if HAProxy is already supporting it. But when it comes in could you support Http/2?

**Comment by vfarcic** [comment]
It'll be available in HAProxy 1.8. They did not specify the date but only said that it's coming soon.

**Comment by natemurthy** [comment]
@vfarcic I saw that this was closed out https://github.com/vfarcic/docker-flow-proxy/issues/93

Is there maybe another place where I could track development progress on this? This could be possibly something to which I can contribute if there is a strong need :)

**Comment by vfarcic** [comment]
@natemurthy #93 was closed by the author of the issue. Now that HAProxy officially announced that H2 is available in 1.8 dev release, this subject should definitely be revisited. My idea is to develop the feature and test it against HAProxy 1.8 dev (for now) and start building Docker images based on 1.7 (stable) and 1.8 (dev) releases of HAProxy. That way, people can choose whether to have DFP with stable HAProxy but without H2 or the other way around. What do you think?

My major problem (at the moment) is that I don't have much free time (beyond all my other activities). Would you be interested in working on this feature?

**Comment by natemurthy** [comment]
How tied is DFP to HAProxy? As of nginx 1.9.5 (stable), http/2 is supported. But if HAProxy is the only option we can at least get a development version started.

I just recently began looking at this code, but I am interested in working on this feature :)

**Comment by vfarcic** [comment]
At the moment, DFP works only with HAProxy but it was written in a way that another proxy (e.g., nginx) can be plugged in. Probably >50% of work would be to make an nginx template equivalent to https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/template.go. Still, even though coding is not huge, testing nginx version would be massive. Time wise, I think that HAProxy dev. release would be a much shorter path.

I'm open to your suggestions which path you'd prefer.

**Comment by ruudboon** [comment]
I got some experience with Nginx, I wouldn't mind helping building the config and doing some testing.
But l agree with @vfarcic probally going with HAProxy will be much faster.

**Comment by vfarcic** [comment]
@ruudboon Would you like to help with a PR? There should be a separate Dockerfile for building an image based on HAProxy 1.8 dev and a few changes to DFP to allow H2 configs. Later can be tested by changing the config manually and sending a reload request. If it works, it should be fairly easy to add it as an additional label.

**Comment by vfarcic** [comment]
DFP with HAPRoxy 1.8 will be released soon. From there on, we can add the support for HTTP/2. Can someone help out by creating a service that can be used to test it?

**Comment by vfarcic** [comment]
HTTP/2 support was added in the [release 17.12.09-77](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17.12.09-77).
