### ISSUE TITLE
[NFR] Support ocsp stapling

### ISSUE THREAD

**Issue by ruudboon** [vfarcic/docker-flow-proxy#356]
OCSP stapling provides the client with the certificate status immediately and specifically, reducing the latency for the page load by avoiding a separate request to an OCSP service hosted by the issuing CA.  

HAProxy isn't retrieving the client certificate automatically like nginx is doing but there are some projects that could help with that.

https://github.com/pierky/haproxy-ocsp-stapling-updater

http://www.jinnko.org/2015/03/ocsp-stapling-with-haproxy.html

**Comment by ruudboon** [comment]
Looking at this now I'm wondering if I should submit this NFR to the https://github.com/hamburml/docker-flow-letsencrypt project

**Comment by vfarcic** [comment]
@ruudboon It would help a lot if you could figure out what is needed in HAProxy and try it out (enter into a DFP container, change the config, reload). What do you think? Is that an option?

**Comment by ruudboon** [comment]
@vfarcic I was already looking into this (and some other SSL performance optimalisations like ssl session caching) but I'm not that experienced with HAProxy and struggling to reload the config in the swarm. I'll let you if I can get it working.

**Comment by vfarcic** [comment]
Reloading is relatively easy. Find the ID of one of the DFP containers, enter into it (e.g., `docker container exec -it [CONTAINER_ID] sh`), edit the config (e.g., `vi /cfg/haproxy.cfg`), and reload (e.g., `curl localhost:8080/v1/docker-flow-proxy/reload`). I can check it (experiment) myself but I'm not sure I'll be able to find time before the weekend after next.

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
