### ISSUE TITLE
[NFR]  tcp-smart-connect

### ISSUE THREAD

**Issue by ruudboon** [vfarcic/docker-flow-proxy#357]
setting the option tcp-smart-connect directly send the data (ie: the proxy protocol header and request data) in the first packet. This ensures that the http backend has the request available immediately and saves it from having to poll for the data.
Could we add this option?
```
  option tcp-smart-connect
```

**Comment by vfarcic** [comment]
Would setting it as a value of `EXTRA_GLOBAL` env. var. do the trick?

**Comment by vfarcic** [comment]
Closing to due inactivity. Please let me know if you'd like to reopen the issue.
