### ISSUE TITLE
[NFR] tune.ssl.cachesize 

### ISSUE THREAD

**Issue by ruudboon** [vfarcic/docker-flow-proxy#358]
For SSL performance it would be nice to support global SSL session cache.
Could we enable the option
```
 tune.ssl.cachesize 
```

**Comment by vfarcic** [comment]
One option that comes out of the box is to use env. var. `EXTRA_GLOBAL` (more info in http://proxy.dockerflow.com/config/#environment-variables). It can be used to add any global setting (like `tune.ssl.cachesize`). Can you try it out?

Assuming that `EXTRA_GLOBAL` works, I'm wondering whether it would be a good idea to add this option (`cachesize`) as a separate parameter. On one hand, it is probably more convenient to set it up through an evn. var. like `TUNE_SSL_CACHESIZE`. On the other hand, the more options there are, the more confusing it might be to use DFP. What do you think?

**Comment by ruudboon** [comment]
Yeah this working. Thnx
If there comes more requests for this we could add it as a default param, I think for now this is fine.
