### ISSUE TITLE
Exposing port other than 80.

### ISSUE THREAD

**Issue by foleymic** [vfarcic/docker-flow-proxy#359]
**Description:**
I’m trying to run Docker Flow Proxy and expose some port other than 80, but not having any luck.  I’ve created a simple test compose file below:

**Steps to reproduce**
On a swarm cluster, deploy the following stack:
```
version: "3.2"

networks:
  backend:
    driver: overlay

services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - "5601:5601"
    networks:
      - backend
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      #- BIND_PORTS=5601
      - DEFAULT_PORTS=5601
      - DEBUG=true

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
  
  kibana:
    image: kibana
    networks:
      - backend
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=somedomain.com
        - com.df.port=5601
```

Add a host or DNS entry to point somedomain.com to your swarm.

Everything seems to start up fine, but I cannot access the service on port 90 (e.g. http://somedomain.com:5601).

**Comment by vfarcic** [comment]
Reproduced it... I'll fix it later today.

**Comment by vfarcic** [comment]
There was an error in documentation. You'll need to add:

```
- BIND_PORTS=90
```

... environment variable to the proxy.

That assumes that you will have services that should be accessible on the port `80`. If not, the change is even simpler. You can change:

```
      - 90:90
```

to

```
      - 90:80
```

If your services have unique identifiers (e.g. `serviceDomain` and/or `servicePath`), with the `BIND_PORTS` env. var. there's no need to specify `srcPort`.

Can you please let me know if this answered your questions and whether one of the suggestions worked?

**Comment by foleymic** [comment]
@vfarcic thanks for looking into this - Unfortunately, I'm still having no luck.  The haproxy.cfg looks correct, but I'm still getting 503 response.  I also turned on debug mode and see that it's not finding a service for the request
```
test_proxy.1.x7jiebktjmko@moby    | 2017/11/01 19:37:02 HAPRoxy: 10.255.0.2:45098 [01/Nov/2017:19:37:02.156] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 2/2/0/0/0 0/0 "GET / HTTP/1.1"
test_proxy.1.x7jiebktjmko@moby    | 2017/11/01 19:37:02 HAPRoxy: 10.255.0.2:45100 [01/Nov/2017:19:37:02.481] services services/<NOSRV> -1/-1/-1/-1/0 503 1271 - - SC-- 1/1/0/0/0 0/0 "GET /favicon.ico HTTP/1.1"
```

**Comment by vfarcic** [comment]
Can you post your updated stack YML file?

**Comment by foleymic** [comment]
I updated the yml in the description above.   Note that I've also tried changing the port mapping to 5601:80 and removing the DEFAULT_PORTS and BIND_PORTS but results are the same.  Here is the  frontend and backend sections of the generated haproxy.cfg:

```
frontend services
    bind *:5601
    mode http

    option httplog
    log global
    acl url_test_kibana5601_0 path_beg /
    acl domain_test_kibana5601_0 hdr(host) -i somedomain.com
    use_backend test_kibana-be5601_0 if url_test_kibana5601_0 domain_test_kibana5601_0

backend test_kibana-be5601_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    log global
    server test_kibana test_kibana:5601
```

**Comment by vfarcic** [comment]
Sorry... I didn't explain myself well. Can you send me the YML files with the definition of your services (proxy, listener, ...)? I'd like to replicate the same as what you have so that I can see where is the error.

**Comment by foleymic** [comment]
[test.yml.zip](https://github.com/vfarcic/docker-flow-proxy/files/1435535/test.yml.zip)
I put the contents of the yml in the description above, but here is the actual file I'm using.

**Comment by vfarcic** [comment]
I just rerun the same stack and, once all the services were running, executed `curl -i -H "Host: somedomain.com" "http://localhost:5601"`. The output is:

```
HTTP/1.1 200 OK
kbn-name: kibana
kbn-version: 5.6.3
cache-control: no-cache
content-type: text/html; charset=utf-8
content-length: 217
accept-ranges: bytes
Date: Wed, 01 Nov 2017 20:21:27 GMT

<script>var hashRoute = '/app/kibana';
var defaultRoute = '/app/kibana';

var hash = window.location.hash;
if (hash.length) {
  window.location = hashRoute + hash;
} else {
  window.location = defaultRoute;
}</script>%
```

The config from my instance of the proxy is exactly the same as in your case so the problem is not that, in my case, DFP did something different.

Is it possible that something is blocking the port `5601`?

**Comment by foleymic** [comment]
Hum, it's not something blocking the port - if I remove the proxy and add the port mapping to the Kibana service, it works.  But given that it works for you, it must be something with my environment.  I'll try on another VM when I get home in about an hour.  Thanks again for looking at it.

**Comment by vfarcic** [comment]
Maybe we can have a screen-sharing session and go through it together? How about tomorrow around this same time? Would that suit you?

**Comment by foleymic** [comment]
@vfarcic - I think I found the problem.  It does work with curl command where you specify the Host value (I don't know why it wasn't working for me yesterday, but it does work now).  It fails when you try with the browser because the Host includes the port (see below).  If I manually change the haproxy acl to include the port `acl domain_test hdr(host) -i somedomain.com:5601` it works from the browser as well.  

We can't have DFP add the port to the acl because that will the the published port and is not anything DFP knows (without adding a new variable, which would not be ideal).  Instead, if we change the generated ACL to use hdr_beg instead of hdr, it will work.  For example, `acl domain_test hdr_beg(host) -i somedomain.com`.  If that sounds like the right approach, I can submit a PR.

![image](https://user-images.githubusercontent.com/6004328/32326763-66051cf2-bfaa-11e7-8782-f87267536f48.png)

**Comment by foleymic** [comment]
Now that I've looked at the code, I can see that a PR isn't needed.  You already externalized the ACL rule via as **SERVICE_DOMAIN_ALGO**.  Thanks!.  Just adding `SERVICE_DOMAIN_ALGO=hdr_beg(host)` works.  Let me know if you think it makes sense to change the default to hdr_beg, or maybe just call it out in the documentation if using a published ports other than 80 or 443.

**Comment by vfarcic** [comment]
I think that the right approach would be to use `hdr_beg` if `serviceDomainAlgo` is NOT specified and `srcPort` is set to value other than `80` or `443`. What do you think? Would you like to make a PR?

**Comment by foleymic** [comment]
I agree on the first part, using hdr_beg if serviceDomainAlgo not specified, but not sure on the second.  Because I'm using serviceDomain, I'm not specifying srcPort at all.  If I did use srcPort, would that be the published port?  For example, if my compose file had:
```
    ports:
       - 90:5601
```
Would I set srcPort to 5601 or 90?  Either way, I'll be glad to submit a PR later today.

**Comment by vfarcic** [comment]
You're right. Let's go with `hdr_beg(host)` as default value instead of `hdr(host)`. I think that it would be enough to change `SERVICE_DOMAIN_ALGO` in Dockerfile. It's a very simple change but it would require a bit of testing to make sure that nothing is broken. I'll wait for a PR unless you tell me otherwise.

**Comment by vfarcic** [comment]
I think this issue can be closed with that merge. Can you please confirm that now it works as expected?

**Comment by b2az** [comment]
Hi @vfarcic - 
I found this issue, is it possible to map a portrange?
Currently i'm using one instance of haproxy-service and maximum 10 of the logstash-service:

frontend fe_logstash
    bind *:10000-10100
    default_backend be_logstash_service

backend be_logstash_service
    balance roundrobin
    server-template logstash- 10 logstash-service check port 10000 resolvers docker init-addr libc,none

The idea is too connect 100 different datasources from outside world to the internal service.

**Comment by vfarcic** [comment]
@b2az Unfortunately, all the development of this project stopped. Almost everyone moved from Swarm to Kubernetes so it didn't make sense to continue working on this project. I strongly suggest you switch to Kubernetes as well. Even Docker company is not working on Swarm for a long time now.
