### ISSUE TITLE
Validation Error, can't see error

### ISSUE THREAD

**Issue by kungfu71186** [vfarcic/docker-flow-proxy#364]
Ran into an issue where I could see validation wasn't passing, but did not see the error haproxy gave.

Basically getting the output of haproxy -f haproxy.cfg

This lead me to believe I was getting the wrong error. It would be helpful to see the haproxy error as well.

**Comment by vfarcic** [comment]
I created `issue-364`. Can you do a pull request against it?

P.S. Sorry for not doing that earlier.

**Comment by vfarcic** [comment]
@kungfu71186 Can you take a look at https://github.com/vfarcic/docker-flow-proxy/commit/81a58ddf07f334f6df8dbcb0a0e315ac374454a8 . I added a few tests and removed paths that cannot be tested with the assumption that those errors will not occur in a controlled environment like containers. Your solution is more robust. On the other hand, I prefer testable simplicity.

What do you think? Should we merge with this commit, revert to your commit, or something else?
