### ISSUE TITLE
Problem with adding external no-swarm  service

### ISSUE THREAD

**Issue by yarmorell** [vfarcic/docker-flow-proxy#368]
Hello,

I want to use DFP instead Nginx, but i have faced the problem with adding non-swarm service to my configuration.
Now I am using Nginx as reverse proxy with config:

`
server {
    listen 443;
    server_tokens  off;
    ssl on;
    ssl_certificate    /etc/nginx/ssl/cert.crt;
    ssl_certificate_key    /etc/nginx/ssl/cert.key;
    server_name servername;
    error_page 500 502 503 504 /error.html;
    set_real_ip_from 10.0.0.0/8;
    real_ip_header X-Real-IP;
    real_ip_recursive on;
    rewrite ^/(pulse|components)$ $1/ permanent;

location ~* ^/pulse(/.*) {
  set $pulse http://pulse_pulse:3060;
  proxy_pass $pulse$1$is_args$args;
}

location ~* ^/components(/.*) {
  set $component https://dev-components.test.io;
  proxy_pass $component$1$is_args$args;
  proxy_set_header realm realmname;
}

}
`
I have tried to create configuration according to the article "Configuring Non-Swarm Services":
`
version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - DEBUG=true
      - EXTRA_FRONTEND=acl is_root path -i /,acl missing_slash path_reg ^/*/[^/]*$$,http-request redirect code 301 prefix / append-slash if missing_slash !is_root
      - DFP_SERVICE_1_SERVICE_NAME=dev-components.test.io
      - DFP_SERVICE_1_SERVICE_PATH=/components
      - DFP_SERVICE_1_OUTBOUND_HOSTNAME=dev-components.test.io
      - DFP_SERVICE_1_PORT=443
      - DFP_SERVICE_1_REQ_PATH_REPLACE=/components
      - DFP_SERVICE_1_REQ_PATH_SEARCH=/
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
`
Could you please suggest any DFP configuration for external https hosts?  
I'd appreciate it if you'd help me.

**Comment by vfarcic** [comment]
In general, DFP is designed to forward requests to Swarm services even though it can be used with others as well. You can send a [reconfigure request](http://proxy.dockerflow.com/usage/#reconfigure) to DFP and, among others, use `outboundHostname`. Please try it out and let me know if it worked as expected.

**Comment by yarmorell** [comment]
Thank you for your answer.
I have found the problem with connecting to my service and changed config like that:

- DFP_SERVICE_1_SERVICE_DOMAIN=test-dfp.service.io
- DFP_SERVICE_1_SERVICE_NAME=components-new.service`.io
- DFP_SERVICE_1_SERVICE_PATH=/components
- DFP_SERVICE_1_OUTBOUND_HOSTNAME=components-new.service.io
- DFP_SERVICE_1_PORT=443
- DFP_SERVICE_1_REQ_PATH_SEARCH=/components/
- DFP_SERVICE_1_REQ_PATH_REPLACE=/
- DFP_SERVICE_1_HTTPS_ONLY=true
- DFP_SERVICE_1_SSL_VERIFY_NONE=true
- DFP_SERVICE_1_ADD_REQ_HEADER=realm ${REALM}
- DFP_SERVICE_1_SET_REQ_HEADER=Host components-new.service.io,realm ${REALM}

How can I change backend name for this service? 
I am using keycloak and I need to change header "realm" for different service domains.
When I have created proxy stack, backend has name: backend components-new.ewizard.io-be443_0, but when I tried to add another service, the proxy has shown error.
New service had the same name as the previous external service.

**Comment by vfarcic** [comment]
At the moment, DFP assumes that the name of the service is unique since Swarm would not allow you to deploy services with the same name. I did not foresee that an external service could be name the same as internal (Swarm) service. I can change the template so that `aclName` is used instead. It defaults to `serviceName`. In other words, if you specify `aclName` (it can be anything), you'll be able to change the name of the backend. Do you think that would work for you?

**Comment by yarmorell** [comment]
Yes. It would be a great solution to solve this problem.
I will be very grateful.

**Comment by vfarcic** [comment]
I'm a bit tight with time. Is it urgent or it's OK if I do it over the weekend?

**Comment by yarmorell** [comment]
I am currently adding one more proxy server for each service instance to avoid this issue.
If you change the configuration on next weekend or next week I will be very grateful.

**Comment by vfarcic** [comment]
I promised I'll do it over this weekend but I could not find free time. I'll have to postpone this fix for a week.

**Comment by yarmorell** [comment]
Thank you for info. 
Currently, it is not the urgent case for me. I will wait for this fix during next week. 
Have a nice week.

**Comment by vfarcic** [comment]
I forgot to comment that the issue is fixed. Can you please try out the latest release?

**Comment by yarmorell** [comment]
I had seen your fix, thank you very much for your help. 
I will test my config on next week and inform you.

**Comment by yarmorell** [comment]
Hello,

I have added to DFP config:

```
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - DEBUG=true
      - EXTRA_FRONTEND=acl is_root path -i /,acl missing_slash path_reg ^/*/[^/]*$$,http-request redirect code 301 prefix / append-slash if missing_slash !is_root

      - DFP_SERVICE_1_ACL_NAME=shared-cloud-one.mydomain.io
      - DFP_SERVICE_1_SERVICE_DOMAIN=shared-cloud-one.mydomain.io
      - DFP_SERVICE_1_SERVICE_NAME=components-new.mydomain.io
      - DFP_SERVICE_1_SERVICE_PATH=/components
      - DFP_SERVICE_1_OUTBOUND_HOSTNAME=components-.mydomain.io
      - DFP_SERVICE_1_PORT=443
      - DFP_SERVICE_1_REQ_PATH_SEARCH=/components/
      - DFP_SERVICE_1_REQ_PATH_REPLACE=/
      - DFP_SERVICE_1_HTTPS_ONLY=true
      - DFP_SERVICE_1_SSL_VERIFY_NONE=true
      - DFP_SERVICE_1_ADD_REQ_HEADER=realm shared-cloud-one
      - DFP_SERVICE_1_SET_REQ_HEADER=Host components-new.mydomain.io

      - DFP_SERVICE_2_ACL_NAME=shared-cloud-two.mydomain.io
      - DFP_SERVICE_2_SERVICE_DOMAIN=shared-cloud-two.mydomain.io
      - DFP_SERVICE_2_SERVICE_NAME=components-new.mydomain.io
      - DFP_SERVICE_2_SERVICE_PATH=/components
      - DFP_SERVICE_2_OUTBOUND_HOSTNAME=components-new.mydomain.io
      - DFP_SERVICE_2_PORT=443
      - DFP_SERVICE_2_REQ_PATH_SEARCH=/components/
      - DFP_SERVICE_2_REQ_PATH_REPLACE=/
      - DFP_SERVICE_2_HTTPS_ONLY=true
      - DFP_SERVICE_2_SSL_VERIFY_NONE=true
      - DFP_SERVICE_2_ADD_REQ_HEADER=realm shared-cloud-one
      - DFP_SERVICE_2_SET_REQ_HEADER=Host components-new.mydomain.io

    deploy:
      replicas: 4
  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
```

But it has created the configuration for proxy without ACL rules:

```
frontend services
    bind *:80
    bind *:443 ssl crt-list /cfg/crt-list.txt alpn h2,http/1.1
    mode http
    http-request set-var(req.scheme) str(https) if { ssl_fc }
    http-request set-var(req.scheme) str(http) if ! { ssl_fc }
    acl is_root path -i /
    acl missing_slash path_reg ^/*/[^/]*$
    http-request redirect code 301 prefix / append-slash if missing_slash !is_root
    option httplog
    log global
    acl url_shared-cloud-two.mydomain.io443_0 path_beg /components
    acl domain_shared-cloud-two.mydomain.io443_0 hdr_beg(host) -i shared-cloud-two.mydomain.io
    use_backend shared-cloud-two.mydomain.io-be443_0 if url_shared-cloud-two.mydomain.io443_0 domain_shared-cloud-two.mydomain.io443_0

backend shared-cloud-one.mydomain.io-be443_0
    mode http
    http-request redirect scheme https if !{ ssl_fc }
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    log global
    http-request add-header realm shared-cloud-one
    http-request set-header Host components-new.mydomain.io
    server components-new.mydomain.io components-new.mydomain.io:443 ssl verify none


backend shared-cloud-two.mydomain.io-be443_0
    mode http
    http-request redirect scheme https if !{ ssl_fc }
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    log global
    http-request add-header realm shared-cloud-one
    http-request set-header Host components-new.mydomain.io
    server components-new.mydomain.io components-new.mydomain.io:443 ssl verify noner
```
Can you please this case? I'll be very grateful!

**Comment by vfarcic** [comment]
The problem is with `DFP_SERVICE_*_SERVICE_NAME`. That's a unique identifier of a service. If two are the same, one will overwrite the other. If you change of the two, your setup should work.
