### ISSUE TITLE
Swarm Mode Port Binding Issue

### ISSUE THREAD

**Issue by turhn** [vfarcic/docker-flow-proxy#37]
Hello, I have the following swarm cluster.

```bash
root@swarm-master:~# docker node ls
ID                           HOSTNAME      STATUS  AVAILABILITY  MANAGER STATUS
0f6v0c2k9xlya9jt7sq64qsqc    swarm-node-1  Ready   Active
3xdm0erdn3g92xaypn5xodbtr    swarm-node-2  Ready   Active
a4t8gkg7tn0g7c64c8di38yml *  swarm-master  Ready   Active        Leader
```

And IP address of the master is 192.168.33.10, the nodes' are 192.168.33.11, 192.168.33.12.

Docker version:

```bash
root@swarm-master:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

In all hosts and the development machine, I have:

/etc/hosts
```
192.168.33.10 dockerhost.local
192.168.33.10 test.voucherreseller.local
```

I create my services with the following:

```bash
docker network create --driver overlay proxy
docker network create --driver overlay test_apps

docker service create \
  --name test_voucherreseller \
  --replicas 3 \
  -p 8024:8024 \
  -e ENVIRONMENT=Test \
  --network proxy \
  --network test_apps \
  dockerhost.local:5000/voucherreseller:latest

docker service create \
  --name proxy \
  --replicas 3 \
  -p 80:80 \
  -p 443:443 \
  -p 8080:8090 \
  --network proxy \
  -e MODE=swarm \
  vfarcic/docker-flow-proxy

```

Service situation is:

```bash
root@swarm-master:~# docker service ls
ID            NAME                  REPLICAS  IMAGE                                         COMMAND
c6ijt0tg63d5  test_voucherreseller  3/3       dockerhost.local:5000/voucherreseller:latest
cx21upf3a7bh  proxy                 3/3       vfarcic/docker-flow-proxy
```

I can access _test_voucherreseller_ service by simply visiting http://192.168.33.10:8024 only if a process running on swarm-master host. I am not sure if this is a bug in swarm mode or I just misunderstood stuff: In my understanding of Docker swarm mode, I could just visit swarm master's IP with a port and see the app is running there. Unfortunately, if a process that belongs to _test_voucherreseller_ or any other service does not have a process running on swarm master, I cannot access it. But if nodes have at least one running process of the service, I can access them by http://192.168.33.11:8024 and http://192.168.33.12:8024. I know this is irrelevant to docker-flow-proxy but I wanted to mention that in order to make sure this has no effect on my issue.

```bash
root@swarm-master:~# docker ps -a
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS                        PORTS                                                                                                                            NAMES
765136306f27        vfarcic/docker-flow-proxy:latest               "/docker-entrypoint.s"   24 minutes ago      Up 24 minutes                 80/tcp, 443/tcp, 8080/tcp                                                                                                        proxy.3.9rrkek94w2ysz4of4pvawljwr
acc8a34383c2        dockerhost.local:5000/voucherreseller:latest   "/bin/sh -c 'python r"   24 minutes ago      Up 24 minutes                 8024/tcp                                                                                                                         test_voucherreseller.2.8biu0b7r2jli2yw79qlmp1fjl
```

I bound docker-flow-proxy's 8080 to 8090 because a Jenkins container is running on port 8080.

Here is the strange part:

```bash
root@swarm-master:~# docker service ps proxy
ID                         NAME     IMAGE                      NODE          DESIRED STATE  CURRENT STATE           ERROR
ejoqto2id5kqt5d1t88zbghj6  proxy.1  vfarcic/docker-flow-proxy  swarm-node-2  Running        Running 30 minutes ago
4v95tce1s3dta9sldaco42iyu  proxy.2  vfarcic/docker-flow-proxy  swarm-node-1  Running        Running 30 minutes ago
9rrkek94w2ysz4of4pvawljwr  proxy.3  vfarcic/docker-flow-proxy  swarm-master  Running        Running 30 minutes ago
```

According to that table, I expect that 80, 443, 8090 ports should be bound to swarm-master. Then I want to run http://192.168.33.10:8090/v1/docker-flow-proxy/reconfigure?serviceName=test_voucherreseller&serviceDomain=test.voucherreseller.local&servicePath=/&port=8024&distribute=true to configure my proxy but 8090 port is not bound. (I stopped Jenkins at 8080 and started docker-flow-proxy with 8080 and the situation is still the same)

When I tested the bound ports with netcat, I realised that they are not bound properly.

Strange table is like the following:

```bash
root@swarm-master:~# nc -vz 192.168.33.10 80
nc: connect to 192.168.33.10 port 80 (tcp) failed: Connection refused
root@swarm-master:~# nc -vz 192.168.33.10 443
nc: connect to 192.168.33.10 port 443 (tcp) failed: Connection refused
root@swarm-master:~# nc -vz 192.168.33.10 8090
nc: connect to 192.168.33.10 port 8090 (tcp) failed: Connection refused
root@swarm-master:~# nc -vz 192.168.33.11 80
Connection to 192.168.33.11 80 port [tcp/http] succeeded!
root@swarm-master:~# nc -vz 192.168.33.11 443
Connection to 192.168.33.11 443 port [tcp/https] succeeded!
root@swarm-master:~# nc -vz 192.168.33.11 8090
nc: connect to 192.168.33.11 port 8090 (tcp) failed: Connection refused
root@swarm-master:~# nc -vz 192.168.33.12 80
Connection to 192.168.33.12 80 port [tcp/http] succeeded!
root@swarm-master:~# nc -vz 192.168.33.12 443
Connection to 192.168.33.12 443 port [tcp/https] succeeded!
root@swarm-master:~# nc -vz 192.168.33.12 8090
nc: connect to 192.168.33.12 port 8090 (tcp) failed: Connection refused
root@swarm-master:~# nc -vz 192.168.33.10 8024
nc: connect to 192.168.33.10 port 8024 (tcp) failed: Connection refused
root@swarm-master:~# nc -vz 192.168.33.11 8024
Connection to 192.168.33.11 8024 port [tcp/*] succeeded!
root@swarm-master:~# nc -vz 192.168.33.12 8024
Connection to 192.168.33.12 8024 port [tcp/*] succeeded!
```

I little bit stuck because I am sure if I am dealing with a Swarm bug, docker-flow-proxy bug or just I misconfigured something.

Thank you.

**Comment by vfarcic** [comment]
My best guess, with the info you sent me, is that Swarm nodes cannot communicate with each other. As a result, ingress network does not work. It should accept a request from any node and forward it to one of the instances of the service that has the same port exposed. From what I understood, in your case, it works only if the service is running on the same node where the request is sent.

Can you let me know which hosting are you using (on-premise, AWS, Azure, ...) and whether there is a firewall blocking some ports?

**Comment by turhn** [comment]
It is Vagrant-VirtualBox environment configured with private network. There is no firewall configured. I can access from any node to other nodes like:

```
ubuntu@swarm-node-1:~$ docker -H 192.168.33.10 ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                                                                                                                            NAMES
765136306f27        vfarcic/docker-flow-proxy:latest               "/docker-entrypoint.s"   55 minutes ago      Up 55 minutes       80/tcp, 443/tcp, 8080/tcp                                                                                                        proxy.3.9rrkek94w2ysz4of4pvawljwr
acc8a34383c2        dockerhost.local:5000/voucherreseller:latest   "/bin/sh -c 'python r"   55 minutes ago      Up 55 minutes       8024/tcp                                                                                                                         test_voucherreseller.2.8biu0b7r2jli2yw79qlmp1fjl
```

```
root@swarm-master:~# docker -H 192.168.33.11 ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                       NAMES
efd1a950db40        vfarcic/docker-flow-proxy:latest               "/docker-entrypoint.s"   54 minutes ago      Up 54 minutes       80/tcp, 443/tcp, 8080/tcp   proxy.2.4v95tce1s3dta9sldaco42iyu
f53848742cc9        dockerhost.local:5000/voucherreseller:latest   "/bin/sh -c 'python r"   54 minutes ago      Up 54 minutes       8024/tcp                    test_voucherreseller.1.6ml6ev3kqneyddkqgj2vj3ibk
root@swarm-master:~# docker -H 192.168.33.12 ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                       NAMES
baec6c274475        vfarcic/docker-flow-proxy:latest               "/docker-entrypoint.s"   55 minutes ago      Up 55 minutes       80/tcp, 443/tcp, 8080/tcp   proxy.1.ejoqto2id5kqt5d1t88zbghj6
e305c6de5038        dockerhost.local:5000/voucherreseller:latest   "/bin/sh -c 'python r"   55 minutes ago      Up 55 minutes       8024/tcp                    test_voucherreseller.3.4jwrorn8wareofwifjoigzlq8
```
```
root@swarm-master:~# docker -H 192.168.33.11 logs efd1a950db40
2016/09/01 16:53:20 Starting HAProxy
2016/09/01 16:53:20 Starting "Docker Flow: Proxy"
```

**Comment by vfarcic** [comment]
Can you send me your Vagrantfile and the commands you used to install Docker and create a Swarm cluster? From there on, I'll try to reproduce it on my laptop.

**Comment by turhn** [comment]
Hi Victor, I published my cluster at https://github.com/turhn/swarm-cluster . It has server specs, Vagrantfile, and Ansible playbooks. Thus you can easily reproduce the same environment.

Thank you very much.

**Comment by vfarcic** [comment]
I could not create the VMs on my MacBook. Xenial64 is known not to work in all situations. On top of that, there seems to be a problem in your Ansible scripts. My guess is that it's related to encoding issues.

Anyways, I noticed that you initialize Swarm with:
```yml
docker swarm init --advertise-addr {{ inventory_hostname }}
```

`inventory_hostname` resolves to the hostname which, in turn, resolves to 127.0.0.1. If I'm right, that would prevent some of the Swarm communication paths from working. Can you change it to the IP of the server?

Similarly, change the inventoty_hostname to the IP of the server in:

```yml
docker swarm join --advertise-addr {{ inventory_hostname }}:{{ swarm_master_port }} --token {{ token }} {{ swarm_master_ip }}
```

As a side note, you don't need to specify port unless you change the default value.


Can you please try this and let me know whether anything changed. The simplest test would be to run any service inside the cluster and send a request through one of the nodes (excluding the node the service is running). If that works, your problem is probably solved.

**Comment by vfarcic** [comment]
First of all, I'm glad we managed to fix the main problem.

I think that you mixed up the ports. If you define ports as 8080:8090, that means that the service running inside a container is listening on 8090 and that 8080 will be exposed to the outside world. My guess is that you want the other way around: the process inside the container listens to 8080 and 8090 should be exposed to the outside world. If that's the case, can you please change it to `8090:8080` and let me know if it worked?

**Comment by turhn** [comment]
Thanks! That problem is also solved! The main problem seems that I am new to Docker and trying to learn all at once. I am very glad you spend your time for me.
