### ISSUE TITLE
Parameter for excluding certain paths to service

### ISSUE THREAD

**Issue by dave08** [vfarcic/docker-flow-proxy#379]
This feature would give the possibility to 'hide' certain paths to a service such as `/metrics`. Currently the only way to do it is by including all possible other paths, which could get to be cumbersome, the proposition is to provide something like `com.df.servicePathExclude=/metrics`.

**Comment by vfarcic** [comment]
Available in the [release 17.12.02-69](https://github.com/vfarcic/docker-flow-proxy/releases/tag/17.12.02-69).

**Comment by dave08** [comment]
Thanks alot!
