### ISSUE TITLE
sessionType settings with service update

### ISSUE THREAD

**Issue by wyhysj** [vfarcic/docker-flow-proxy#382]
Hi, I look into issue [#171](https://github.com/vfarcic/docker-flow-proxy/issues/171) and [#296](https://github.com/vfarcic/docker-flow-proxy/issues/296), and tried sessionType=sticky-server in my configuration.

But the thing is we use `docker service update` to do CI, and update service docker images. When we do such update, seems current configuration doesn't work.

```
backend domain-name_web-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    http-request redirect scheme https if !{ ssl_fc }
    balance roundrobin
    cookie domain-name_web insert indirect nocache
    server domain-name_web_0 10.0.3.82:80 check cookie domain-name_web_0
    server domain-name_web_1 10.0.3.76:80 check cookie domain-name_web_1
```

Because after service update, the container IP in overlay network will change, then service unavailable

I also checked swarm listener documentation, seems now only got "DF_NOTIFY_CREATE_SERVICE_URL" and "DF_NOTIFY_REMOVE_SERVICE_URL", for service update event, listener can not notify swarm proxy, right?

Any work around or suggestion here

Thanks

**Comment by vfarcic** [comment]
You might want to use env. vars. `REPEAT_RELOAD` and `RELOAD_INTERVAL`. With `REPEAT_RELOAD`, DFP will repeat the process periodically and keep the list of service IPs up to date. Both env. vars. are described in http://proxy.dockerflow.com/config/#environment-variables . Can you please try it out and let me know if it fixes your problem?

**Comment by vfarcic** [comment]
Can you please let me know if the previous message helped and the issue can be closed?

**Comment by wyhysj** [comment]
@vfarcic Hi, I'm on leave for last two weeks, will test on Monday tomorrow, sorry for the delay

**Comment by wyhysj** [comment]
Hi @vfarcic I think this work around can not
Even I don't issue a `docker service update`, I see configuration reloaded with different state

```    server domain-name_web_0 10.0.1.19:80 check cookie domain-name_web_0
    server domain-name_web_1 10.0.1.21:80 check cookie domain-name_web_1
```

```    server domain-name_web_0 10.0.1.21:80 check cookie domain-name_web_0
    server domain-name_web_1 10.0.1.19:80 check cookie domain-name_web_1
```

Although the IP is changed when service update, but the sticky server will be a random state with every reload interval.

**Comment by vfarcic** [comment]
Those two configurations are the same (order should not matter). However, I just realized another problem. You cannot have more than one replica of the proxy. Otherwise, there is no guarantee that both will get the same cookie and they might forward to different replicas of the end-service.

**Comment by wyhysj** [comment]
Hi @vfarcic My docker flow proxy only got 1 replica, and service backend have multiple replica. But with every reload interval, the service backend will flip with different cookie, I don't know if you get it. My last comment the configuration is from same proxy, only different reload interval.

**Comment by vfarcic** [comment]
I got it. I'll see what I can do next week. I'd like to check it out earlier but the rest of this week I'll have too much work to do.

**Comment by rusanov** [comment]
Any update on this, I have the same issue. Workaround with REPEAT_RELOAD do the job for updating replica's ips but I can not use replicas for the proxy due to different cookies set.

**Comment by vfarcic** [comment]
I haven't had the opportunity to tackle this issue. There were other more urgent issues I had to solve on top of all other obligations (not related to DFP). Would one of you volunteer to do a PR? I'd guide you through the code.

**Comment by jjesudassbah** [comment]
I have the same problem with multiple replicas of the server/container with sessiontype sticky :(

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
