### ISSUE TITLE
Add support for mapping full URLs

### ISSUE THREAD

**Issue by cazacugmihai** [vfarcic/docker-flow-proxy#385]
Please add support for mapping full URLs, e.g.: map `/search` to `https://www.google.ro/search`.

I'm using this in nginx:

```
location /search {
    proxy_pass http://some-external-site/search;
}
```

Thanks!

**Comment by vfarcic** [comment]
Did you try `outboundHostname`? I think that should solve your problem.

**Comment by cazacugmihai** [comment]
Reading the [docs](https://proxy.dockerflow.com/usage/), I see that `outboundHostname` is: 
```
The hostname where the service is running, for instance on a separate swarm. 
If specified, the proxy will dispatch requests to that domain.
```
Based on this and the fact that I have already the `servicePath` specified and pointed to a local machine:
```
--label com.df.servicePath=/sockjs-node,/assets
--label com.df.serviceDomain=local_machine_name
```
I cannot use that parameter because all the requests will be forwarded now to the external host (specified by `outboundHostname`).

What I need is something like this (it can be related to [383](https://github.com/vfarcic/docker-flow-proxy/issues/383)):
```
--label com.df.reqPathReplace=/search:http://some-external-site/search
```

**Comment by vfarcic** [comment]
@cazacugmihai `outboundHostname` can be indexed. You can have one something like `servicePath.1=/something` that would redirect it to the service in the cluster and `servicePath.2=/else`and `outboundHostname.2=some-domain.com` that would redirect requests that match that path to the external domain. Is that what you're looking for?

**Comment by cazacugmihai** [comment]
Yes.
