### ISSUE TITLE
Separate go code and docker image configuration

### ISSUE THREAD

**Issue by remy-tiitre** [vfarcic/docker-flow-proxy#386]
Have you thought about separating the docker-flow-proxy go code compilation and distribution from docker image. My issue is that I would like to use different base for docker-flow-proxy, alpines DNS causes issues and it would be easier to base the proxy image from our own corporate base image.

I know that we could do it right now as well, but we would have to fork the whole go source code as well, which is not ideal.

**Comment by vfarcic** [comment]
Do you have a suggestion what would work well for your use case? Would publishing binaries separately from Docker images do the trick or you had something else in mind?

**Comment by remy-tiitre** [comment]
Thats something I had in mind, yes. So I could base my docker image on centos, ubuntu or any other OS. There seems to be some issues with DNS configuration on alpine image. https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md

**Comment by vfarcic** [comment]
I think I should have it done by the end of next week. I hope that's OK.

**Comment by remy-tiitre** [comment]
Yeah, thats fine. Thanks for the greate work.

**Comment by vfarcic** [comment]
I'll have to delay the work on this for a week. I had too much on my plate and could not find enough time.

**Comment by vfarcic** [comment]
Available in the release https://github.com/vfarcic/docker-flow-proxy/releases/tag/17.12.17-87. Can you please try out the binaries and let me know if that's what you were looking for?
