### ISSUE TITLE
hpproxy metrics public exposed

### ISSUE THREAD

**Issue by chengoldbond1** [vfarcic/docker-flow-proxy#387]
publish a way to expose haproxy metric (4xx,5xx, etc.) to an external port for outside usage

**Comment by mhaamann** [comment]
I have not tried it yet myself but I believe that this can be solved reading this section: https://proxy.dockerflow.com/swarm-mode-auto/#proxy-statistics

**Comment by vfarcic** [comment]
There are (as @mhaamann mentioned earlier) HAProxy stats as well as the `/metrics` endpoint that transforms them into Prometheus-friendly metrics.

Please let me know if that's what you're looking for @chengoldbond1

**Comment by vfarcic** [comment]
I'll assume that the issue can be closed. Please reopen it if the proposed solutions do not fit your use-case.
