### ISSUE TITLE
FezVrasta bootstrap resources give 404

### ISSUE THREAD

**Issue by BretFisher** [vfarcic/docker-flow-proxy#388]
**Description**

Looks like the method for including bootstrap css/js in `errorfiles` has changed URL's.

**PR with fix is coming today**

**Steps to reproduce the issue:**
1. Cause Docker Flow Proxy to give you a "friendly" HTTP error
2. Look at the source of error page
3. See the 404's for resources from https://github.com/FezVrasta/bootstrap-material-design

**Describe the results you received:**

`404`'s for FezVrasta resources:

https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/master/dist/css/bootstrap-material-design.min.css
https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/master/dist/css/ripples.min.css
https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/master/dist/css/bootstrap-material-design.min.css
https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/master/dist/css/ripples.min.css

**Describe the results you expected:**

`200`

**Additional information you deem important (e.g. issue happens only occasionally):**

It may be better to include these resources in the repo and Docker image, and to only include official bootstrap rather than a one-off theme like this.

**Comment by vfarcic** [comment]
Thanks @BretFisher
