### ISSUE TITLE
Add custom, index-able variable for templates

### ISSUE THREAD

**Issue by wheelybird** [vfarcic/docker-flow-proxy#394]
Hello.   I'm using a very basic, custom template for the frontend definitions as I need to define a large number of ACLs for our particular implementation.  I then need to get the frontends created by DFP to match against these ACLs.  It'd be really useful if there was a generic, index-able variable I could use for this purpose.
So, as an example, the frontend template would be:
```
{{- range $sd := .ServiceDest}}
use_backend {{$.ServiceName}}-be{{.Port}}_{{.Index}} if {{$.userDef}}
{{- end}}
```
and the DFP configs in the backend container:
```
com.df.port.1: "8080"
com.df.servicePath.1: "/"
com.df.userDef.1: "host_cheese"
com.df.port.2: "8081"
com.df.servicePath.2: "/"
com.df.userDef.2: "host_wine"
```
Is this something that is reasonable or even feasible?  CHeers!

**Comment by vfarcic** [comment]
That shouldn't be a problem. I saw that you already went through the code so maybe you'd like to send a PR? If not, I think I can add this feature over the weekend.

**Comment by wheelybird** [comment]
I've looked through the code, but frankly Golang is a bit beyond me right now.  I'm more of a Perl person. :D

**Comment by vfarcic** [comment]
Sorry for a very long delay with this issue. Could not find a free moment to work on it until now.

`userDef` parameter was added to the [release 18.01.28-100](https://github.com/vfarcic/docker-flow-proxy/releases/tag/18.01.28-100). I hope it's still useful to you.

Please let me know if it works as expected.

**Comment by wheelybird** [comment]
Hi.  Thanks a lot!   I've moved back to static haproxy for the time being, but I'll give it another try as soon as possible and let you know.
