### ISSUE TITLE
Constantly failing service should be ignored

### ISSUE THREAD

**Issue by dave08** [vfarcic/docker-flow-proxy#395]
When putting up a new service and testing its configuration, sometimes it fails many times, the configuration doesn't get regenerated and all other services are unreachable at that time. Would it be possible to keep the last working configuration until the service succeeds to stay running?

**Comment by vfarcic** [comment]
That is the idea behind the current design. However, seems that it does not cover all the cases. Could you create a set of commands/stacks that would help me reproduce this. That would simplify the search for the specific case and help me make sure that the change fixes it.

**Comment by dave08** [comment]
I've had problems with the overlay networking recently, so a possibility is that it can't reach that service in the first place... I had to delete the network and re-attach all my services to it and then things started working again and DFP got its configs... But meanwhile, even when I scaled the unreachable containers to 0, DFP was still trying to reach them... Is there a way the swarm listener could only send config requests when there is at least one replica in the service...

**Comment by vfarcic** [comment]
I'll assume that the issue is solved. Please let me know if that's not the case.
