### ISSUE TITLE
Proxy returns 503 after one swarm node is down

### ISSUE THREAD

**Issue by rubensyltek** [vfarcic/docker-flow-proxy#397]
**Proxy returns 503 after one swarm node is down**

We have a docker swarm with 3 manager nodes and 3 worker nodes. We also have configured a proxy overlay network. The proxy service is set up to start in 2 instances (worker nodes).

When the proxy is started (scaled up from 0 to 2) everything works fine after a short period of time. Then, when we shut down one of the worker nodes where the proxy container is running on we start receiving 503 from the new instance created by swarm to replace the one that is down. Looking at the configuration of that proxy instance we see that it didn't see any service and that's why we're getting 503.

If we scale down the proxy to 0 and back to 2 everything works normally again.

**Steps to reproduce the issue:**
1. Deploy the proxy in 2 instances in worker nodes using a proxy overlay network
2. Deploy some other services and make sure the proxy is configured correctly and those services are reachable.
3. Shut down one of the nodes where the proxy is running on
4. Try to access some of the services. You will get 503 from the proxy

**Describe the results you received:**
We get 503 after shutting down a node

**Describe the results you expected:**
Everything should keep on working smoothly even if one node is down

**Additional information you deem important (e.g. issue happens only occasionally):**
We're using version 17.11.24-67.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The cluster is running on virtual machines in our own servers

**Comment by shabbirkagalwala** [comment]
Had the exact same issue couple of weeks again, when a node failed and autoscaling started another and joined it to the swarm again.

**Comment by vfarcic** [comment]
I'm failing to reproduce this problem. My best guess is that the problem is with ingress network and that it continues sending requests to the failed node or that the network that connects the proxy with the final service is still using the failed node. In either case, I think that the problem is in Docker networking or your cluster setup.

I wrote a simple set of steps to test it. They are in https://github.com/vfarcic/docker-flow-proxy/tree/master/issues/397. If you think the issue is related to DFP (not ingress), please go through them and help me reproduce the problem. It might be a corner case I missed.

**Comment by rubensyltek** [comment]
When the node is shut down a new container is starting in a different node. When I send a request to that container to get the HAProxy configuration the configuration doesn't have any of my services. The other instance, the one running in the node that wasn't stopped keeps on working properly so I get 503 only when I reach the new instance that it's not configured properly. 

I guess the new instance is not notified of the services in the swarm and that's why the HAProxy is not configured. 

Tomorrow I'll run the test again and I'll upload the logs

**Comment by rubensyltek** [comment]
When the node is shut down a new container is started in a different node. When I send a request to that container to get the HAProxy configuration the configuration doesn't have any of my services. The other instance, the one running in the node that wasn't stopped, keeps on working properly so I get 503 only when I reach the new instance that it's not configured properly. 

I guess the new instance is not notified of the services in the swarm and that's why the HAProxy is not configured. 

Tomorrow I'll run the test again and I'll upload the logs

**Comment by vfarcic** [comment]
A a DFP replica is started, it gets all the information from DFSL. In the tests I run, a new replica was created after a node was destroyed and the configuration was correct. I'm sure that there is a bug. I just need to manage to reproduce it.

Could you modify the commands/stacks from the link in the previous message so that the issue is reproduced? If that's not an option, logs from a "real" system should help.

**Comment by mhabegger** [comment]
Same behavior here. Happens 1-2 per week.
The reconfiguration of DFP seems to get stuck somehow because it cannot resolve the service since it is not up and running yet. 

We tried to move services and DFP to worker nodes only and use manager node, just as managers. Currently we have 3 managers and 3 workers but still see the issue once a week.

Would it be possible to follow through with reconfiguration and strip out the services for which it fails only so that the services up get their proper configuration? In that case, services that are quickly back up would work again while services which take 2-3 minutes to restart or have dependencies on each other would be reconfigured at a later point?

Excerpt from yesterdays issue for a service with 2 replicas:
```
2017/12/18 18:01:34 Processing remove request /v1/docker-flow-proxy/remove
2017/12/18 18:01:34 Removing mediadeliver-playlistapi-beo_playlistapi configuration
2017/12/18 18:01:34 Removing the mediadeliver-playlistapi-beo_playlistapi configuration files
2017/12/18 18:01:34 Reloading the proxy
2017/12/18 18:01:34 Validating configuration
Configuration file is valid
2017/12/18 18:01:34 Proxy config was reloaded
2017/12/18 18:02:09 Creating configuration for the service mediadeliver-playlistapi-beo_playlistapi
2017/12/18 18:02:09 Reloading the proxy
2017/12/18 18:02:09 Validating configuration
Exit Status: 1
2017/12/18 18:02:09 Config validation failed. Will try again...
2017/12/18 18:02:10 Validating configuration
Exit Status: 1
2017/12/18 18:02:10 Config validation failed. Will try again...
2017/12/18 18:02:11 Validating configuration
Exit Status: 1
2017/12/18 18:02:11 Config validation failed. Will try again...
2017/12/18 18:02:12 Validating configuration
Exit Status: 1
2017/12/18 18:02:12 Config validation failed. Will try again...
2017/12/18 18:02:13 Validating configuration
Exit Status: 1
2017/12/18 18:02:13 Config validation failed. Will try again...
2017/12/18 18:02:14 Validating configuration
Exit Status: 1
2017/12/18 18:02:15 Config validation failed. Will try again...
2017/12/18 18:02:16 Validating configuration
Exit Status: 1
2017/12/18 18:02:16 Config validation failed. Will try again...
2017/12/18 18:02:17 Validating configuration
Exit Status: 1
2017/12/18 18:02:17 Config validation failed. Will try again...
2017/12/18 18:02:18 Validating configuration
Configuration file is valid
2017/12/18 18:02:18 Config validation failed

stdout:

stderr:
[ALERT] 351/180217 (6694) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
[ALERT] 351/180217 (6694) : Failed to initialize server(s) addr.


global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    # disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

resolvers docker
    nameserver dns 127.0.0.11:53

[...]

2017/12/18 18:02:18 Proxy config was reloaded

```

And the error log:
```
2017-12-18T18:02:09.904212180Z [ALERT] 351/180209 (6680) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
2017-12-18T18:02:09.907880105Z [ALERT] 351/180209 (6680) : Failed to initialize server(s) addr.
2017-12-18T18:02:10.926438779Z [ALERT] 351/180210 (6681) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
2017-12-18T18:02:10.930006838Z [ALERT] 351/180210 (6681) : Failed to initialize server(s) addr.
2017-12-18T18:02:11.950710045Z [ALERT] 351/180211 (6682) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
2017-12-18T18:02:11.953944985Z [ALERT] 351/180211 (6682) : Failed to initialize server(s) addr.
2017-12-18T18:02:12.970671450Z [ALERT] 351/180212 (6690) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
2017-12-18T18:02:12.973908585Z [ALERT] 351/180212 (6690) : Failed to initialize server(s) addr.
2017-12-18T18:02:13.991859588Z [ALERT] 351/180213 (6691) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
2017-12-18T18:02:13.995384009Z [ALERT] 351/180213 (6691) : Failed to initialize server(s) addr.
2017-12-18T18:02:15.012157132Z [ALERT] 351/180215 (6692) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
2017-12-18T18:02:15.015420318Z [ALERT] 351/180215 (6692) : Failed to initialize server(s) addr.
2017-12-18T18:02:16.033942267Z [ALERT] 351/180216 (6693) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
2017-12-18T18:02:16.037386725Z [ALERT] 351/180216 (6693) : Failed to initialize server(s) addr.
2017-12-18T18:02:17.056811264Z [ALERT] 351/180217 (6694) : parsing [/cfg/haproxy.cfg:185] : 'server mediadeliver-playlistapi-beo_playlistapi' : could not resolve address 'mediadeliver-playlistapi-beo_playlistapi'.
2017-12-18T18:02:17.060625225Z [ALERT] 351/180217 (6694) : Failed to initialize server(s) addr.
```

**Comment by mhabegger** [comment]
Would #396 solve this by any chance?

**Comment by vfarcic** [comment]
I think you're right @mhabegger. Can you try it again with the latest release @rubensyltek ?

**Comment by rubensyltek** [comment]
It's working fine with version 17.12.19-90

**Comment by mhabegger** [comment]
We've updated our stack to 17.12.21-91 and keep you updated if we still see similar issues.
Thanks again very much.
