### ISSUE TITLE
Issue with some large headers using df-proxy behind AWS ELB

### ISSUE THREAD

**Issue by rusanov** [vfarcic/docker-flow-proxy#400]
**Description**
We are using Docker4AWS and want to create SSL termination with df-proxy.
Docker4AWS setup EC2 ELB with TCP forward on port 443.
Some request with really large header ~ 45KB fails.
**Steps to reproduce the issue:**
1. Start swarm cluster in AWS
2. Setup latest df-proxy as ssl termination
3. Try to make POST requests with large HTTP headers

**Describe the results you received:**
With ELB configured as show in attachment issue persists.
<img width="1126" alt="screen shot 2017-12-21 at 12 19 28" src="https://user-images.githubusercontent.com/2698037/34251574-44f31f08-e649-11e7-9dab-3b72673e38ce.png">

This is the log entry for large request:
2017/12/21 10:04:15 HAPRoxy: 10.255.0.2:35892 [21/Dec/2017:10:04:15.969] services~ services/<NOSRV> -1/-1/-1/-1/0 503 674 - - SC-- 2/2/0/0/0 0/0 "POST / HTTP/1.1"

This is screenshot with HTTPS forward setup and all works fine:
<img width="1159" alt="screen shot 2017-12-21 at 12 21 17" src="https://user-images.githubusercontent.com/2698037/34251651-7d08d1da-e649-11e7-9255-915b025cf8f2.png">

**Additional information you deem important (e.g. issue happens only occasionally):**
I also tried with version 17.12.02-72 of df-proxy and issue does not occurs.

**Comment by patricjansson** [comment]
I am not a AWS user, but have you checked that your are not running into some AWS limits, like for http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-custom-headers ?

**Comment by rusanov** [comment]
It turns out that problem is using alpn in http2 connectinos:
https://github.com/vfarcic/docker-flow-proxy/commit/1bd3b5a36fc935a01fac85b4277e94f61ab5b386#diff-27ede3b1d638e09e6b033cb1647c8772

After building latest version with bind options:
bind *:443 ssl crt-list /cfg/crt-list.txt alpn http/1.1

everything works as expected.

**Comment by vfarcic** [comment]
Please switch to `vfarcic/docker-flow-proxy:17.12.21-91` (or newer) and add the env. var. `ENABLE_H2=false`. That will remove the http/2 support and result in the same config as the one you created @rusanov.
