### ISSUE TITLE
Use com.df.reqPathSearchReplace in multiple sets

### ISSUE THREAD

**Issue by dave08** [vfarcic/docker-flow-proxy#406]
Like`com.df.reqPathSearchReplace.1`, instead of having it as a global setting for all routes. My use case is that I have multiple domains pointing to the same service and each needs `/` to point to a different path in the actual service.

**Comment by vfarcic** [comment]
Can you please try the tag `vfarcic/docker-flow-proxy:18.01.13-96` and let me know whether it works as expected?
