### ISSUE TITLE
why should one use this instead of the one created by docker-cloud https://hub.docker.com/r/dockercloud/haproxy/

### ISSUE THREAD

**Issue by mwaaas** [vfarcic/docker-flow-proxy#41]

**Comment by vfarcic** [comment]
The last time I checked, DockerCloud/HAproxy did not support Swarm Mode (Docker 1.12+), did not scale well, could not persist the state externally, and so on. Things might have changed in the meantime.

I'm not saying that this proxy is better or worse. Please try both and make your own conclusion.
