### ISSUE TITLE
URL Rewriting not working

### ISSUE THREAD

**Issue by jordijansen** [vfarcic/docker-flow-proxy#411]
Hi,

I'm having a little trouble with some basic set-up. Since we are limited to using docker-compose for development we have to write our set-up with environment variables instead of the Swarm listener. 

For me the URL rewriting is not working, I have a basic set-up with docker-flow-proxy wich proxies a simple Nginx server that serves under / (root). The docker-compose file:

> proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    environment:
      - DFP_SERVICE_SERVICE_NAME=blogserver
      - DFP_SERVICE_SERVICE_PATH=/blog
      - DFP_SERVICE_REQ_PATH_SEARCH_REPLACE=/blog,/
      - DFP_SERVICE_OUTBOUND_HOSTNAME=blog
      - DFP_SERVICE_PORT=80

Now if I navigate to /blog/1 I see the following line in the Nginx access log:

> 172.21.0.3 - - [15/Jan/2018:14:26:47 +0000] "GET /blog/1 HTTP/1.1" 404 199 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

As you can see the path is not replaced but is exactly kept the same and send to the underlying backend server.

Any help would be appreciated!

EDIT: It seems like the variable isn't used at all. Whatever I fill in at the DFP_SERVICE_REQ_PATH_SEARCH_REPLACE environment variable is completly ignored. Used the following values with no result: 
/blog,/test 
/blog/,/test/
/blog,
/blog/,

**Comment by vfarcic** [comment]
I just made a fix. It's available as `vfarcic/docker-flow-proxy:18.01.17-97`. Can you please try it out?

**Comment by jordijansen** [comment]
@vfarcic thanks for your fast response. Maybe I'm not understanding correctly, but it still doesn't seem to be working.  In my understanding if I navigate to http://proxy/blog/123 it should call the underlying backend at http://blogserver/123, is this correct?

When I look inside the container at the config generated I see no mention of a path replacement or anything.

**Comment by eonicle** [comment]
+1 here, REQ_PATH_SEARCH_REPLACE seems to be ignored at all, so we had to rollback to 17.12.02-72. IMHO, issue is with this [line](https://github.com/vfarcic/docker-flow-proxy/blob/426e4898b20aa6835dfdafdc25f72631d45a8e7f/server/server.go#L307). Shouldn't there be  `os.Getenv` method called as well?

**Comment by vfarcic** [comment]
@jordijansen You're right. I forgot to add the logic for `ReqPathSearchReplaceFormatted`. I had a limited time available and ended up with changes that were not properly tested. I'm building a new tag `vfarcic/docker-flow-proxy:18.01.18-98`. Can you please try it out and let me know whether it works as expected? I (again) had very limited free time and did only a very basic testing.

**Comment by jordijansen** [comment]
That seems to be working now. But it seems like other options are also not working, do you want me to open a seperate issues for that (ALLOWED_METHODS, DENIED_METHODS, OUTBOUND_HOSTNAME)?

**Comment by vfarcic** [comment]
Seems that env. vars. were neglected. Feel free to post the list of vars. that do not work here or in a separate issue. Whatever is easier for you.

I noticed that you were checking the code so you might even give it a try with a PR?

**Comment by jordijansen** [comment]
I don't have any experience with Go yet. I'll create a separate issue for the env variables that are not working.

Would love to help you with this great project but can't promise anything as I'm quite busy with a project at the moment.
