### ISSUE TITLE
Odoo behinf docker flow proxy

### ISSUE THREAD

**Issue by aleskinen** [vfarcic/docker-flow-proxy#413]
I wan t to run odoo begind docker flow proxy. It needs path /longpolling to be directed to different port in same service. In local nginx it would be:
location /longpolling {
    proxy_pass http://127.0.0.1:8072;
}
location / {
    proxy_pass http://127.0.0.1:8069;
}

Can this be done with docker-flow-proxy?

**Comment by vfarcic** [comment]
You can use indexes to create different sets of rules. Your labels can be something like:

```
com.df.port.1=8072
com.df.servicePath.1=/longpolling
com.df.port.2=8069
com.df.servicePath.2=/
```

**Comment by vfarcic** [comment]
Please let me know if the suggestions solved the issue or it still persists?

**Comment by aleskinen** [comment]
This seems to work fine. Log has some warnings about order of settings, but seems to work fine with latest version.
