### ISSUE TITLE
Environment variables not working when using manual configuration

### ISSUE THREAD

**Issue by jordijansen** [vfarcic/docker-flow-proxy#415]
Hi,

I've noticed that a lot of the [environment variables](http://proxy.dockerflow.com/usage/#environment-variables) are not working at the moment. The variables I've noticed that are not working are:
- ALLOWED_METHODS
- DENIED_METHODS
- SET_REQ_HEADER
- OUTBOUND_HOSTNAME
- BACKEND_EXTRA
- VERIFY_CLIENT_SSL

I expect there are even more that are not working as it seems to be a general issue with environment variables.

**Comment by jordijansen** [comment]
I'll try to get a PR ready this week for this issue.

**Comment by vfarcic** [comment]
That's great! Thank you in advance @jordijansen.

**Comment by jordijansen** [comment]
I've added a PR to resolve this. Let me know if I should change anything.

I think the docs could also be improved regarding the environment variables, because some env variables can only be used at certain levels. I distinguish 4 levels:
- global (for example: DO_NOT_RESOLVE_ADDR)
- DFP_SERVICE (for example: DFP_SERVICE_HTTPS_ONLY)
- DFP_SERVICE_1 (for example: DFP_SERVICE_1_SERVICE_PATH)
- DFP_SERVICE_1_SERVICE_PATH_1, DFP_SERVICE_1_SERVICE_PATH_2

**Comment by vfarcic** [comment]
Available as `vfarcic/docker-flow-proxy:18.01.28-99`.
