### ISSUE TITLE
Run as global service

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/docker-flow-proxy#42]

**Comment by pascalandy** [comment]
+1

**Comment by vfarcic** [comment]
The ticket was created to validate whether the proxy works when deployed in global mode. It does :)

```bash
```

**Comment by vfarcic** [comment]
There's nothing to do to run the proxy in the global mode.

**Comment by pascalandy** [comment]
Wow. This is terrific!

**Comment by vfarcic** [comment]
Please note that Consul is not a requirement for running in the Global mode. The only important thing is to use "distribute=true" so that all instances are reconfigured.
