### ISSUE TITLE
Refactor environment variables

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/docker-flow-proxy#420]
Try to refactor the code by making env. vars. parsing more generic instead hard-coding every parameter.

The `getServiceFromEnvVars` function inside `server/server.go` extracts each environment variable separatelly. It would be more efficient to iterate through all environment variables with the correct prefix, and convert them into structs automatically. Otherwise, we'd continue running into situations when a new parameter is not parsed as env. var.

@jordijansen Since you already submitted a fix for the same function (PR #417), maybe you'd like to work on this as well?

**Comment by jordijansen** [comment]
Yes, was thinking about this as well. If I have some spare time, I'll work on it.

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
