### ISSUE TITLE
OUTBOUND_HOSTNAME env.variable is ignored and SERVICE_NAME treated as it instead

### ISSUE THREAD

**Issue by redtex** [vfarcic/docker-flow-proxy#421]
When I try to add non-swarm service, according to http://proxy.dockerflow.com/non-swarm/ , I have to use OUTBOUND_HOSTNAME env.variable to inform flow-proxy about non-swarm service backend address, and SERVICE_NAME as service identifier.
But now, it's not.
SERVICE_NAME is used as service identifier and has to be resolvable hostname, which is used as service backend address
OUTBOUND_HOSTNAME is just ignored

**Comment by vfarcic** [comment]
it's fixed and available as the `vfarcic/docker-flow-proxy:18.01.29-101` tag. Can you please try it out and let me know whether it works as expected?

**Comment by redtex** [comment]
Victor, thank you for fast response.
Yes, now it's works as expected..
