### ISSUE TITLE
DFP to handle SSL pass through

### ISSUE THREAD

**Issue by shebinbabu05** [vfarcic/docker-flow-proxy#423]
**Description**

I have a requirement to run DFP in mode http for port 80 and in mode tcp for port 443.
I have updated DEFAULT_PORTS="80", apart from that all the other environment values are same as in here: https://github.com/vfarcic/docker-flow-proxy/blob/master/Dockerfile

I have used DFP for my cluster that runs nearly 70 services. However, I am now stuck at a point where I might need your help/suggestion. Till now all the services that I have created/migrated uses HTTP only, so far all good. I have few web app services to migrate which handles SSL themselves so I’d not need SSL termination at DFP instead I’d like DFP to do an SSL pass through. Unfortunately, I am not getting the result as expected.

**Steps to reproduce the issue:**
1. Currently configured DFP to run in mode http for port 80 and in mode tcp for port 443, config pasted below

2. Created a service using the following command that serves request sent to backend servers

```bash
docker service create --with-registry-auth --limit-memory 1500m --name dev-test --network proxy --label com.df.notify=true --label com.df.distribute=true --label com.df.serviceDomain=dev-test.example.com --label com.df.port.1=80 --label com.df.servicePath.1=/ --label com.df.port.2=443 --label com.df.srcPort.2=443 --label com.df.reqMode.2=tcp shebinbabu05/nginx-ssl
```

3.The backend server/container is exposed on port 80 and 443.

**Describe the results you received:**
I get an operation timeout while accessing the domain on port 443

```bash
openssl s_client -connect dev-test.example.com:443
```

```
connect: Operation timed out
connect:errno=60
```

**Describe the results you expected:**
The docker when I run on my local machine with the following command I get the HTTPS page without any issue:

```bash
docker run --name nginx-ssl-07-dev-test -d -p 80:80 -p 443:443 shebinbabu05/nginx-ssl:latest
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Here’s how my dfp config looks like

```bash
cat cfg/haproxy.cfg
```

```
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048
    log 127.0.0.1:1514 local0

    # disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

resolvers docker
    nameserver dns 127.0.0.11:53

defaults
    mode    http
    balance roundrobin

    option  http-keep-alive
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s


frontend services
    bind *:80
    mode http

    option httplog
    log global
    acl url_dev-test80_1 path_beg /
    acl domain_dev-test80_1 hdr(host) -i dev-test.example.com
    acl domain_dev-test443_2 hdr(host) -i dev-test.example.com
    use_backend dev-test-be80_1 if url_dev-test80_1 domain_dev-test80_1

frontend tcpFE_443
    bind *:443
    mode tcp
    option tcplog
    log global
    acl domain_dev-test443_2 hdr(host) -i dev-test.example.com
    use_backend dev-test-be443_2 if domain_dev-test443_2

backend dev-test-be80_1
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    log global
    server dev-test dev-test:80
backend dev-test-be443_2
    mode tcp
    log global
    server dev-test dev-test:443
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by vfarcic** [comment]
Can you make `shebinbabu05/nginx-ssl` (or a stripped down version) public? That would help me simplify testing.

**Comment by shazChaudhry** [comment]
@vfarcic I am also keen to understand if ssl passthough is possible with the proxy service. I will be grateful if you could point me to an example showing configuration.

**Comment by goncalo-oliveira** [comment]
Isn't it something like this you want?

```
docker service create --name servicename \
    --network proxynetwork \
    --label com.df.notify=true \
    --label com.df.port=443 \
    --label com.df.servicePath=/hello \
    --label com.df.httpsOnly=true \
    --label.com.df.sslVerifyNone=true \
    imagename
```

The documentation says about `sslVerifyNone` that 

> If set to true, backend server certificates are not verified. This flag should be set for SSL enabled backend services.

**Comment by shazChaudhry** [comment]
Thanks @goncalo-oliveira for a quick response. 
Please correct me _(and accept my apologies for making noise)_ if I am wrong but the example provided is for "SSL Termination" and not for the "SSL Pass-Through" that I was hoping to learn about. 

Found this easy to understand article that explains the difference between "SSL Termination" and "SSL Pass-Through" at https://serversforhackers.com/c/using-ssl-certificates-with-haproxy

**Comment by vfarcic** [comment]
@shazChaudhry If you set the mode to tcp, it's always passthrough. Just remember that you won't be able to evaluate request paths and domains.

**Comment by shazChaudhry** [comment]
@vfarcic - Thats cool. Thanks
