### ISSUE TITLE
Config for websocket service

### ISSUE THREAD

**Issue by arrisde** [vfarcic/docker-flow-proxy#430]
I've been trying to use docker-flow-proxy to expose a websocket service running in my swarm stack. According to HAproxy docs and my own testing, the following settings in HAproxy's frontend section allow checking for presence of the HTTP upgrade header and routing to the websocket backend: 

`acl hdr_connection_upgrade hdr(Connection) -i upgrade`
`acl hdr_upgrade_websocket  hdr(Upgrade) -i websocket`
`use_backend ws_backend if hdr_connection_upgrade hdr_upgrade_websocket`

Is there a way to achieve this kind of config with service labels used by docker-flow-proxy? What is the preferred way of dealing with websocket connections in dfp? 
The only way I have gotten this working so far is if use a seperate port and declare the service to be in tcp mode, which kind of defeats the purpose of the proxy. Also, due to #281, it seems that the proxy cannot terminate TLS in this case, right?

**Comment by vfarcic** [comment]
HAProxy should switch automatically from HTTP to tunnel mode when the client request a websocket.

The lines of the config you specified are often used when one wants to forward requests to one service or the other based on whether it's HTTP or WebSocket connection.

Can you please confirm that automatic switch from HTTP to tunnel mode did not work?

**Comment by arrisde** [comment]
Actually, I just tested again and you are correct, it seems websocket connections "just work" with the standard config for HTTP services. I have no clue why I couldn't get this running when I tried before. Appologies for opening an issue about this.
