### ISSUE TITLE
How to auto map port xx to xx ?

### ISSUE THREAD

**Issue by eromoe** [vfarcic/docker-flow-proxy#431]
Hello, 

I have read the doc http://proxy.dockerflow.com/swarm-mode-stack/
It looks like, all port be map to 80 on docker-flow-proxy running node, and need use sub directory to access it.

I have some service , I just want to map all of them to proxy running node,  expose  same port . 

I mean something like below can open port 7000, 12000 on manager node to access corresponding services.
```
  extractor:
    image: ${PRIVATE_REGISTRY}/bidspy/extractor:0.1
    environment:
      - PORT=12000
    deploy:
      labels:
        - com.df.notify=true
        - com.df.port=12000

  scheduler:
    image: ${PRIVATE_REGISTRY}/bidspy/scheduler:0.1
    links:
      - repository-lb
    environment:
      - PORT=7000
      - DB_API_URL=repository:6000
      - DEBUG=1
      - SCHEDULER_TIMEZONE=UTC
    deploy:
      labels:
        - com.df.notify=true
        - com.df.port=7000

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 7000:7000
      - 12000:12000
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      placement:
        constraints: [node.role == manager]
```

How to do this ?

**Comment by vfarcic** [comment]
You should adde env. var. `BIND_PORTS=7000,12000` to the proxy as well as `com.df. srcPort=7000` as an additional service label.

Before you do that, please check whether you need the proxy for that or not. If all you want is to serve one service on one port and the other on the other port, you might not need a proxy at all. It should be enough to simply publish those ports.

**Comment by eromoe** [comment]
Thank you . 

I just want to make all services can be accessed on one node, so that test would be easy.
