### ISSUE TITLE
reqPathSearchReplace has priority over servicePaths label

### ISSUE THREAD

**Issue by basz** [vfarcic/docker-flow-proxy#433]
> Something like that might be a good addition

Not entirely sure what you exactly meant here I'll just post the conversation... But *if* you where referring to the issue given titel...

Given a container that serves the mentioned servicePath files from `/` (not from `/.well-known`) you would expect to be able to use a label such as.

- com.df.servicePath=/.well-known/security.txt,/.well-known/security.txt.sig,/.well-known/security.pgp.key.txt,/.well-known/security-policy.jpg
- com.df.reqPathSearchReplace=/\.well-known,

Unfortunately this will not work because the request url is search and replaced first and the the servicePath obviously don't match.

Thanks

```
basz [5:51 PM]
what do you do when one proxy instance keeps giving ‘Config validation failed. Will try again...’? ps. it would be really helpful if the log shows why the reconfiguring failed.

vfarcic [5:52 PM]
@basz It should show the error from HAProxy below that line.
@basz Actually, it should show the actual error after all the attempts failed.
@basz By default, it tries for 20 times. That can be changed through the env. var. `RECONFIGURE_ATTEMPTS`.

basz [5:54 PM]
does not do that…. (vfarcic/docker-flow-proxy:17.10.14-45) perhaps to old?
ah.  all attempts…
exit status 1

vfarcic [5:55 PM]
https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/ha_proxy.go#L150
GitHub
vfarcic/docker-flow-proxy
docker-flow-proxy - Docker Flow Proxy

basz [5:55 PM]
and then the config and  ‘2018/02/11 16:51:23 Config validation failed’

vfarcic [5:56 PM]
It's in https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/ha_proxy.go#L506
GitHub
vfarcic/docker-flow-proxy
docker-flow-proxy - Docker Flow Proxy

basz [5:56 PM]
well simply removing the stack and redeploying solved it…

vfarcic [5:56 PM]
It prints `Config validation failed` followed with the error from HAProxy and the config.

basz [5:56 PM]
so, error was ‘exit status 1’

vfarcic [5:57 PM]
HAProxy often does not produce meaningful errors :disappointed:

basz [5:57 PM]
ok, to bad
is it to be expected that sometimes it just fails? while the labels (stack.yml) are in principle ok? (edited)

vfarcic [5:59 PM]
Not on my machine :slightly_smiling_face:. Jokes aside, there are many permutations and I'm often having difficulties reproducing other people's situation that causes a problem. If you can somehow make it reproducible, I'm sure I can fix that case as well. Otherwise, it's a bit tough. Sometimes networking is temporarily out, it takes too much to pull the images and run services, `proxy` resolves to something else, ...

basz [6:01 PM]
I totally understand. I’m on digitalocean now, small swarm. works ok in general. Sometimes I fear to reconfigure the proxy because sometimes these errors forces me to redeploy everything…
Does the swarm listener dispatch reconfigure instructions the moment a stack is deployed? Or after they are ready (edited)

vfarcic [6:03 PM]
It dispatches requests the moment a service is created. It does not know when it is running. DFP retries reconfiguration...
How long does it take for your services to become ready?

basz [6:04 PM]
seconds

vfarcic [6:05 PM]
Then timeouts are not a problem.

basz [6:05 PM]
deployed via gitlab ci. just added a very small nginx (100Kb) over all domains http://bushbaby.nl/.well-known/security.txt

vfarcic [6:06 PM]
Try to look for patterns. They help with reproducing issues.

basz [6:06 PM]
took a few deploymemnts to get it right and then one of the proxy instances got confused
Could a proxy request a complete reconfiguration when conf keeps failing?

vfarcic [6:07 PM]
Yes it can. Look for reload requests in the docs.
What did you mean by a few deployments to get it right? We're they failing to start before?

basz [6:10 PM]
I needed to play a bit with nginx rewrite rules. security.txt is actually in it root. started with the search and replace label, but that takes presedence over the servicePaths I couldn’t get that to work correctly.
btw this yields no results: http://proxy.dockerflow.com/?query=reload+requests
REPEAT_RELOAD?

vfarcic [6:14 PM]
Something like that might be a good addition. Can you open an issue? I am about to board a plane and go offline.

basz [6:14 PM]
Well, it’s an awesome project
Ok, will do. Thanks. Don’t crash!
```

**Comment by basz** [comment]
If i remember correctly;

Rewrite is done first. Which means my servicePath should become `/security.txt`.

That means that any service in the swarm that serves `/security.txt` would get it overriden by mine.Obviously I only want to override '/.well-known/security.txt'. 

So if servicePath is '/.well-known/security.txt'
then forward after rewriting `/security.txt` to my container.

ps. I could well be I made some other mistake that caused this. Like i said I solved it with a rewrite rule in the container.

**Comment by vfarcic** [comment]
Rewrite is happening on backend and ACLs are in frontend. If, for example, `servicePath` is `/.well-known/security.txt` and `reqPathSearchReplace` is `/.well-known,`, the process for a request with the path `/.well-known/security.txt` is:

1. A request enters on port `80`
2. HAProxy processes ACL rules (one by one) defined in the front-end. The first rule that matches moves it to the corresponding backend.
3. An ACL rule finds a match between for `/.well-known/security.txt` and sends it to the related backend.
4. Backend converts path `/.well-known/security.txt` to `/security.txt` using `reqPathSearchReplace` formula.
5. Backend forwards the request to the related service.

At least, that's the intention...

In any case, ACLs are in frontends, replace rules are in backend. Frontends are processed before backends.

As a side note, you don't need:

```
com.df.servicePath=/.well-known/security.txt,/.well-known/security.txt.sig,/.well-known/security.pgp.key.txt,/.well-known/security-policy.jpg
```

It can be:

```
com.df.servicePath=/.well-known
```

... unless you have paths for other services that start with `/.well-known`.

**Comment by basz** [comment]
> At least, that's the intention...

I might try to confirm that. I expected it to work this way...

> unless you have paths for other services that start with /.well-known.

letsencrypt-companion, but come to think of it i could give that a higher all priority

I'll leave it open for now as a reminder
thanks

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
