### ISSUE TITLE
multiple services mapped under a common name

### ISSUE THREAD

**Issue by cazacugmihai** [vfarcic/docker-flow-proxy#434]
Hi,

Let's say that we have three services and each one is listening on port `8888` but it is started with a different configuration (e.g. a different mounting volume). 

Is there a way to configure the proxy in order to obtain this behavior: 
when we are trying to access `http://localhost/`, the proxy will redirect the request to any service that is alive?

Thank you!

**Comment by cazacugmihai** [comment]
It is enough to use something like this:

```
--label com.df.notify=true \
--label com.df.distribute=true \
--label com.df.servicePath=/ \
--label com.df.port=8888 \
```

for each service? It seems to work but I need your confirmation. 

Thanks!

**Comment by cazacugmihai** [comment]
The services are based on the same image but have different configuration (the mounting volume). They form a replicated storage which assures me that if a node is down, the others can provide the requested information. 

What I want is to have a single point of access to these services. E.g.: having the services `storageA`, `storageB` and `storageC`, the proxy should allow me to access them by using a call to `http://localhost/` that points to any of the mentioned services (using round-robin algorithm) and, if any of them is down, the request will be always redirected to the one who is alive.

**Comment by vfarcic** [comment]
@cazacugmihai At the moment, that feature is not supported. Most users would run three replicas of a service attached to a network drive or by replicating data between those replicas (e.g., DBs). This is the first case I encountered with three services that should act as if they are one service with three replicas.

I'm not sure whether DFP should be the right tool to do something like that. If it is, what would be your suggestions for labels? How should DFP identify that all three services are acting as one service? A new label like `serviceGroup`?

**Comment by cazacugmihai** [comment]
Yes, you are right. On production, the services will be replicated and the problem is solved. But what if you want to run all of these services on a local machine (without resorting to VMware, VirtualBox or any other virtualization tool), in order to test the replication? As I said, each service instance is needing its own data directory and this cannot be done when the `replicas` is used. For this, there must be a way to create each service separately and hide them under a specific address (letting the proxy to do the rest of the job - the balancing).

I don't know for sure (but I tend to think so) if the `proxy` is really the right tool for this and I'm saying that only because I don't know if swarm, by itself, can solve this. 

About the suggested name (`serviceGroup`): yes, it is a very good one.

**Comment by vfarcic** [comment]
I think I understand what you need. However, I'll have to put this as `low-priority` since there aren't many in such a situation.

Would you be willing to work on this yourself? I can walk you through the code.

**Comment by cazacugmihai** [comment]
Yes, please write here the steps that you would have followed in order to implement this feature. Thanks!

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I'm on a trip with very limited free time. I'll write the steps during the upcoming weekend (if not before).

**Comment by vfarcic** [comment]
All data is kept in a map (https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/proxy.go#L6) and is available through its instance (https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/proxy.go#L10). The job would, most probably, be to modify `AddService` (https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/ha_proxy.go#L180) and `RemoveService` (https://github.com/vfarcic/docker-flow-proxy/blob/master/proxy/ha_proxy.go#L185) functions so that multiple Swarm services are added as a single service in DFP.

**Comment by cazacugmihai** [comment]
Okay. I'm going to start working on it.

**Comment by cazacugmihai** [comment]
Can you check the [changes](https://github.com/cazacugmihai/docker-flow-proxy/commit/eb9b4578e179c3699a762ce92c7e8e5bdd6aaa2a) that I've done and give a feedback? I haven't tested anything yet. I'm just curious if the direction is good or not.

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
