### ISSUE TITLE
DFP can't detect services in its own stack.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [vfarcic/docker-flow-proxy#442]
In the example setup in http://proxy.dockerflow.com/swarm-mode-stack/, DFP is in its own stack, safely deployed before any services are deployed.

This creates a race-condition where one stack needs to synchronize with another in order to work.

Sometimes it is more convenient to have DFP in the same stack as its services and make that work robustly.

The default DNS lookup logic in HAProxy seems to be to resolve a DNS name 3 times and give up. In a larger stack, this leads to HAProxy assuming a server is down, and refusing to serve that backend, simply because it was brought up together with some other server.

It seems like HAProxy by default should be configured to try to resolve DNS at least for a couple of minutes before failing.

**Comment by alexanderkjeldaas** [comment]
Is there any issue with setting `resolve_retries 3600` instead of the default `3`?

**Comment by vfarcic** [comment]
We can add a new env. var. that would overwrite the default value of `3`. Do you think that would work for you?

**Comment by alexanderkjeldaas** [comment]
I'm not sure if this solves it... I did a local change and this didn't fully stabilize, so I think it's premature.

Pulling it out into a separate stack did fix all issues though, so there is something iffy, but probably not this, or not only this.

**Comment by alexanderkjeldaas** [comment]
No, separate stack does not solve the issue.  HAProxy often gets into situations where it can think a backend is gone for hours.  I don't know how to get HAProxy to actually *use* DNS.

**Comment by vfarcic** [comment]
@alexanderkjeldaas Can you create a set of steps that would reproduce _HAProxy often gets into situations where it can think a backend is gone for hours_?

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
