### ISSUE TITLE
sticky-server on service update

### ISSUE THREAD

**Issue by valeriomazzeo** [vfarcic/docker-flow-proxy#446]
When using `com.df.sessionType: "sticky-server"`, the cookie on the client contains the specific container id.

When updating the service, that container id changes, and subsequent requests will fail with a socket connection error, until that cookie expires.

Is there anyway that docker-flow-proxy could invalidate the related cookies on containers update?

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
