### ISSUE TITLE
Document the semantics of docker-flow-proxy wrt the state transitions of containers

### ISSUE THREAD

**Issue by alexanderkjeldaas** [vfarcic/docker-flow-proxy#448]
I can't find any documentation on which states a container is in when docker-flow-proxy notifies various components.

For example, I would want HAProxy to be reloaded after the container is Healthy, not in Starting or Running states.

A sequence diagram like http://docs-aliyun.cn-hangzhou.oss.aliyun-inc.com/assets/pic/58588/cn_zh/1503972599061/%E6%97%B6%E5%BA%8F%E5%9B%BE.png (from https://www.alibabacloud.com/help/doc-detail/58588.htm) using websequencediagrams.com would be very helpful.

**Comment by vfarcic** [comment]
DFP receives a notification from DFSL when a service is created. Neither knows whether the service is running and healthy, but only that it was created. Once DFP receives a notification about a new service, it tries to contact it. If the service is unreachable, it'll try again in a loop until it succeeds or retries time out. On the other hand, Overlay network will LB only to replicas that are healthy.

Please let me know if that answers your questions.

**Comment by alexanderkjeldaas** [comment]
Shouldn't this be documented?
