### ISSUE TITLE
Swarm DFP with multiple ports (443 & 5601)

### ISSUE THREAD

**Issue by masonb81** [vfarcic/docker-flow-proxy#452]
I'm running within docker swarm the DFP with SSL configured via port 443 and trying to then also add it to be a reverse proxy for Kibana and serve on port 5601 using SSL. The sites work fine with HTTPS on port 443 but Kibana gives an SSL error but works fine using HTTP on port 5601. Can you see my configuration below what I might be missing? It would be preferable to make this work so Kibana is also served over SSL.

Docker Flow Proxy Configuration:

docker service create \
    --name proxy \
    -p 443:443 \
    -p 5601:5601 \
    --network proxy \
    --detach=true \
    --constraint 'node.role==manager' \
    -e MODE=swarm \
    -e LISTENER_ADDRESS=swarm-listener \
    -e BIND_PORTS=443,5601 \
    -e DEBUG=true \
    vfarcic/docker-flow-proxy

docker service update --secret-add my-ssl-cert.pem proxy

Service configuration:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    networks:
      - logging_nw
      - proxy
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./Kibana/kibana.yml:/etc/kibana/kibana.yml
    deploy:
      labels:
        - com.df.aclName=proxyPriority
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/,/api
        - com.df.port=5601
        - com.df.srcPort=5601
        - com.df.serviceDomainAlgo=hdr_beg(host)
        - com.df.serviceDomain=mysite.com

When trying to access: https://mysite.com:5601 this is the error:

![image](https://user-images.githubusercontent.com/24825800/38171905-51f3cb74-35ab-11e8-977a-95b539d6f029.png)

This is the error shown in the DFP container log:
proxy.1.tra4znro1bib@myserver    | 2018/04/01 09:52:38 HAPRoxy: 10.255.0.2:53603 [01/Apr/2018:09:52:38.689] services services/<NOSRV> -1/-1/-1/-1/0 400 658 - - PR-- 2/2/0/0/0 0/0 "<BADREQ>"
proxy.1.tra4znro1bib@myserver    | 2018/04/01 09:52:38 HAPRoxy: 10.255.0.2:53602 [01/Apr/2018:09:52:38.689] services services/<NOSRV> -1/-1/-1/-1/0 400 658 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>"

When accessing http://mysite.com:5601 the site works fine

Ideally in the long run I want kibana to be served on /kibana along with the other sites but it doesn't seem to work properly within Kabana as even using the server.basePath="/kibana" and setting up the mappings in the service labels which I've logged a separate ticket for: https://discuss.elastic.co/t/kibana-6-2-3-behind-reverse-proxy-with-sub-folder/126294

Thanks in advance!
Br, Mason

**Comment by vfarcic** [comment]
Can you please post the full stack (with ES). That way I can reproduce is as-is in my cluster.

**Comment by masonb81** [comment]
Hi Viktor,

Here is the contents of the ELK stack compose file:

version: "3.3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - cluster.name=docker-es-cluster
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Europe/Helsinki
    networks:
      - logging_nw
    deploy:
      resources:
        reservations:
          memory: 1000M
        limits:
          memory: 1500M

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - cluster.name=docker-es-cluster
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Europe/Helsinki
      - discovery.zen.ping.unicast.hosts=elasticsearch
    deploy:
      resources:
        reservations:
          memory: 1000M
        limits:
          memory: 1500M
    networks:
      - logging_nw

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.3
    volumes:
      - ./LogstashConfigFiles:/usr/share/logstash/pipeline:ro
      - /etc/localtime:/etc/localtime
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - logging_nw
    depends_on:
      - elasticsearch

  vnext-backend-beats-logfilereader:
    image: docker.elastic.co/beats/filebeat:6.2.3
    volumes:
      - ./FileBeatConfigFiles/app-backend.yml:/usr/share/filebeat/filebeat.yml:ro
      - backend-kestrel-logs-vol:/var/log/app-backend
      - /etc/localtime:/etc/localtime
    networks:
      - logging_nw
    depends_on:
      - logstash
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    networks:
      - logging_nw
      - proxy
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./Kibana/kibana.yml:/etc/kibana/kibana.yml
    deploy:
      labels:
        - com.df.aclName=proxyPriority
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/,/api
        - com.df.port=5601
        - com.df.srcPort=5601
        - com.df.serviceDomainAlgo=hdr_beg(host)
        - com.df.serviceDomain=mysite.com

networks:
  proxy:
    external: true
  logging_nw:

volumes:
  backend-kestrel-logs-vol:
    external: true

The docker service definition for our web application (below) that we have running already accessible on :443 is an internal angular app hosted on nginx. (I've only replaced confidential internal names/values/IP).

The app is served ok with SSL with no errors, just having problems to get Kibana from the ELK stack working on :5601 using SSL or (preferably) to get it running under a virtual folder like /kibana. I'm using the server.basePath="/kibana" value from their documentation but the content is still being served such that various components using the URL /bundles/.. etc when they should be from /kibana/bundles/... to work through the reverse proxy.

docker service create \
 --name myapp-admin-test \
 --network proxy \
--label com.df.aclName='proxyPriorityB' \
--label com.df.notify=true \
--label com.df.distribute=true \
--label com.df.serviceDomain=mysite.com \
--label com.df.servicePath=/admin \
--label com.df.reqPathSearch=/admin \
--label com.df.reqPathReplace=/ \
--label com.df.port=80 \
 1.1.1.1:8098/myapp-admin:208

**Comment by vfarcic** [comment]
Can you post your `kibana.yml` file as well?

**Comment by masonb81** [comment]
kibana.yml content:

server.port: 5601
server.host: "0.0.0.0"
#server.basePath: "/kibana"
elasticsearch.url: http://elasticsearch:9200

**Comment by masonb81** [comment]
Logstash configuration file content. Designed to process logs from kestral with serilog

input {
  beats {
    port => 5044
  }
}

filter {
  grok {
   match => { "message" => "%{TIMESTAMP_ISO8601:event_timestamp} ([+-]([01]?[0-9]|2[0-3]):[0-5][0-9]) \[%{LOGLEVEL:loglevel}\] %{GREEDYDATA:message}" }
   overwrite => ["message"]
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
    index => "%{[fields][appsource]}-%{+dd.MM.YYYY}"
    manage_template => false
  }
  stdout {
    codec => rubydebug
  }
}

**Comment by vfarcic** [comment]
The project moved to https://github.com/docker-flow/docker-flow-proxy. Please recreate the issue there if it's still valid.
