### ISSUE TITLE
Broken link for https://proxy.dockerflow.com/haproxy.tmpl

### ISSUE THREAD

**Issue by demaniak** [vfarcic/docker-flow-proxy#456]
**Description**

**Steps to reproduce the issue:**
1. Visit  https://proxy.dockerflow.com/config/#custom-config
2. Follow the link for haproxy.tmpl

**Describe the results you received:**
HTTP 404 error.

**Describe the results you expected:**
The `haproxy.tmpl` source file.

**Additional information you deem important (e.g. issue happens only occasionally):**
Permanent as far as I can see.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/a

**Comment by vfarcic** [comment]
Fixed
