### ISSUE TITLE
[help] Specify resolvers to be used

### ISSUE THREAD

**Issue by viict** [vfarcic/docker-flow-proxy#458]
Hi,

How can we specify resolvers to the haproxy? Not the docker resolver.

Just to understand our use case:
We have a few dynamic hostnames that periodically changes their IP, if we don't set a few resolvers with the "hold" option haproxy does not handle traffic to the correct IP.

I've found the DO_NOT_RESOLVE_ADDR but I think it's not what we are looking for.

**Comment by vfarcic** [comment]
Can you provide an example snippet of the config?

I guess something like:

```
resolvers docker
    nameserver dns [ADDRESS]
```

Where `[ADDRESS]` can be changed through an environment variable. Is that correct?

Yesterday we moved the project to https://github.com/docker-flow/docker-flow-proxy. Can you re-create the issue there?

**Comment by viict** [comment]
The issues tab there is not available. When available I can recreate the issue there.

Just to let you know our use case, is something like this, and for this example I used the public internet dns servers we know. But, we use a private dns cluster there.

```
resolvers dns
	nameserver dns-0  4.4.2.1:53
	nameserver dns-1  8.8.8.8:53
	nameserver dns-2  4.4.2.2:53
	nameserver dns-3  8.8.4.4:53
	hold valid 300s

backend infra-ddns
	mode http
        timeout connect 60s
	timeout server  60s
	server ddns1 ddns.domain.net:9000 resolvers dns check
	server ddns2 ddns2.domain.net:9000 resolvers dns check 
```

**Comment by vfarcic** [comment]
That should not be a problem. I can add that feature in a few days.

As a side note, I just enabled issues in the new repo.

**Comment by viict** [comment]
I'm closing this issue in favor of: docker-flow/docker-flow-proxy#1
