### ISSUE TITLE
two define ports running on a service. 

### ISSUE THREAD

**Issue by hitomidennis** [vfarcic/docker-flow-proxy#461]
Hi, 

I have a project called workflow in our company. The service running two ports 3000 and 4000, Just imagine and docker service running two services inside but using different ports. When a user access the URL http://x.sample.com:3000 upon login, it will redirect the user to http://x.sample.com:4000/x.
I am using dockerflowproxy(thanks to Sir viktor farcic for this). 
Is that possible in dockerflow proxy?
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/ \
    --label com.df.serviceDomain=x.sample.com \
    --label com.df.port=3000 \
    --label com.df.serviceDomain=x.sample.com \
    --label com.df.servicePath=/x \
    --label com.df.port=4000 \  

Is that possible?

Thank you

**Comment by vfarcic** [comment]
You can add indexes. For example:

```
--label com.df.servicePath.1=/ 
--label com.df.serviceDomain.1=x.sample.com 
--label com.df.port.1=3000 
--label com.df.serviceDomain.2=x.sample.com 
--label com.df.servicePath.2=/x 
--label com.df.port.2=4000 \
```

You'll find more information about it in http://proxy.dockerflow.com/usage/. A few tutorials probably use indexes as well.
