### ISSUE TITLE
[Feature request] Add TLS related parameters to the configuration endpoint

### ISSUE THREAD

**Issue by bvis** [vfarcic/docker-flow-proxy#48]
To avoid the need of extending your image each time a new TLS certificate is needed one possible improvement could be to allow to configure the TLS info of a configured service via parameters.

The system could accept some new parameters like:
- tlsKey: The certificate private key
- tlsCert: Your certificate
- tlsForced: If the request goes via the non TLS port a 301 redirect is done to the TLS port

I don't know the max length for a GET request your library supports, if it's not very long maybe implement POST would be a good option as an alternative.

**Comment by vfarcic** [comment]
Sorry for not responding earlier to this issue.

Maybe it would be a better option to add the keys to the image by extending Dockerfile? That way, both the new config and the key could be inside and save you the trouble from specifying it in requests. What do you think?

**Comment by vfarcic** [comment]
I think you're right. I'll start working on it ASAP.

**Comment by vfarcic** [comment]
I'm not sure that using labels to add a certificate is a good option. If I understood the request correctly, it would mean that content of a certificate would need to be a label and they are not really designed to hold a lot of information. Having certificate name as a label would be OK but then there would still need to be a process that uploads it to the proxy container.

I still need to test the limits of a value service label can hold. If the content of a certificate can be stored as a label, I'll start working on it soon.

In the mean time, I added an API endpoint that allows you to add a certificate to a running proxy service.

You can find the information about the request endpoint and parameters in the [Put Certificate](https://github.com/vfarcic/docker-flow-proxy#put-certificate) section.  A tutorial can be found in the [Configuring Service SSLs And Proxying HTTPS Requests](https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode-listener.md#configuring-service-ssls-and-proxying-https-requests) section of the [Swarm Mode (Docker 1.12+) With Automatic Configuration](https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode-listener.md) article.

Can you please let me know what are your thoughts on the subject?

**Comment by bvis** [comment]
I really like your approach about how to add the certificate.

And to be sure that the "extra" approach based in labels is secure I did a question in the docker-dev google group: https://groups.google.com/forum/#!topic/docker-dev/m74xF2L3MG8

At this moment nobody has provided any answer.

**Comment by vfarcic** [comment]
A few days ago I merged a pull request https://github.com/vfarcic/docker-flow-proxy/pull/82 that allows adding certificates through labels. It is available in the release [1.121](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.121).

Certificates can now be added as a POST request or through labels.

Closing this ticket... Please reopen it if you think more work should be done on this feature.
