### ISSUE TITLE
Unable to remove service from proxy configuration

### ISSUE THREAD

**Issue by tazle** [vfarcic/docker-flow-proxy#5]
It seems that removing a service from proxy configuration is not possible. There is no explicit API method for removing a service, and configuring a service with empty path merely changes the service frontend to match *any* request as follows:

    frontend http-env-echo-fe
            bind *:80
            bind *:443
            option http-server-close
            acl url_http-env-echo path_beg
            use_backend http-env-echo-be if url_http-env-echo
    
    backend http-env-echo-be

**Comment by vfarcic** [comment]
The option to send a request that will remove a service will be added in the next release in a day or two.

**Comment by vfarcic** [comment]
The release contains the option to remove a service from the proxy config. Please check https://github.com/vfarcic/docker-flow-proxy#remove for details.

Can you please test it and let me know if it matches your scenario?

**Comment by tazle** [comment]
Unable to test it in my environment right now. The description of the functionality looks good, and the code looks reasonable.
