### ISSUE TITLE
Feature Request - Allow creation of config entries even if the swarm service does NOT exist

### ISSUE THREAD

**Issue by goffinf** [vfarcic/docker-flow-proxy#50]
I could be wrong, but my testing indicates that if you attempt to use 'reconfigure' and specify a serviceName for a docker service which has not yet been created, a NOK response is returned.

I would like to request that it IS possible to create config entries AHEAD of the service existing.

I can understand why it might be cleaner to only allow configuration entries for EXISTING services and, if thats your preferred implementation I would request three other changes ...

1. Enhance the NOK response to indicate that the requested serviceName does NOT exist so it is obvious to the caller what the problem is.

2. Add this expected behaviour to the documentation for docker-flow-proxy

3. To make the reconfigure (add) behaviour consistent with remove, when a docker service is removed, detect that and also remove the entry from haproxy.cfg file.

See related issue: https://github.com/vfarcic/docker-flow-proxy/issues/51

**Comment by vfarcic** [comment]
A bit of a background. When HAProxy is reloaded, it checks the validity of its configuration. If there is an error it fails to reload and continues working with the previous config. In this case, HAProxy failed to find one of the addresses (service name) and rejected to reload. The message you were seeing comes directly from HAProxy.

I added address lookup into the DFP code. Before it starts creating the new HAProxy configuration and executing the command to reload it, it will perform an address lookup. If the destination address does not respond, it will return an error similar to the one that follows.

```
lookup my-new-service: no such host
```

I think this will make things clearer for those manually sending HTTP requests to reconfigure the proxy.

As a side note, if you start using [Docker Flow: Swarm Listener](https://github.com/vfarcic/docker-flow-swarm-listener) to configure the proxy, you'll see that it has the option to specify number of retries and the delay between the attempts. The listener will repeat the attempts to reconfigure the proxy until the service is available or the number of retries is exhausted. It monitors not only creation of new services but also their removal so it'll keep the proxy always up to date.

Please let me know if you think this solution fits your use case. If it doesn't, please reopen the ticket and we'll brainstorm a better way to handle this situation.
