### ISSUE TITLE
Multiple services that expose the same port on proxy overlay network

### ISSUE THREAD

**Issue by demaniak** [vfarcic/docker-flow-proxy#54]
Some background on environment:

- 13 host cluster
- split into 2 geographical locations
- Docker 1.12.2 in swarm mode
- 3 manager nodes (2 in one data center, 1 in the other one)
- using `serviceDomain` config option for docker-flow-proxy, with all `servicePath`'s set to `/`

So I'm attempting to run multiple services (different apps), and expose some of them externally on port 80 and 443, via docker flow proxy.

Basically just like the demo app, just with more than one one front end app.

So, I had two apps running, one exposing port 8080, and the other 8888. Everything was fine.

However, when I tried to bring a different service up, that is also exposing port 8080, things got weird.
I was suddenly seeing a lot of 404s, 503s and 500s when accessing the one app (via `serviceDomain`), and occasionally the OTHER app's response would start getting mixed in.

So as per the demo setup, I have a `proxy` overlay network, and overlay network for one of the other apps (this app has bunch of backing microservices). The second app was only connected to the `proxy` network.

I am NOT sure if this is a problem/limitation with
- my config
- docker flow proxy
- OR the docker 1.12 mesh routing

With the mesh routing in the mix, I'm not every sure where/how to start proper troubleshooting.

**Comment by vfarcic** [comment]
Is each service having a different domain or it's the same for all?

Can you send me the commands you used to set up your services and the proxy?

**Comment by demaniak** [comment]
Different domains for all of them.

I provide commands below, please just note that service and domain names were changed to protect the innocent (busy with bespoke development...)!

Some notes:
- app1 exposes port 8080 to the overlay network
- app2 exposes port 8888 to the overlay network
- app3 also exposes port 8080 to the ovelay network ([swagger editor image](http://swagger.io/swagger-editor/))
```
docker network create --driver overlay app1-net
docker network create --driver overlay proxy
docker service create --name proxy   -p 80:80  -p 443:443  -p 8080:8080   --network proxy -e MODE=swarm   vfarcic/docker-flow-proxy
docker service create --name app1 --replicas 2 --network app1-net --network proxy  -e spring.profiles.active=prod dockerrepo.ourcomp.com/app1
docker service create --name app2 --replicas 1 --network proxy dockerrepo.comp.com/app2
docker service create --name app3 --replicas 2 --network proxy swaggerapi/swagger-editor
```

Then the (manual) proxy setup. `Curl` was executed on one of the manager nodes. 
```
curl "http://127.0.0.1:8080/v1/docker-flow-proxy/reconfigure?serviceName=app1&servicePath=/&serviceDomain=app1.com&port=8080&distribute=true"

curl "http://192.168.200.120:8080/v1/docker-flow-proxy/reconfigure?serviceName=app2r&servicePath=/&serviceDomain=app2.com&port=8888&distribute=true"

curl "http://127.0.0.1:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&servicePath=/&serviceDomain=swagger-editor.com&port=8080&distribute=true"

```

Domain names were added to local machine hosts file for testing.

**Comment by vfarcic** [comment]
I just executed (almost) the same commands. I only changed the image with the one I often use for testing. I sent around 100 requests to each of the services and the response was always 200. I also checked logs of the services and requests were always forwarded to the correct service and load balanced across different instances.

My guess is that the problem is somehow related to your environment. Can we have a Skype or HangOuts call and share your screen? I think we'll advance much faster that way.

**Comment by demaniak** [comment]
Thank you @vfarcic - let me tear down my setup, and setup from scratch again, and see what happens then.
It is POSSIBLE we are having UDP traffic issues between the data centers.
If still no luck, I might take you up on the screen share suggestion.

On a possible related note, I started playing with the automated setup also, and I was watching the logs of the swarm-listener service - apparently it is not able to connect to the proxy service (or now and then it CAN, but gets a 404). 
This would suggest networking issues between the swarm nodes, don't you think?

Since you can confirm no obvious reproducible issues, I will close this issues for now.
I will comment here with further outcomes on my side.

Thanks again for the effort.

**Comment by vfarcic** [comment]
If the message from the listener was something like "Notification to <URL> failed. Retrying...", it's normal. As soon as a service is created, listener starts sending notifications to the proxy. However, even though the service is created, it might take some time until containers are actually up and running. In such a case, the listener will retry notifications until one of the are successful (or a certain number of retries is exhausted).

On the other hand, that might not be the case you're experiencing. Can you me a sample from the listener logs?

**Comment by demaniak** [comment]
Ok, so I now did the following:

1.  removed all services from the cluster
2. removed all overaly networks
3. bounced all the swarm nodes (thanks ansible!)
4. created overlay networks for all target services (even if they don't actually have any other related services)
5. created swarm-listener service
6. created proxy service
7. created two different services (both on port 8080), using different domains for the`serviceDomain` label. Both services are connected to `proxy` network, and their own seperate overlay networks.

Aaaaaaaaand everything is working as expected.

So far so good.

As for logs - unfortunately I destroyed the containers before thinking of grabbing logs. What I can say is that the "Retrying..." loop was running, but every Nth attempt would results in a 404. Manually calling the url (from in the running container) also resulted in 404. Not sure what to make of it, but I think this is docker/environment related (as you suspected).

So, CURRENTLY, with the third service I'm bringing up (port 8888), things are taking long. So the listener started with it's "Retrying..." loop, but then hit a 500, and stopped. So I assume the service is NOT configured in th proxy.
Logs:
```
2016/10/19 14:59:42 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 14:59:47 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 14:59:52 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 14:59:57 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 15:00:02 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 15:00:07 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 15:00:12 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 15:00:17 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 15:00:22 Notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true failed. Retrying...
2016/10/19 15:00:27 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app3&port=8888&serviceDomain=app3.comp.com&servicePath=/&distribute=true returned status code 500
```

**Comment by vfarcic** [comment]
Listener retried request for ten times and, finally, gave up. That means that the proxy was returning an error message.

Before we start debugging it, can you please confirm that the serviceDomain should indeed be app3.comp.com (twice .com)?

**Comment by demaniak** [comment]
Hah, made up domain names - that's `app3.comp.com` - `comp` short for "company". We can change it if you prefer.

After the containers were up for the app3 service, I could manually call the configuration end point on the proxy, and it worked fine. What confused me - previously (before the tear down), trailing the swarm-listener logs, it seemed that it never gave up? 

I'm leaving for home now, but if you would like me to try anything specific debugging-wise, please comment here. I might be able to do something tonight, otherwise tomorrow morning some time.

**Comment by vfarcic** [comment]
There are two possibilities. Either the listener never managed to reach the proxy or it and the proxy failed to reconfigure itself. We can see which case it is through the proxy logs. Please wait until the listener gives up (or reports at least a few retries), get the logs from the proxy, and paste them here.

**Comment by demaniak** [comment]
I will do so as soon as possible - just hit some work pressures currently.

Thanks!
