### ISSUE TITLE
Question: general question & docker-machine in the scripts

### ISSUE THREAD

**Issue by hamburml** [vfarcic/docker-flow-proxy#58]
Hi!

I am in search for a automatic proxy solution for docker 1.12+. I want to use docker engine swarm (not docker swarm) to reliable host websites. I want to use three swarm manager and n swarm workers. When browsing the swarm managers ips I can reach the website. Now I want that when using a domain it should be load balanced between all three swarm managers and when one is down it is removed from the load balancing. As far as I know docker-flow-proxy can provide this! Additionally I need letsencrypt for https and automatic renewel. This should be possible, right?

I would like to try it out but then I saw that inside the swarm-cluster.sh docker-machine is used to create docker container. I installed docker 1.12 on debian 8.6 but I do not have docker-machine as a command. Could it be that the scripts inside of docker-flow-proxy/scripts/ are not updated to work with docker 1.12+ or do I need to install something else?

Thanks for helping and keep up the good work 👍

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I had too many things to take care of...

The swarm-cluster.sh is only an example of a quick way to create a demo cluster. Normally, you'd use different tools to create a fully operational cluster for product. My favourite combination is Packer with Terraform but that can be anything else.

Can I recommend [The DevOps 2.1 Toolkit: Docker Swarm](https://leanpub.com/the-devops-2-1-toolkit)? It contains all the information you'll need to run Swarm services.

Once your Swarm cluster is running, you can use the **Docker Flow: Proxy** (probably together with **Docker Flow: Swarm Listener** to have a dynamic proxy that will reconfigure itself whenever a new service is created or an existing one is removed. The proxy is not coupled with any specific way of creating a cluster. It should work no matter how you got there.

Feel free to ping me on Skype (user: vfarcic) or HangOuts (user: viktor@farcic.com) and I'll walk you through the process of creating the cluster and putting the proxy on top of it.

**Comment by Michael-Hamburger** [comment]
Thanks for answering and the link to the DevOps 2.1 Toolkit.

Currently I do something else but when I work on that matter again I will come back to you!

**Comment by vfarcic** [comment]
Sorry for not responding earlier. Please ping me on Skype (user: vfarcic) or HangOuts (user: viktor@farcic.com) and we'll take a look at your problem together.

**Comment by vfarcic** [comment]
I think we resolved this issue through chats and email. Please reopen it if I'm wrong.
