### ISSUE TITLE
Support for regex paths

### ISSUE THREAD

**Issue by wilkko** [vfarcic/docker-flow-proxy#6]
It seems that HAProxy inside docker-flow-proxy is always configured with `path_beg`. We have a microservice that has a RESTful path only resolvable with `path_reg`.

**Comment by vfarcic** [comment]
Would it suit you if path_reg is used for all services or it should differ from one service to another?

**Comment by wilkko** [comment]
It differs from service to service. Mostly path_beg is fine but for this particular service both path_beg and path_reg needs to be registered. I can paste examples tomorrow if needed.

**Comment by vfarcic** [comment]
I'll have it done soon. Would you might testing it?

**Comment by wilkko** [comment]
Thanks! I can test it but it might take a week or two before I can get back into the context of re-deploying those backend services.

**Comment by vfarcic** [comment]
The feature has been added. You can use pathType query to specify a different configuration. See the [Usage](https://github.com/vfarcic/docker-flow-proxy#usage) for more info.

Please let me know it this addition fixed your problem.
