### ISSUE TITLE
password protect only some routes

### ISSUE THREAD

**Issue by no-more** [vfarcic/docker-flow-proxy#61]
Hi,

I was wondering if it was possible to add a user/password request on some routes (not all).

Thanks.

**Comment by vfarcic** [comment]
This feature was added to the release 1.105. Please consult the [Release Notes](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.105) for more info.

I would appreciate if you could try it out and let me know if the current implementation matches your use-case.
