### ISSUE TITLE
[Feature request] json configuration output for config endpoint

### ISSUE THREAD

**Issue by joke** [vfarcic/docker-flow-proxy#63]
Hi,

it would be cool to add an option to the /config endpoint. This way it would be possible to query the endpoint and generate a listing of the current domain to service mappings. This could be used for monitoring software like Kibana for example.

Regards
Joke

**Comment by vfarcic** [comment]
Sorry for not responding to this issue earlier.

I'm currently in the process of moving everything from configuration files to in-memory structures. Once that is done, it'll be trivial to output configs as JSON.

**Comment by vfarcic** [comment]
`type` parameter was added to the `config` endpoint some time ago and I forgot to update this issue. After a very long delay, the feature is now available. Please see [http://proxy.dockerflow.com/usage/#config](http://proxy.dockerflow.com/usage/#config) for more info.
