### ISSUE TITLE
Rewrite servicePath to rewritePath if available

### ISSUE THREAD

**Issue by barhun** [vfarcic/docker-flow-proxy#64]
Hi,

First of all, this is one of the best projects out there which save me so much time being free of hassle. (: Yet, one functionality I'd like to be able to make use of seems missing. Here it is: I want the proxy to match a service with the beginning of the request path as it's already been possible and rewrite the path before forwarding the request to the matching service as follows:

```
docker service create --name go-demo \
    -e DB=go-demo-db \
    --network go-demo \
    --network proxy \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/demo/* \
    --label com.df.rewritePath=/* \
    --label com.df.port=8080 \
    vfarcic/go-demo
```

This would forward requests for http://domain/demo/ to http://serviceName/ and some other requests for http://domain/demo/admin to http://serviceName/admin. I've browsed through the articles in this repo and performed some searches but found out no way to rewrite request paths. Is this functionality available or do you have any plans about it?

**Comment by vfarcic** [comment]
This is definitely a good feature to add. I'm a bit overwhelmed with work right now. I'll do my best to implement it as soon as I can.

**Comment by jmkhael** [comment]
I've tried to put [Portainer ](https://github.com/portainer/portainer)/ [Visualizer](https://github.com/ManoMarks/docker-swarm-visualizer) behind docker-flow-proxy, but couldn't make them work... I suspect some path rewrites would make it work.

**Comment by Xustyx** [comment]
@jmkhael 
Hi, you must read this -> https://github.com/portainer/portainer-docs/blob/master/docs/source/faq.rst#how-can-i-configure-my-reverse-proxy-to-serve-portainer-using-haproxy

I solved creating a pair of templates on `/consul-template` dir.

If you reconfigure service via api, the api parameters "consulTemplateBePath" and "consulTemplateFePath" need to point your template files.

Else, if you use swarm-listener, you must add labels to service like this.
--label com.df.consulTemplateFePath=/consul_templates/[FE template path]
--label com.df.consulTemplateBePath=/consul_templates/[BE template path]

The only problem here is that templates are statics and you can't profit for other services.
Now I'm looking the code to make this possible creating an independent function for parse the templates like auto-generated config.

Look this functions:
https://github.com/vfarcic/docker-flow-proxy/blob/master/reconfigure.go#L264
https://github.com/vfarcic/docker-flow-proxy/blob/master/reconfigure.go#L281

Only auto-generated replace the parameters with "Execute" method and this can be in other function to use the replace after template loaded. Then we can create parametrized templates or satatics.
```go
tmplFront, _ := template.New("consulTemplate").Parse(srcFront)
tmplBack, _ := template.New("consulTemplate").Parse(srcBack)
var ctFront bytes.Buffer
var ctBack bytes.Buffer
tmplFront.Execute(&ctFront, sr)
tmplBack.Execute(&ctBack, sr)
return ctFront.String(), ctBack.String()
```

Good Job @vfarcic ;)

**Comment by Xustyx** [comment]
Ping @fuertesb :)

**Comment by jmkhael** [comment]
@Xustyx thank you for the message and the links.
I am using Docker Flow Proxy without Consul, a.k.a. with the [New Swarm Mode](https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode-listener.md). Is there a way to set templates for this mode too?

**Comment by Xustyx** [comment]
@jmkhael 

Yes, it's the second way that I posted.

> Else, if you use swarm-listener, you must add labels to service like this.
> --label com.df.consulTemplateFePath=/consul_templates/[FE template path]
> --label com.df.consulTemplateBePath=/consul_templates/[BE template path]

**Comment by jmkhael** [comment]
Great, i'll give it a go. the consul part in the commands and labels mislead me :)

**Comment by Xustyx** [comment]
@jmkhael 

Yeps, the label keys are not appropriate at this point, because consul is not needed now, and I use image path `/consul_templates`  but you can store your templates in other.

Remember map the directory with templates with image path with mount, or build a new docker image adding the templates.

```sh
docker service create \
--name proxy \
-p 80:80 \
-p 443:443 \
--network proxy \
--constraint 'node.labels.nas == templates' \
--mount type=bind,src=/home/docker/templates,dst=/consul_templates \
-e MODE=swarm \
-e LISTENER_ADDRESS=swarm-listener \
vfarcic/docker-flow-proxy
```

**Comment by vfarcic** [comment]
@Xustyx You're right. The directory name is not appropriate anymore. It all started with Consul and evolved from there. I should probably change the name to /templates in one of the next releases.

**Comment by vfarcic** [comment]
I just added the ability to rewrite paths. It is available in the release 1.111.

Please see [Rewriting Paths](https://github.com/vfarcic/docker-flow-proxy/blob/master/articles/swarm-mode-listener.md#rewriting-paths) section of the documentation for more info.

I'd appreciate any feedback you might give on this feature. Please try it out and let me know if you notice any problems or have a suggestion for improvement.

**Comment by barhun** [comment]
Hey @vfarcic,

Thank you very much for implementing this feature, it works like a charm! I've just tried using the following services to test the proxy while rewriting paths and there seems to be no problem.

```bash
docker service create --name swarm-listener \
    --network proxy \
    --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
    -e DF_NOTIF_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure \
    -e DF_NOTIF_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove \
    --constraint 'node.role==manager' \
    vfarcic/docker-flow-swarm-listener


docker service create --name proxy \
    -p 80:80 \
    -p 443:443 \
    --network proxy \
    -e MODE=swarm \
    -e LISTENER_ADDRESS=swarm-listener \
    vfarcic/docker-flow-proxy


docker service create --name blue \
    --replicas 3 \
    --network proxy \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/blue/ \
    --label com.df.reqRepSearch='^([^\ ]*)\ /blue/(.*)' \
    --label com.df.reqRepReplace='\1\ /\2' \
    --label com.df.port=80 \
    nginx:alpine \
    sh -c "echo blue:\$(hostname) > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"


docker service create --name green \
    --replicas 3 \
    --network proxy \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/green/ \
    --label com.df.reqRepSearch='^([^\ ]*)\ /green/(.*)' \
    --label com.df.reqRepReplace='\1\ /\2' \
    --label com.df.port=80 \
    nginx:alpine \
    sh -c "echo green:\$(hostname) > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
```

**Comment by vfarcic** [comment]
Are you implementing blue/green deployment with Swarm?

**Comment by barhun** [comment]
No, it was just for testing, nothing relevant to do with any deployment strategy. They might have been named _red_ and _black_ if I just wanted. (:

**Comment by barhun** [comment]
Hi again, @vfarcic

It may still be a better choice to use a directive such as `http-request set-path %[path, regsub({{.ReqPathSearch}}, {{.ReqPathReplace}})]` instead because `regrep ...` scans the entire request buffer searching for regex matches while `http-request set-path ...` directive does only a quick scan of the request path.

Note: The _regsub_ function handles arguments doing the same operation as the well-know _sed_ utility with `"s/<regex>/<subst>/"` so it differs from _regrep_ that handles arguments as PCRE by default. There is a flag for _regsub_ known as _-r_ to enable extended regex handling which may come handy in some cases but I think basic replace functionality will meet the requirements for most of the use-cases.

regsub: https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#regsub
Set the URL path: https://www.haproxy.com/doc/aloha/7.0/haproxy/http_rewriting.html#set-the-url-path
PCRE Regex to SED: http://stackoverflow.com/a/24832550/1973424

**Comment by vfarcic** [comment]
You're right. It should be better if we replace it with `http-request`. Would you like to give it a try and submit a pull request?
