### ISSUE TITLE
Timeout configuration?

### ISSUE THREAD

**Issue by demaniak** [vfarcic/docker-flow-proxy#68]
Hi.
What is the default timeout for forwarded requests (if anything).

And if there IS a timeout, would it be possible to make it configurable?

Thanks!

**Comment by vfarcic** [comment]
The release 1.103 added the option to modify default timeout values using environment variables.

Please see the [release notes](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.103). The list of environment variables is in [container config](https://github.com/vfarcic/docker-flow-proxy#container-config). It contains the list of `TIMEOUT` variables, with a short description and default values.

Can you please try out the release `vfarcic/docker-flow-proxy:1.103` and let me know whether that's what you were looking for?

**Comment by demaniak** [comment]
Will do, thank you very much!

**Comment by demaniak** [comment]
Closing for now, will re-open if 1.103 is perhaps not what we are looking for :)

**Comment by demaniak** [comment]
Just confirming - this definitely seems to be working, thanks very much!
