### ISSUE TITLE
serviceDomain with multiple values

### ISSUE THREAD

**Issue by rsalimian** [vfarcic/docker-flow-proxy#69]
we need to be able point multiple domain(subdomain) to same service.
tried to do as comma separated or separated labels and didn't work:
 
`--label com.df.serviceDomain=my1.domain.com, my2.domain.com`

`--label com.df.serviceDomain=my1.domain.com
--label com.df.serviceDomain=my2.domain.com`

**Comment by rsalimian** [comment]
any ETA to have this?

**Comment by vfarcic** [comment]
It'll be done before the end of this week.

**Comment by ali-maraschi** [comment]
Looking forward to using this feature too :+1:

**Comment by marascha** [comment]
Supporting regular expressions (or wildcards) would also be a great extension here.

**Comment by vfarcic** [comment]
The feature to specify multiple domains was added to the release 1.108. 

Multiple domains should be separated with comma (`,`). For example: `--label com.df.serviceDomain=my-domain.com,my-other-domain.com`.

Can you please try it out and let me know whether it works as you expected.

@marascha The initial feature request to support multiple domains is implemented. Can you please create a separate for using regular expressions?
