### ISSUE TITLE
ServiceDomain concept not clear

### ISSUE THREAD

**Issue by tazle** [vfarcic/docker-flow-proxy#7]
README.md says "Optionally, serviceDomain can be used as well. If specified, the proxy will allow access only to requests coming from that domain. The example that follows sets serviceDomain to my-domain-com. After the proxy is reconfigured, only requests for that domain will be redirected to the destination service."

Note "requests coming from that domain".

Should perhaps say "Optionally, serviceDomain can be used as well. If specified, the proxy will allow access only to requests coming to that domain. The example that follows sets serviceDomain to my-domain-com. After the proxy is reconfigured, only requests for that domain will be redirected to the destination service."

**Comment by vfarcic** [comment]
You're right. Thank you for spotting it.
