### ISSUE TITLE
Ability to set custom error pages in proxy

### ISSUE THREAD

**Issue by michaelwilde** [vfarcic/docker-flow-proxy#77]
As a docker administrator there are times when i might be restarting services, or a user may enter a hostname that doesn't exist.  by default HAproxy puts a simple default error in the browser.

It is desirable to have control over that error page.  Perhaps with a file we copy in, or even as a command line switch.   Would like to make a pretty error page.

**Comment by vfarcic** [comment]
Done as release [1.124](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.124). Please let me know if you experience any problem or have a suggestion how to improve it.
