### ISSUE TITLE
Race condition in reconfigure.go createConfig()

### ISSUE THREAD

**Issue by tazle** [vfarcic/docker-flow-proxy#8]
It seems that createConfig() in reconfigure.go (https://github.com/vfarcic/docker-flow-proxy/blob/6d7749e67a52560923ebc350adde7bd7c8308e05/reconfigure.go#L56) has a race condition. I

It uses one hard-coded path for the Consul template generated for different services, and concurrent calls may end up using corrupt or just plain wrong template. Using a proper temporary file should solve this.

**Comment by vfarcic** [comment]
You're right. There can be a race condition. Actually, I think that there are few other places where it can happen as well.

1. [reconfigure.go#L68](https://github.com/vfarcic/docker-flow-proxy/blob/race-condition/reconfigure.go#L68) writes Consul template.
2. [reconfigure.go#L69](https://github.com/vfarcic/docker-flow-proxy/blob/race-condition/reconfigure.go#L69) executes Consul template which creates another file.
3. [reconfigure.go#L72](https://github.com/vfarcic/docker-flow-proxy/blob/race-condition/reconfigure.go#L72) Concatenates all configs into a single HAProxy config (unlike nginx, HAProxy does not allow includes).
4. [reconfigure.go#L58](https://github.com/vfarcic/docker-flow-proxy/blob/race-condition/reconfigure.go#L58) Reloads

All those should probably be locked into a single lock as in [reconfigure.go#L53](https://github.com/vfarcic/docker-flow-proxy/blob/race-condition/reconfigure.go#L53).

What do you think?
