### ISSUE TITLE
Sticky session?

### ISSUE THREAD

**Issue by igorspasic** [vfarcic/docker-flow-proxy#83]
Using Swarm DNS load balancer you can't have sticky session.

**Comment by vfarcic** [comment]
You cannot have sticky sessions with Docker's Overlay network. You can accomplish sticky sessions with a different networking (or no networking at all). In that case, you could use the proxy with Consul for service discovery.

**Comment by igorspasic** [comment]
Ok. If I have a Swarm v1.12, who would notify consul about docker container being created on certain host? Polling swarm services would require additional poling for each services tasks (in other words: `docker service list`; for each service: `docker service ps`) - wouldn't that be too much for large swarm?

I could listen to docker events, but I would like not to; as there is no filtering for swarm (so I can listen only create/destroy) and they are not that reliable yet (flow can stop after some time).

What is your proposal with this? I was thinking in using autopilot pattern and having each container register itself into the consul on startup.

**Comment by vfarcic** [comment]
If you don't use Swarm's Overlay network, you would probably need to get information about individual containers, not services. That would also mean that you'd need to expose ports to all services. Before the new Swarm, I used [Registrator](https://github.com/gliderlabs/registrator) to get the information about containers and store it in Consul. It would need to run on each node so you should probably run is as `--mode global`. Please try it out and let me know if it worked.

P.S. I would probably try to get rid of sticky sessions and store them in Reddis or a similar DB. That way you'd become independent of a specific instance and can leverage Swarm features like failover, load balancing, and so on.

**Comment by igorspasic** [comment]
Thanx, will close this now.

**Comment by igorspasic** [comment]
Btw, Registrator does not work with the new swarm mode as it ignores the services that does not publish port on its host.

**Comment by vfarcic** [comment]
True. Even if it would work with services that do not publish any ports that would not solve your problem. If you use Docker Overlay networking, you have to use load balancing and cannot have sticky sessions. That means that the only option you have is not to use the network. In that case, you'll have to publish ports.

**Comment by igorspasic** [comment]
Thats what I thought :) Let me expand this subject a bit, if I may.

We want to use Swarm Mode. However, after very simple tests we figured that networks in Swarm Mode are not scalable: performance is slow and you can't create many networks - or join many services into one network. We tried on AWS and on inhouse servers, the results were simple bad: I crashed beyond repari (!) the whole swarm cluster just by creating 200 (!) apps+networks. (Interesting is that on Joyent infrastructure, the behavior was fine). Long story short, we decide to try without any docker swarm networking; in that case swarm works fine :)

Now, without network, we need some type of Registrator for the services. Tried to use the Glides, but it simply ignores containers that are created by swarm, because the ports are _not_ published. Yes, even when I say `-p` for the service, it is not published in the same way as you do with `docker run`. Looks like https://github.com/gliderlabs/registrator/pull/476/commits/6d8b69e3eef1d8e816072ce9a7ac6093dc9bbd5c will solve it, unfortunately Glider is not maintained well.

So what we can do is:

+ home made Registrator (for each swarm node) that listens to events and registers correctly. The challenge is to figure the service port
+ To use some kind of autopilot inside image that will notify Consul when task is up/down; however: this requires custom images.
+ to scan the complete swarm periodically (like you do in the `listener`) and to store information in the Consul, that will then reload HA. I like this one as it does not depend on swarm events, I just am worried about performances when number of services goes up. So far as I saw, docker list services fast, even in case when `docker ps` takes minute(s) to respond.

**Comment by vfarcic** [comment]
The third option should not be a problem. I can the option to store service info in Consul. I think I can have it done during the next week. You're welcome to make a pull request as well.

**Comment by igorspasic** [comment]
Hey @vfarcic , just a note: the lookup we were talking about (one that scans tasks so they can be registered as services in eg Consul) can be done only after docker 1.13 (the way ports are exposed etc).

One question: if we make a listener for task changes (like I said, this listener would need to scan changes in tasks, not only services) - why we would need Consul anyway? In other words, why:

    listener -> consul <- haproxy

when we can say:

    listener -> haproxy

and remove the need for Consul component?

**Comment by vfarcic** [comment]
There's no need for Consul if we adapt the listener. I suggested Consul initially as the only possible way to do this without modifying the listener and/or the proxy.
