### ISSUE TITLE
Frontend to Backend port mapping

### ISSUE THREAD

**Issue by lhenry7** [vfarcic/docker-flow-proxy#86]
My question is similar to #59 and #75, in that I want frontend port 80 to proxy to service port :80, and frontend:443 to proxy to service :443. Even potentially by specifying the port mapping(as an envvar), similar to the docker --port option (-p 80:80 -p 443:443). Is this achievable with custom templates? Or any other way to accomplish this?

**Comment by vfarcic** [comment]
The release [1.123](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.123) adds this feature through the `httpsProxy` parameter. You'll need to [put a certificate](https://github.com/vfarcic/docker-flow-proxy#put-certificate) for SSH traffic to work.

Please try it out and let me know if you experience any problem.

**Comment by lhenry7** [comment]
This looks like it would work, but one problem: You've added a "mode https" to the https backend, but https option is invalid on "mode". Just make it http and I think this will work perfectly.

From proxy logs:
[ALERT] 353/161452 (109) : parsing [/cfg/haproxy.cfg:55] : unknown proxy mode 'https'.
[ALERT] 353/161452 (109) : parsing [/cfg/haproxy.cfg:63] : unknown proxy mode 'https'.
[ALERT] 353/161452 (109) : Error(s) found in configuration file : /cfg/haproxy.cfg
[ALERT] 353/161452 (109) : Fatal errors found in configuration.

**Comment by vfarcic** [comment]
Sometimes I am too confident in automated tests and do not check the feature manually. Sorry for that.

I just pushed the fix. Can you pull the latest version and let me know if it works as expected?

**Comment by lhenry7** [comment]
Yes, the mode http is fixed, the config looks good. I'll try and do more testing here before the holidays.

Thanks!!

**Comment by lhenry7** [comment]
After more testing,  I’ve discovered that if I start the proxy with -p 31000:80 (instead of 80:80) the dst_port value is now going to be 31000, which causes the acl to be false.

This isn’t exactly what I wanted. If haproxy receives on container port 80, proxy to port 80 backend (regardless of what the server mapping port is). I think using src_port instead would  be more accurate.  If you agree, can you make this change?

More background on what I’m doing: I have a set of services running on one overlay network and a second set on a different overlay network, so I’m starting 2 copies of the proxy-listener and the proxy. Since the 2nd proxy needs to be on some server ports other that 80 and 443, I want the container ports to control the BE ports for proxy.


Larry Henry
Lead Systems Analyst -  Digital Strategy Group Architecture Digital Thread GE

T 734 641 2415
F 734 727 5420
M 734 502 9855
Larry.Henry@ge.com<mailto:Larry.Henry@ge.com>

Grace Lake Corporate Center
One Village Center Drive
Van Buren Twp, Michigan 48111
General Electric Company

GE imagination at work

**Comment by vfarcic** [comment]
You're right. That was an overlook on my part. It should be src_port.

New release with the fix will be available in a few minutes. Please try it out and let me know if it worked.
