### ISSUE TITLE
Feature Request - Wildcard domain support

### ISSUE THREAD

**Issue by getvivekv** [vfarcic/docker-flow-proxy#87]
This is a usecase in which we need wildcard domain support in the docker flow proxy. 

Example,

We need to be able to add 2 domains in the `serviceDomain` parameter such as 

```
username.domain.com
*.username.domain.com
```

Our application is a Magento installation in which one user can have unlimited number of sub-domains such as 

```
subdomain1.username.domain.com
subdomain2.username.domain.com
subdomain3.username.domain.com
```

All these subdomains must be pointed to the container of `username.example.com` user. It would great if we can have this feature added to docker proxy instead of messing up with the haproxy config manually by a user and maintaining a separate configuration.

**Comment by vfarcic** [comment]
Please take a look at the [release 1.122](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.122).

Can you try it out and let me know whether it works as you expected?

**Comment by getvivekv** [comment]
Works!
