### ISSUE TITLE
Support for multiple proxied ports per container -- specified at runtime

### ISSUE THREAD

**Issue by michaelwilde** [vfarcic/docker-flow-proxy#89]
As a devops admin, an app i have has a few ports that *can* be opened my app container.
My app listens on port 8000 (web front end), 8089 (https api port) and a few others. 

Normally, i launch my docker service so that Docker Flow: Proxy sets domain, port, path. (like this)

> docker service create  --with-registry-auth --name splunk-reporter \
>   -e SPLUNK_START_ARGS="--accept-license" \
>   --network splunkoxygen \
>   --network proxy \
>   --label com.df.notify=true \
>   --label com.df.distribute=true \
>   --label com.df.serviceDomain=reporter.demo.splunkoxygen.com \
>    --label com.df.servicePath=/ \
>   --label com.df.port=8000 \
>   registry.splunk.com/splunk/splunk:latest 

 

It is desirable to be able to open up a second or third port and have it proxied.  In this case, i'd like to proxy https port 8089 along with http port 8000.   Port 8000 gets proxied thru port 80.  It would be good if i could open 8089 on the front end for my domain name and have it shoot to port 8089 on the proxied container.

Perhaps via another --label? or an environment variable. If one was going to proxy multiple ports, we would need to be able to direct each frontend port to a different back end port.

**Comment by vfarcic** [comment]
A few days ago I made the [release 1.123](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.123) that adds the option to specify https port as a separate parameter. It is one of the [reconfigure](https://github.com/vfarcic/docker-flow-proxy#reconfigure) parameters. 

Can you please let me know if that solves your problem or you had something else in mind?

**Comment by michaelwilde** [comment]
That may solve some problems, but not specifically what i'm thinking.

If i have 3 frontend services 80 (http), 443 (https), 8089 (https), i'd need to be able to map a container to a port, and potentially a container to multiple ports. I can't add multiple labels for ports, can i?

**Comment by vfarcic** [comment]
Just to clarify... Are there three services, or one service listening to three ports?

**Comment by michaelwilde** [comment]
Three services…   lets say technically two but possibly more…

SplunkWeb (interface) usually runs on port 80, but if configured, it could run https on 443 – so that’s easy
splunkdAPI port – always runs on port 8089 https – example:  https://demo-oi3.splunkoxygen.com:8089

(in theory, one could also open up a few other ports that are technically services in splunk – 9997 receiving forwarded data, 8081 https Event Collector API)

- wilde

**Comment by vfarcic** [comment]
Do those services have a unique path (e.g. /foo, /bar, etc), or they might potentially send requests to the same path (e.g. /)?

**Comment by vfarcic** [comment]
What would help me understand is to make some kind of a map. For example,

|proxy   |service name|service listens|
|:80/foo|service-1      |:8080/foo        |
|:80/bar|service-2     |:8080/bar        |
...

**Comment by vfarcic** [comment]
The feature is done and passed automated tests. There's only one task left before I release it. I need to run a few manual tests with a live service. The problem is that I don't have any service that listens to multiple ports. All those that I have are a microservice/single-process/single-port type of services.

Do you have some service that I could use for testing this feature? That would save me from writing a demo app just for this issue.

**Comment by michaelwilde** [comment]
@vfarcic ... apologies for not answering your comment from the other day...  Service map would be:
proxy = :80/ --> service listens :8000/  
proxy = :8089/ --> service listens :8089/  
servicename = mysplunk
servicedomain = mysplunk.whatever.com

wanna try a service... run this.

>  docker service create  --name splunk-reporter \
>   -e SPLUNK_START_ARGS="--accept-license" \
>#put your switches in here
> registry.splunk.com/splunk/splunk:latest

**Comment by vfarcic** [comment]
I created the service you requested:

```bash
docker service create --name splunk-reporter \
    -p 8000:8000 -p 8089:8089 \
    -e SPLUNK_START_ARGS="--accept-license" \
    registry.splunk.com/splunk/splunk
```

First I want to confirm it works and that I can test whether the ports are open. Later on, I'll integrate it with the proxy.

What would be the easiest way to confirm that 8089 works? Is there a simple request I can send to that port?

**Comment by michaelwilde** [comment]
just curl it.  https://name:8089 admin/changeme is default pw.  Basic with.

-




On Sat, Dec 24, 2016 at 3:22 PM -0600, "Viktor Farcic" <notifications@github.com<mailto:notifications@github.com>> wrote:


I created the service you requested:

docker service create --name splunk-reporter \
    -p 8000:8000 -p 8089:8089 \
    -e SPLUNK_START_ARGS="--accept-license" \
    registry.splunk.com/splunk/splunk

First I want to confirm it works and that I can test whether the ports are open. Later on, I'll integrate it with the proxy.

What would be the easiest way to confirm that 8089 works? Is there a simple request I can send to that port?

**Comment by vfarcic** [comment]
I entered into some kind of a loop I cannot get out. I'm sure I'm missing something but I don't know what that is. Would you have a bit of time to go through it with me? You might spot something I haven't seen.

The commands that should make it work are as follows.

```bash
docker service create --name swarm-listener \
    --network proxy \
    --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
    -e DF_NOTIF_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure \
    -e DF_NOTIF_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove \
    --constraint 'node.role==manager' \
    vfarcic/docker-flow-swarm-listener

docker service create --name proxy \
    -p 80:80 \
    -p 443:443 \
    -p 8080:8080 \
    -p 8089:8089 \
    --network proxy \
    -e MODE=swarm \
    -e LISTENER_ADDRESS=swarm-listener \
    -e BIND_PORTS=8089 \
    docker-flow-proxy
```

**Comment by michaelwilde** [comment]
Viktor... In my testing i can confirm 

The frontend from 80 --> backend 8000 http works (splunk ui comes up).

What I noticed is that when you go frontend 443/https to backend 8089/https it can't get a secure connection.

When i try proxying 8089/https to 8089/https, it also doesn't work.  (i think on this particular one, its because the backend rule is configured by default to mode http.

 
/cfg/tmpl # more splunk-reporter-be.cfg

```
backend splunk-reporter-be8089
    mode http
    server splunk-reporter splunk-reporter:8089
backend splunk-reporter-be8000
    mode http
    server splunk-reporter splunk-reporter:8000
```

**Comment by vfarcic** [comment]
I think I know what the problem is. I need to deverlop the option to add SSL certificates to ports other than 443. Can you confirm that you tested 443>8089 with a valid certificate?

**Comment by michaelwilde** [comment]
Its just the default self-signed cert that comes with splunk.

- wilde

**Comment by vfarcic** [comment]
Can you send me proxy config (when you have time, it's not urgent)?

**Comment by michaelwilde** [comment]
```
swarm:Users thewilde$ curl "http://localhost:8080/v1/docker-flow-proxy/config"
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-server-close
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout http-request 5s
    timeout http-keep-alive 15s

    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats auth admin:admin
    stats uri /admin?stats

frontend services
    bind *:80
    bind *:443
    mode http

    bind *:8089


    acl url_splunk-reporter8089 path_beg /
    acl srcPort_splunk-reporter443 dst_port 443
    acl url_splunk-reporter8000 path_beg /
    acl srcPort_splunk-reporter80 dst_port 80
    use_backend splunk-reporter-be8089 if url_splunk-reporter8089 srcPort_splunk-reporter443
    use_backend splunk-reporter-be8000 if url_splunk-reporter8000 srcPort_splunk-reporter80


backend splunk-reporter-be8089
    mode http
    server splunk-reporter splunk-reporter:8089
backend splunk-reporter-be8000
    mode http
    server splunk-reporter splunk-reporter:8000
```

**Comment by vfarcic** [comment]
I think that the problem is SSL. On one hand, proxy accepting HTTPS requests expects a valid certificate (which you don't have). On the other hand, if you send an HTTP (without S) request, your service expects a certificate.

Let's touch base when you get a bit of free time. Maybe after holidays?

**Comment by morph027** [comment]
Stumbled upon the same...first of all, thanks for this awesome project.

My app is even worse, right now it needs 5 ports (don't ask why ;) )...

Might be worth to passthrough all traffic and play load-balancer only, see _HAProxy with SSL Pass-Through_ here: https://serversforhackers.com/using-ssl-certificates-with-haproxy

**Comment by vfarcic** [comment]
@morph027 The option to have multiple ports for each service was added to the [release 1.133](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.133) a few weeks ago. Does that solve your problem?

@michaelwilde I just added the reconfigure parameter `httpsOnly`. That will redirect any HTTP request to HTTPS. Does that solve your problem?

**Comment by michaelwilde** [comment]
@vfarcic doing some testing today.. it should.  I'll file if not.

**Comment by morph027** [comment]
@vfarcic : Uh, didn't saw this. I'll have a look later, thanks!

**Comment by morph027** [comment]
Hell yes, multiple

```
--label com.df.servicePath.x=/ \
--label com.df.port.x=$port \
--label com.df.srcPort.x=$port \
```

together with ```-e BIND_PORTS=5000,8082,8084,8086,...``` worked out for me :+1: 

Thank you!

**Comment by vfarcic** [comment]
@morph027 You can use TCP for SSH access. Please let me know if you have any problem with it and I'll write an example in the documentation.

@michaelwilde I'll close the ticket. Feel free to reopen it if your tests failed.
