### ISSUE TITLE
Support for authenticated paths

### ISSUE THREAD

**Issue by wilkko** [vfarcic/docker-flow-proxy#9]
We have a microservice that uses basic auth (right or wrong) in some of it's resource paths. Docker flow proxy seems to let HAProxy to do health checking for the path to be proxied. Consul is already doing health checking for us and we give it an unauthenticated path (Spring boot health actuator endpoint) with Registrator. We used to run Consul template in deamon mode so that unhealthy services were not offered by Consul template and HAProxy check could be turned off. I know it's not the same as letting HAProxy verify each path but it's close. Other option would be to provide credentials or custom health check URLs to HAProxy.

**Comment by vfarcic** [comment]
A new query param skipCheck has been added. See the [Usage](https://github.com/vfarcic/docker-flow-proxy#reconfigure) section for more info.

Please reopen this issue if the fix does not solve your problem.
