### ISSUE TITLE
Proxy - Force Reload

### ISSUE THREAD

**Issue by getvivekv** [vfarcic/docker-flow-proxy#91]
Hello

Starting to test this with 5-10 domains. I've been seeing that even though the haproxy configuration is updated when new containers are created, it is not reloading properly. Because of this, users browsing the domain are seeing error. Is there a way to force reloading haproxy? What I've been doing now is to remove the proxy service completely and creating it again.

**Comment by vfarcic** [comment]
I just added the `reload` endpoint. You can see the request format from the [reload](https://github.com/vfarcic/docker-flow-proxy#reload) section of the documentation.

Please note that this is only a workaround for your issue. My guess is that there's something wrong with Docker networking. I would appreciate if you could send me more info of the problem. It would help me diagnose the issue. It would be even better if you could ping me on Skype or HangOuts and share your screen.
