### ISSUE TITLE
HTTP/2 support ?

### ISSUE THREAD

**Issue by myuseringithub** [vfarcic/docker-flow-proxy#93]
Hi, I don't see any mention about http/2 support, this is crucial for modern web apps. Will it be added ?

If you could make this project pluggable it would make more sense, e.g. not limited to a default proxy. The project solves a lot and prevents maintenance of many different tools, but if it would be separated from using a specific proxy & limited configurations it would make more sense. I, for example, would like to test "redbird" proxy as it uses nodejs (https://github.com/OptimalBits/redbird), and it has some good features. But both of your projects mix a lot of the same features/components, if they are available separated and pluggable it would make more of custom & powerful combinations. 

Thanks so much for your book & all examples.

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I'll start working on http/2 in a few days.

I'm not sure what you mean by making the project pluggable? Do you mean plugging other proxies? If that's the case, I love the idea. Actually, that was the plan from the start. The only problem is that there's not enough time to do everything.

The project became relatively popular and I have more requests than contributors. Would you like to contribute? Any help would be welcome.

**Comment by myuseringithub** [comment]
Ya, this is what I meant. 
Thanks. Currently I'm not in a position where I can contribute.

**Comment by vfarcic** [comment]
It turns out that HAProxy does not yet really support HTTP/2.

I think that the best I can do for now is to detect a http/2 request and pass it to https tcp stream to a service that does support https and http/2. I'm not sure that is a good idea but, from what I understood, there aren't many other options until HAProxy starts supporting it fully.

**Comment by myuseringithub** [comment]
I see. I think for a project like that, you should've chosen Nodejs server as a proxy. Makes it more dynamic and it can be easily manipulated, and support for HTTP/2 exist in many other projects. Thank you checking this issue.

**Comment by vfarcic** [comment]
It's hard to say what would work better. HAProxy and nginx are known to outperform almost any other proxy known to men. On the other hand, they might not be as flexible and dynamic as other solutions.

**Comment by myuseringithub** [comment]
Btw, maybe creating a proxy server using Nodejs with Firebase (realtime key-value database with ability to save entire objects) could be an easy solution. Where DNS names, routing paths, forwarding configurations could be saved on a shared object on the database. What do you think ?

**Comment by myuseringithub** [comment]
Yes I see. It appears that there is still no robust Nodejs reverse proxy available.

**Comment by vfarcic** [comment]
I'd be very happy to do that. Can you help? My NodeJS skill are a bit rusty (haven't worked with it for a while). I can translate all the existing logic/features into anything else. I'd just need a guidance about the output.

In such a case, I could move HAProxy out of Docker Flow Proxy and let users choose whether they'd like to attach it (through networking) to HAProxy, NodeJS solution, or something else we'd support later on.

I don't think there's a need for Firebase since all the data is already stored in Docker and available through its API. We just need to fetch it.

**Comment by myuseringithub** [comment]
I will need to finish reading your book 2.1 first. I'm coming from PHP & Mysql background. Focusing now on building JS webapps with microservices architecture. This is where I needed to learn deployment with containers, and automate my workflow. I'm not an expert in any means. I'd try my best to contribute. Just need couple of weeks.

**Comment by hamburml** [comment]
I think your idea of detecting a http/2 stream and redirecting it to a service which supports http/2 (like nginx) is better than using a nodejs application as middleware. After searching the web I also found some guys who use haproxy and nginx together for http/2 (haproxy as load balancer, nginx for http/2 connection). Http/2 is known for it's performance boost compared to http or spdy. Nginx is faster than a nodejs app and therefore we would lose some of this performance boost.

Can you make an working example which uses haproxy as loadbalancer and nginx with working http/2? Or do you have a link which describes the setup?

**Comment by teohhanhui** [comment]
Lack of HTTP/2 support is a deal-breaker for us. Automagic offloading to nginx sounds good.

**Comment by teohhanhui** [comment]
Or indeed a docker-flow-proxy that uses nginx under the hood would be perfect. What does HAProxy bring to the table when it's not doing any load-balancing (since that's left to the Swarm routing mesh)?

**Comment by vfarcic** [comment]
@teohhanhui

> Or indeed a docker-flow-proxy that uses nginx under the hood would be perfect.

DFP code can be extended to support nginx as well. Indeed, the initial idea is to support multiple proxy backends. The only problem is time. There's never enough. Would you like to help? If you could, I'm sure that we could add nginx support.

> What does HAProxy bring to the table when it's not doing any load-balancing (since that's left to the Swarm routing mesh)?

Swarm does L4 proxy and is incapable of evaluating request paths, domains, and so on. It cannot forward to a specific service based on requests. HAProxy, nginx, and a miriad of others are L7 proxies that can do that. If you'd use only Swarm network, every service would need to expose a different port. If your cluster has only one public service, there's no need for anything else. If, on the other hand, you do have more, you'll need some kind of L7 proxy.

**Comment by teohhanhui** [comment]
> Swarm does L4 proxy and is incapable of evaluating request paths,
domains, and so on. It cannot forward to a specific service based on
requests. HAProxy, nginx, and a miriad of others are L7 proxies that can do
that.

I didn't make myself clear. What I mean is that HAProxy is not a
particularly good HTTP + TLS proxy, as can be attested to by the fact that
it still doesn't support HTTP/2. I thought its strong point is that it's a
good load balancer, so what do we gain by using it over nginx (which is a
pretty damn good HTTP + TLS proxy)?

**Comment by teohhanhui** [comment]
> DFP code can be extended to support nginx as well. Indeed, the initial
idea is to support multiple proxy backends. The only problem is time.
There's never enough. Would you like to help? If you could, I'm sure that
we could add nginx support.

I'd certainly love to make it work. Do you think we can run a separate
container using an unmodified nginx image? That'd be ideal, like what
jwilder/nginx-proxy does. So, I imagine the following services:
swarm-listener, nginx-gen, nginx

On 4 Apr 2017 13:01, "Teoh Han Hui" <teohhanhui@gmail.com> wrote:

> Swarm does L4 proxy and is incapable of evaluating request paths,
domains, and so on. It cannot forward to a specific service based on
requests. HAProxy, nginx, and a miriad of others are L7 proxies that can do
that.

I didn't make myself clear. What I mean is that HAProxy is not a
particularly good HTTP + TLS proxy, as can be attested to by the fact that
it still doesn't support HTTP/2. I thought its strong point is that it's a
good load balancer, so what do we gain by using it over nginx (which is a
pretty damn good HTTP + TLS proxy)?

**Comment by teohhanhui** [comment]
> Do you think we can run a separate container using an unmodified nginx image?

To answer my own question, we'd probably need to add an "agent" to the nginx container. It will be responsible for triggering SIGHUP for nginx config reload, through a HTTP request. Since it's not a good idea to run it as a separate process in the container, and since nginx supports fastcgi out of the box, https://golang.org/pkg/net/http/fcgi/ seems like a possible way of achieving that.

**Comment by hamburml** [comment]
FYI: Another possibility to allow backends/services to use http2 with DFP in front is to use ssl-passthrough setting https://serversforhackers.com/using-ssl-certificates-with-haproxy

I was able to use HAProxy as load balancer which doesn't terminates the ssl-connections but instead let's the backend handles it. That also means that mode tcp must be set in the haproxy.cfg in frontend and the backend.
